"""Numeric-comparison verifier: parse agent answer as number, compare to expected."""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""Numeric-comparison verifier — generated by nemotron_gym.

verifier_data.json:
  {
    "expected_value": float,
    "tolerance_abs": float (default 1e-6),
    "tolerance_rel": float (default 1e-6),
  }

Accepts the last numeric token found in /app/answer.txt (also unwraps
`\boxed{...}` if present). Passes iff |got - expected| <= max(abs_tol, rel_tol*|expected|).
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
ANSWER = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


def _extract_number(text: str) -> float | None:
    # Try \boxed{...} first.
    m = re.search(r"\\boxed\{([^}]+)\}", text)
    candidates = []
    if m:
        candidates.append(m.group(1))
    # Last numeric token in the whole text.
    nums = re.findall(r"[-+]?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?", text)
    if nums:
        candidates.append(nums[-1])
    for c in candidates:
        c = c.strip().replace(",", "")
        try:
            return float(c)
        except ValueError:
            continue
    return None


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    expected = data.get("expected_value")
    if not isinstance(expected, (int, float)):
        print("expected_value must be numeric", file=sys.stderr)
        return 0
    abs_tol = float(data.get("tolerance_abs", 1e-6))
    rel_tol = float(data.get("tolerance_rel", 1e-6))
    if not ANSWER.exists():
        print("/app/answer.txt missing", file=sys.stderr)
        return 0
    raw = ANSWER.read_text(errors="replace")
    got = _extract_number(raw)
    if got is None:
        print("no numeric value found in answer")
        return 0
    tol = max(abs_tol, rel_tol * abs(expected))
    delta = abs(got - float(expected))
    print(f"got={got} expected={expected} delta={delta:.3e} tol={tol:.3e}")
    score = 1 if delta <= tol else 0
    print("verdict:", "match" if score else "mismatch")
    return score


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
