"""ReasoningGym verifier: delegate to upstream reasoning_gym.score() if available."""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""ReasoningGym verifier — generated by nemotron_gym.

Tries `reasoning_gym` library's per-task scorer first; falls back to a
normalized exact-match against `answer`.
"""
from __future__ import annotations

import json
import pathlib
import re
import string
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
ANSWER = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


def _normalize(s: str) -> str:
    s = s.strip().lower()
    s = "".join(ch for ch in s if ch not in string.punctuation)
    return re.sub(r"\s+", " ", s).strip()


def _try_reasoning_gym(question: str, answer: str, entry: dict) -> int | None:
    """Returns 1/0 on a verdict, or None if reasoning_gym lib isn't usable.

    Uses reasoning_gym's public factory API: `get_score_answer_fn(name)` returns
    the dataset's `score_answer(answer, entry)` bound method, which yields a
    float in [0.0, 1.0]. We threshold at 0.5 for the binary verdict.
    """
    try:
        import reasoning_gym  # type: ignore
    except ImportError:
        return None
    source = entry.get("metadata", {}).get("source_dataset")
    if not source:
        return None
    # Prefer the v0.1.x factory API. Fall back to a legacy `get_scorer` shape
    # for older/forked versions of the library that exposed a different name.
    score_fn = None
    if hasattr(reasoning_gym, "get_score_answer_fn"):
        try:
            score_fn = reasoning_gym.get_score_answer_fn(source)
        except Exception as e:
            print(f"reasoning_gym.get_score_answer_fn({source!r}) failed: {e}")
            return None
    elif hasattr(reasoning_gym, "get_scorer"):
        try:
            score_fn = reasoning_gym.get_scorer(source)
        except Exception as e:
            print(f"reasoning_gym.get_scorer({source!r}) failed: {e}")
            return None
    else:
        print("reasoning_gym has neither get_score_answer_fn nor get_scorer")
        return None
    # reasoning_gym >= 0.1.19 expects (answer, entry) positionally; the entry
    # dict needs a top-level "metadata" passthrough (matches verifier_data.json
    # produced by the converter) plus the gold "answer".
    try:
        rg_entry = {"answer": entry.get("answer", ""), "metadata": entry.get("metadata", {})}
        score = score_fn(answer, rg_entry)
    except Exception as e:
        print(f"score_fn call failed: {e}")
        return None
    if isinstance(score, (int, float)):
        return 1 if score >= 0.5 else 0
    return None


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    question = data.get("question", "")
    expected = data.get("answer", "")
    if not isinstance(expected, str):
        print("answer must be str", file=sys.stderr)
        return 0
    if not ANSWER.exists():
        print("/app/answer.txt missing", file=sys.stderr)
        return 0
    got = ANSWER.read_text(errors="replace").strip()
    print(f"got={got[:200]!r} expected={expected[:200]!r}")
    rg_verdict = _try_reasoning_gym(question=question, answer=got, entry=data)
    if rg_verdict is not None:
        print(f"reasoning_gym verdict={rg_verdict}")
        return rg_verdict
    # Fallback: normalized exact-match.
    if _normalize(got) == _normalize(expected):
        print("verdict: normalized-match")
        return 1
    if expected and expected in got:
        print("verdict: substring-match")
        return 1
    print("verdict: mismatch")
    return 0


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
