"""Tool-call match verifier: agent emits JSON {name, arguments}, compare to gt."""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""Tool-call match verifier — generated by nemotron_gym.

The agent is asked to write a single JSON object to /app/answer.txt describing
the tool it would invoke:
  {"name": "tool_name", "arguments": { ... }}

The verifier checks against verifier_data.json's `expected` (a list of accepted
tool calls; passes if ANY one matches name+arguments). This is a *simplified*
substitute for the upstream stateful tool environment — multi-turn / stateful
tasks cannot be faithfully reproduced; single-step calls can.
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
ANSWER = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


def _parse_arguments(args: object) -> dict | None:
    if isinstance(args, dict):
        return args
    if isinstance(args, str):
        try:
            v = json.loads(args)
            if isinstance(v, dict):
                return v
        except Exception:
            return None
    return None


def _normalize(args: dict) -> dict:
    """Lowercase string values, strip whitespace, leave numerics alone."""
    out: dict = {}
    for k, v in args.items():
        if isinstance(v, str):
            out[k] = v.strip()
        else:
            out[k] = v
    return out


def _args_match(got: dict, expected: dict) -> bool:
    if set(got.keys()) != set(expected.keys()):
        return False
    for k, v in expected.items():
        g = got.get(k)
        if isinstance(v, str) and isinstance(g, str):
            if v.strip().lower() != g.strip().lower():
                return False
        else:
            if v != g:
                return False
    return True


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    expected = data.get("expected", [])
    if not isinstance(expected, list) or not expected:
        print("expected calls missing", file=sys.stderr)
        return 0
    if not ANSWER.exists():
        print("/app/answer.txt missing", file=sys.stderr)
        return 0
    raw = ANSWER.read_text(errors="replace")
    fence = re.search(r"```(?:json)?\s*(.*?)```", raw, flags=re.DOTALL)
    candidate = fence.group(1) if fence else raw
    try:
        got = json.loads(candidate)
    except Exception as e:
        print(f"agent did not emit valid JSON: {e}")
        return 0
    if not isinstance(got, dict):
        print(f"agent JSON not an object: {type(got).__name__}")
        return 0
    got_name = got.get("name")
    got_args_norm = _parse_arguments(got.get("arguments"))
    if not isinstance(got_name, str) or got_args_norm is None:
        print(f"agent JSON missing name/arguments: {got!r}")
        return 0
    got_args_norm = _normalize(got_args_norm)
    print(f"agent call: name={got_name!r} args={got_args_norm!r}")
    for i, ec in enumerate(expected):
        if not isinstance(ec, dict):
            continue
        en = ec.get("name")
        ea = _parse_arguments(ec.get("arguments"))
        if not isinstance(en, str) or ea is None:
            continue
        ea = _normalize(ea)
        print(f"  vs expected[{i}]: name={en!r} args={ea!r}")
        if got_name == en and _args_match(got_args_norm, ea):
            print("verdict: match")
            return 1
    print("verdict: mismatch")
    return 0


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
