#!/usr/bin/env python3
"""
exp_rpt_stack-php-v2 → v3 patcher.

Bug (v2-v2, found in QC 2026-05-15):
  After the earlier "tests_found gate" patch (patch_exp_rpt_stack_php_v2_tasks.py
  for this dataset, patch_stack_php_v3_tasks.py for stack-php-large-v2),
  100% of trials died at the very first phpunit invocation with:

      Running PHPUnit tests...
      PHPUnit 10.5.63 by Sebastian Bergmann and contributors.

      Unknown option "--fail-on-no-tests"
      exp_rpt_stack-php-v2 verifier: runner_rc=2 tests_run=0 failures=0 errors=0

  The previous patch used `--fail-on-no-tests`, which **does not exist** in
  PHPUnit 10.5.x. The correct flag is `--fail-on-empty-test-suite`. Source:
  https://github.com/sebastianbergmann/phpunit/blob/10.5.63/src/TextUI/Configuration/Cli/Builder.php

  As a second issue, the previous patch dropped the original v2's
  `phpunit --configuration /app/phpunit.xml` invocation and replaced it with
  bare `phpunit`. PHPUnit's default test-file pattern is `*Test.php`, but
  every task in this dataset stores its test class in `tests/TestSolution.php`
  (verified across 8 random samples and matches the upstream stack-php layout).
  Without an explicit phpunit.xml that maps the test file, even a fixed flag
  would yield zero discovered tests.

  Net effect of the v2-v2 patch: runner_rc=2, tests_run=0, reward=0 on every
  trial. Triage signature looked like a 100%-infra-ok / 0%-solve rubber-stamp,
  but the verifier was actually a *closed* gate — it just always failed.

Fix (v3):
  Rewrite `tests/test.sh` so it:
    1. Writes a self-contained `/app/phpunit.xml` that:
       - Bootstraps with vendor/autoload.php (composer-generated by the agent)
         if present, else falls back to /app/autoload.php (baked into the
         Dockerfile as an spl_autoload_register fallback).
       - Defines a `<testsuite>` pointing at `tests/TestSolution.php`
         explicitly (bypassing the `*Test.php` suffix requirement).
       - Sets PHPUnit 10 schema attributes (cacheDirectory, executionOrder,
         failOnEmptyTestSuite=true so empty suite → non-zero exit).
    2. Runs `phpunit --configuration /app/phpunit.xml --fail-on-skipped`
       — uses ONLY flags that exist in PHPUnit 10.5.x. The
       `failOnEmptyTestSuite=true` config attribute (PHPUnit 10-supported)
       handles the "no tests collected" case without a CLI flag.
    3. Parses the summary line (`OK (N tests, A assertions)` or
       `Tests: N, Assertions: A, Failures: F, Errors: E`) to extract a
       numeric tests_run / failures / errors signal — primary safety gate
       independent of the exit code.
    4. Requires runner_rc == 0 AND tests_run >= 1 AND failures == 0
       AND errors == 0 to score reward=1. Anything else = 0.

  Idempotency marker (distinct from prior patches so we can tell which
  patcher version produced a given test.sh by grep):
      `# --- laion exp_rpt_stack-php-v2 v3 patch: phpunit_xml + tests_found gate ---`

If a task has no `tests/test.sh` or its existing test.sh has no `phpunit`
invocation, it is left untouched and counted as `skipped_no_phpunit`.

Usage:
  python data/patchers/patch_exp_rpt_stack_php_v2_v3_tasks.py \
      --root <dir> [--dry-run] [--limit N]

Constraints (per upload spec):
  - Only `tests/test.sh` is touched. instruction.md, TestSolution.php,
    environment/Dockerfile, etc. are preserved verbatim.
  - The same fix applies to the sibling stack-php-large-v2 dataset; a
    parallel agent should apply this same template (with whatever
    marker / repo name it chooses) to that tarball.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Marker we drop into the new test.sh so re-runs are idempotent.
# Distinct from the prior `# --- laion exp_rpt_stack-php-v2 patch: tests_found gate ---`
# (v2-v2 patch) and `# --- laion v3 patch: tests_found gate ---` (stack-php-large
# v3 patch) markers so we can grep-identify which generation produced a file.
PATCH_MARKER = (
    "# --- laion exp_rpt_stack-php-v2 v3 patch: phpunit_xml + tests_found gate ---"
)

# Markers from earlier patch generations — we want to overwrite both of these.
PRIOR_MARKERS = (
    "# --- laion exp_rpt_stack-php-v2 patch: tests_found gate ---",
    "# --- laion v3 patch: tests_found gate ---",
)

# The new test.sh body. Key differences from the v2-v2 patch:
#   - Generates /app/phpunit.xml on the fly (the v2-v2 patch dropped this,
#     which broke test discovery for `TestSolution.php` since it doesn't
#     match PHPUnit's default `*Test.php` suffix).
#   - Uses `--fail-on-skipped` only (a valid PHPUnit 10.5 flag) and relies on
#     the phpunit.xml `failOnEmptyTestSuite="true"` attribute for the
#     no-tests-collected case. The v2-v2 patch used `--fail-on-no-tests`
#     which does not exist in PHPUnit 10.5.x and crashed every trial with
#     "Unknown option" before any tests could run.
#   - Bootstraps with vendor/autoload.php (if the agent ran `composer
#     dump-autoload`) and falls back to /app/autoload.php (baked into the
#     Dockerfile). The shell-side picks whichever exists at runtime.
#   - Keeps the same tests_run >= 1 / failures == 0 / errors == 0 gate as
#     the primary success criterion, independent of exit code.
NEW_TEST_SH = """#!/bin/bash
# --- laion exp_rpt_stack-php-v2 v3 patch: phpunit_xml + tests_found gate ---
# Verifier: gate reward on (a) PHPUnit exiting cleanly AND (b) PHPUnit
# reporting at least one test actually executed (and zero failures/errors).
#
# History:
#   v2 (upstream)   : trap-based scoring on `phpunit` exit. PHPUnit 10
#                     exits 0 on "No tests executed!", so any zero-exit
#                     invocation scored reward=1 → 100% rubber-stamp.
#   v2-v2 (broken)  : tried to gate via `--fail-on-no-tests`, which does
#                     NOT exist in PHPUnit 10.5.x → "Unknown option" at
#                     argument parsing → runner_rc=2 → reward=0 on every
#                     trial (100% trials died before any test ran).
#   v3 (this file)  : generate phpunit.xml explicitly mapping
#                     tests/TestSolution.php; use only PHPUnit-10.5-valid
#                     flags; gate on parsed tests_run >= 1.

set +e
mkdir -p /logs/verifier
echo "0" > /logs/verifier/reward.txt
cd /app

# Pick the strongest autoload available at runtime.
#   - vendor/autoload.php: composer-generated, used when the agent runs
#     `composer dump-autoload` (typical for psr-4 namespaces). This is the
#     primary path for tasks with non-trivial namespace mappings.
#   - /app/autoload.php  : baked into the Dockerfile as an
#     spl_autoload_register fallback for `<ns>\\<class>` → `/app/<path>.php`.
if [ -f /app/vendor/autoload.php ]; then
    BOOTSTRAP="/app/vendor/autoload.php"
elif [ -f /app/autoload.php ]; then
    BOOTSTRAP="/app/autoload.php"
else
    # If neither exists, write a tiny one inline so PHPUnit can bootstrap
    # to *something* and the test class load path becomes a deterministic
    # error rather than a missing-bootstrap silent skip.
    cat > /app/autoload.php <<'AUTOLOAD'
<?php
spl_autoload_register(function($class) {
    $file = "/app/" . str_replace("\\\\", "/", $class) . ".php";
    if (file_exists($file)) { require $file; }
});
AUTOLOAD
    BOOTSTRAP="/app/autoload.php"
fi

# Generate phpunit.xml that explicitly maps tests/TestSolution.php.
# PHPUnit 10's default test-file suffix is `Test.php`; this dataset uses
# `TestSolution.php`, so we MUST point at the file by name in <file>.
#
# failOnEmptyTestSuite="true" → PHPUnit 10 exits non-zero if zero tests
# were collected (replaces the non-existent --fail-on-no-tests CLI flag).
# beStrictAboutOutputDuringTests=false keeps stray echo/print from tests
# (or autoload paths) from being escalated to failures.
cat > /app/phpunit.xml <<XMLEOF
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/10.5/phpunit.xsd"
    bootstrap="${BOOTSTRAP}"
    cacheDirectory=".phpunit.cache"
    executionOrder="default"
    beStrictAboutOutputDuringTests="false"
    failOnEmptyTestSuite="true"
    colors="false">
    <testsuites>
        <testsuite name="solution">
            <file>tests/TestSolution.php</file>
        </testsuite>
    </testsuites>
</phpunit>
XMLEOF

echo "Running PHPUnit tests..."
# Only valid PHPUnit 10.5 flags. --fail-on-skipped is real; the
# no-tests-collected case is handled via failOnEmptyTestSuite in the XML.
phpunit --configuration /app/phpunit.xml --fail-on-skipped 2>&1 \\
    | tee /logs/verifier/test_output.txt
runner_rc=${PIPESTATUS[0]}

# PHPUnit 10 summary line shapes (most-common first):
#   "OK (3 tests, 5 assertions)"
#   "Tests: 3, Assertions: 5, Failures: 0, Errors: 0"
#   "No tests executed!"   ← still possible if XML resolves to empty suite
ok_line=$(grep -oE 'OK \\([0-9]+ tests?, [0-9]+ assertions?\\)' \\
    /logs/verifier/test_output.txt | tail -1)
detail_line=$(grep -oE 'Tests: [0-9]+(, Assertions: [0-9]+)?(, Failures: [0-9]+)?(, Errors: [0-9]+)?' \\
    /logs/verifier/test_output.txt | tail -1)

tests_run=0
failures=0
errors=0
if [ -n "$ok_line" ]; then
    tests_run=$(echo "$ok_line" | grep -oE '[0-9]+' | head -1)
elif [ -n "$detail_line" ]; then
    tests_run=$(echo "$detail_line" | grep -oE 'Tests: [0-9]+' | grep -oE '[0-9]+' | head -1)
    failures=$(echo "$detail_line" | grep -oE 'Failures: [0-9]+' | grep -oE '[0-9]+' | head -1)
    errors=$(echo "$detail_line"   | grep -oE 'Errors: [0-9]+'   | grep -oE '[0-9]+' | head -1)
fi
tests_run=${tests_run:-0}
failures=${failures:-0}
errors=${errors:-0}

echo "exp_rpt_stack-php-v2 v3 verifier: runner_rc=$runner_rc tests_run=$tests_run failures=$failures errors=$errors bootstrap=$BOOTSTRAP"

if [ "$runner_rc" -eq 0 ] \\
        && [ "$tests_run" -ge 1 ] \\
        && [ "$failures" -eq 0 ] \\
        && [ "$errors" -eq 0 ]; then
    echo "1" > /logs/verifier/reward.txt
    exit 0
else
    echo "0" > /logs/verifier/reward.txt
    if [ "$runner_rc" -ne 0 ]; then exit "$runner_rc"; fi
    exit 1
fi
"""


def patch_one(test_sh: Path, dry_run: bool) -> str:
    """Patch a single tests/test.sh file. Returns one of:
    'patched_from_v2_v2', 'patched_from_v3_large', 'patched_from_original',
    'patched_unusual', 'already', 'missing', 'skipped_no_phpunit',
    'unparseable'.
    """
    if not test_sh.is_file():
        return "missing"
    try:
        existing = test_sh.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return "unparseable"
    if PATCH_MARKER in existing:
        return "already"

    # Skip tasks whose test.sh doesn't actually invoke phpunit — they're not
    # PHPUnit tasks (or use some other harness) and we'd corrupt them by
    # replacing the file with our PHPUnit-specific gate.
    if "phpunit" not in existing.lower():
        return "skipped_no_phpunit"

    # Classify the prior generation so the summary can report what we're
    # overwriting (sanity / forensics).
    if PRIOR_MARKERS[0] in existing:
        source = "patched_from_v2_v2"
    elif PRIOR_MARKERS[1] in existing:
        source = "patched_from_v3_large"
    elif "trap cleanup EXIT" in existing:
        # Original v2 upstream (trap-based scoring) — pre-any-patch state.
        source = "patched_from_original"
    else:
        source = "patched_unusual"

    if not dry_run:
        test_sh.write_text(NEW_TEST_SH, encoding="utf-8")
    return source


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--root", required=True, help="Path to extracted tasks root")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--limit", type=int, default=0)
    args = p.parse_args()

    root = Path(args.root).expanduser().resolve()
    if not root.is_dir():
        print(f"Not a directory: {root}", file=sys.stderr)
        return 2

    task_dirs = sorted(d for d in root.iterdir() if d.is_dir())
    if args.limit:
        task_dirs = task_dirs[: args.limit]

    n_total = len(task_dirs)
    counts = {
        "patched_from_v2_v2": 0,
        "patched_from_v3_large": 0,
        "patched_from_original": 0,
        "patched_unusual": 0,
        "already": 0,
        "missing": 0,
        "skipped_no_phpunit": 0,
        "unparseable": 0,
    }

    for i, td in enumerate(task_dirs, 1):
        test_sh = td / "tests" / "test.sh"
        result = patch_one(test_sh, dry_run=args.dry_run)
        counts[result] = counts.get(result, 0) + 1

        if i % 1000 == 0 or i == n_total:
            print(
                f"[{i}/{n_total}] "
                f"from_v2_v2={counts['patched_from_v2_v2']} "
                f"from_v3_large={counts['patched_from_v3_large']} "
                f"from_original={counts['patched_from_original']} "
                f"unusual={counts['patched_unusual']} "
                f"already={counts['already']} missing={counts['missing']} "
                f"skipped_no_phpunit={counts['skipped_no_phpunit']} "
                f"unparseable={counts['unparseable']}",
                flush=True,
            )

    print(
        f"\nDone. total={n_total} "
        f"patched_from_v2_v2={counts['patched_from_v2_v2']} "
        f"patched_from_v3_large={counts['patched_from_v3_large']} "
        f"patched_from_original={counts['patched_from_original']} "
        f"patched_unusual={counts['patched_unusual']} "
        f"already_patched={counts['already']} "
        f"missing={counts['missing']} "
        f"skipped_no_phpunit={counts['skipped_no_phpunit']} "
        f"unparseable={counts['unparseable']} "
        f"(dry_run={args.dry_run})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
