# Licensed under the Apache License, Version 2.0 (see LICENSE).
"""Sprint-11 Wave-6 — Adapter to the official ARC-AGI-3-Agents harness.

The official ``arcprize/ARC-AGI-3-Agents`` harness drives every game
through subclasses of its own :class:`agents.agent.Agent` ABC. Cognithor
ships :class:`CognithorPSEAgent` typed against local Protocols
(:mod:`.protocol`), so the two are *duck-compatible* — every Cognithor
agent implements the right method names with the right shapes. The
adapter just needs to wrap our agent in a class the harness can
recognise.

This module ships :func:`cognithor_agent_factory`: pass a
:class:`CognithorPSEAgent` delegate and an optional list of agentops
tags, get back a class the harness can register in
``agents.AVAILABLE_AGENTS``.

The factory **lazy-imports** ``agents.agent.Agent`` so this module
loads cleanly without ``arc-agi`` / ``arcengine`` installed. If the
harness isn't available, the factory raises a clear
:class:`ImportError` with the install instructions.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from cognithor.channels.program_synthesis.arc_agi3.agent import (
        CognithorPSEAgent,
    )


_HARNESS_INSTALL_HINT = (
    "The official ARC-AGI-3-Agents harness is not installed.\n"
    "Install instructions:\n"
    "  1. git clone https://github.com/arcprize/ARC-AGI-3-Agents.git\n"
    "  2. cd ARC-AGI-3-Agents && uv sync\n"
    "  3. uv pip install -e /path/to/cognithor\n"
    "Then call cognithor_agent_factory inside a Python invocation\n"
    "that has the harness on its sys.path (typically: from inside\n"
    "ARC-AGI-3-Agents itself, with `uv run`)."
)


def cognithor_agent_factory(
    *,
    delegate: CognithorPSEAgent,
    name_suffix: str = "",
    extra_tags: list[str] | None = None,
) -> type:
    """Return a harness-compatible Agent class that delegates to *delegate*.

    The returned class:

    * subclasses ``agents.agent.Agent`` (the official ABC)
    * forwards :meth:`is_done` and :meth:`choose_action` to *delegate*
    * adds ``"cognithor"`` and any ``extra_tags`` to the harness's
      tag list (for AgentOps + scorecard filtering)
    * names itself ``"Cognithor" + delegate.__class__.__name__ + name_suffix``
      so registration in ``agents.AVAILABLE_AGENTS`` is unambiguous

    Raises :class:`ImportError` if the harness isn't installed.
    """
    try:
        from agents.agent import Agent as _HarnessAgent
    except ImportError as exc:
        raise ImportError(_HARNESS_INSTALL_HINT) from exc

    class _CognithorHarnessAgent(_HarnessAgent):  # type: ignore[misc]
        """Auto-generated by cognithor_agent_factory."""

        def __init__(self, *args: Any, **kwargs: Any) -> None:
            super().__init__(*args, **kwargs)
            tags: list[str] = list(getattr(self, "tags", []) or [])
            if "cognithor" not in tags:
                tags.append("cognithor")
            if extra_tags is not None:
                tags.extend(t for t in extra_tags if t not in tags)
            self.tags = tags
            self._delegate = delegate

        def is_done(self, frames: list[Any], latest_frame: Any) -> bool:
            return self._delegate.is_done(frames, latest_frame)

        def choose_action(self, frames: list[Any], latest_frame: Any) -> Any:
            return self._delegate.choose_action(frames, latest_frame)

    cls_name = f"Cognithor{type(delegate).__name__}{name_suffix}"
    _CognithorHarnessAgent.__name__ = cls_name
    _CognithorHarnessAgent.__qualname__ = cls_name
    return _CognithorHarnessAgent


__all__ = ["cognithor_agent_factory"]
