#!/usr/bin/env python3
"""Deterministic test→assert scanner; no production files modified.

Method: Método de trabajo/registro de plugins/GUIA_REGISTRO_PLUGINS_Y_CABLEADO.md
This exporter is stable after registration; future wiring must use the registered
plugin/contract connection rather than editing the generated artifact.
"""
from __future__ import annotations
import ast, json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[3]
ROOTS = [ROOT / "extensions/wordflow/tests", ROOT / "extensions/wordflow_kernel/tests"]
OUT = ROOT / "agente-yaiwes/code-programming-engine/module-tests"

def scan(path: Path) -> dict:
    text = path.read_text(encoding="utf-8", errors="replace")
    try: tree = ast.parse(text)
    except SyntaxError as e: return {"path":str(path.relative_to(ROOT)),"parse":"FAIL","error":str(e),"asserts":[]}
    hits=[]
    for node in ast.walk(tree):
        if isinstance(node, ast.Assert): hits.append({"line":node.lineno,"kind":"assert"})
        elif isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and node.func.attr.startswith("assert"):
            hits.append({"line":node.lineno,"kind":node.func.attr})
    return {"path":str(path.relative_to(ROOT)),"parse":"PASS","assert_count":len(hits),"asserts":hits}

def main():
    files=sorted({p for root in ROOTS if root.exists() for p in root.rglob("test_*.py")})
    data={"roots":[str(p.relative_to(ROOT)) for p in ROOTS],"file_count":len(files),"files":[scan(p) for p in files]}
    OUT.mkdir(parents=True,exist_ok=True)
    (OUT/"TEST_ASSERT_INDEX.json").write_text(json.dumps(data,indent=2,sort_keys=True)+"\n",encoding="utf-8")
    lines=["# TEST → ASSERT INDEX","","Generated by `Refactoria/G3/new/build_test_assert_index.py`.",f"Test files: {len(files)}","","| Test | Parse | Asserts |","|---|---|---:|"]
    for row in data["files"]: lines.append(f'| `{row["path"]}` | {row["parse"]} | {row.get("assert_count","-")} |')
    (OUT/"TEST_ASSERT_INDEX.md").write_text("\n".join(lines)+"\n",encoding="utf-8")
if __name__=="__main__": main()
