"""desplegador.py v2 — plan.json → repos_listos + git · 0% LLM · idempotente
SOURCE: DESPLIEGUE-DETERMINISTA-UNIVERSAL-v2 PASO 2
"""
from __future__ import annotations
import argparse
import json
import shutil
import subprocess
from pathlib import Path
from typing import Any


def run(cmd: list[str], cwd: Path | None = None) -> None:
    subprocess.run(cmd, cwd=cwd, check=True, capture_output=True)


def desplegar(project_root: str | Path, plan_path: str | Path, staging: str | Path) -> dict[str, Any]:
    """API legacy: un staging plano."""
    root = Path(project_root)
    plan = json.loads(Path(plan_path).read_text(encoding="utf-8"))
    if plan.get("SIN_REGLA") or plan.get("BLOQUEADOS"):
        return {"ok": False, "error": "SIN_REGLA o BLOQUEADOS — abort"}
    stage = Path(staging)
    stage.mkdir(parents=True, exist_ok=True)
    copied: list[str] = []
    for item in plan.get("mapped", []):
        src = root / item["src"]
        if not src.exists():
            continue
        dest = stage / item["src"]
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)
        copied.append(item["src"])
    return {"ok": True, "copied": copied, "staging": str(stage)}


def deploy_by_repo(root: Path, plan_path: Path, out_dir: Path) -> dict:
    plan = json.loads(plan_path.read_text(encoding="utf-8"))
    if plan.get("SIN_REGLA") or plan.get("BLOQUEADOS"):
        return {"ok": False, "error": "SIN_REGLA o BLOQUEADOS — abort"}
    mapped = plan.get("mapped") or []
    by_repo: dict[str, list[str]] = {}
    for item in mapped:
        by_repo.setdefault(item.get("dest", "default"), []).append(item["src"])
    if not by_repo and plan.get("repos"):
        by_repo = {k: list(v) for k, v in plan["repos"].items()}
    out_dir.mkdir(parents=True, exist_ok=True)
    summary: dict = {"ok": True, "repos": {}}
    for repo, files in by_repo.items():
        repo_path = out_dir / repo
        if repo_path.exists():
            shutil.rmtree(repo_path)
        repo_path.mkdir(parents=True)
        for rel in files:
            src = root / rel
            if not src.is_file():
                continue
            dest = repo_path / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dest)
        readme = repo_path / "README.md"
        if not readme.exists():
            readme.write_text(f"# {repo}\n\nAuto-generated by desplegador v2.\n", encoding="utf-8")
        if not (repo_path / ".git").exists():
            run(["git", "init"], cwd=repo_path)
            run(["git", "config", "user.email", "deploy@local"], cwd=repo_path)
            run(["git", "config", "user.name", "desplegador"], cwd=repo_path)
        run(["git", "add", "-A"], cwd=repo_path)
        subprocess.run(
            ["git", "commit", "-m", "deploy: snapshot determinista"],
            cwd=repo_path, capture_output=True,
        )
        n = sum(1 for p in repo_path.rglob("*") if p.is_file() and ".git" not in p.parts)
        summary["repos"][repo] = {"files": n, "path": str(repo_path)}
    return summary


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("root", type=Path, nargs="?", default=Path("."))
    ap.add_argument("out", type=Path, nargs="?", default=Path("repos_listos"))
    ap.add_argument("--plan", type=Path, default=Path("plan.json"))
    args = ap.parse_args()
    if not args.plan.is_file():
        print(f"missing {args.plan}")
        return 1
    summary = deploy_by_repo(args.root.resolve(), args.plan, args.out.resolve())
    print(json.dumps(summary, indent=2))
    return 0 if summary.get("ok") else 1


if __name__ == "__main__":
    raise SystemExit(main())
