// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/cadence/common/quotas (interfaces: Policy)
//
// Generated by this command:
//
//	mockgen -package=quotas -destination=policy_mock.go github.com/uber/cadence/common/quotas Policy
//

// Package quotas is a generated GoMock package.
package quotas

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPolicy is a mock of Policy interface.
type MockPolicy struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyMockRecorder
	isgomock struct{}
}

// MockPolicyMockRecorder is the mock recorder for MockPolicy.
type MockPolicyMockRecorder struct {
	mock *MockPolicy
}

// NewMockPolicy creates a new mock instance.
func NewMockPolicy(ctrl *gomock.Controller) *MockPolicy {
	mock := &MockPolicy{ctrl: ctrl}
	mock.recorder = &MockPolicyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicy) EXPECT() *MockPolicyMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockPolicy) Allow(info Info) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", info)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Allow indicates an expected call of Allow.
func (mr *MockPolicyMockRecorder) Allow(info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockPolicy)(nil).Allow), info)
}

// Wait mocks base method.
func (m *MockPolicy) Wait(ctx context.Context, info Info) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", ctx, info)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockPolicyMockRecorder) Wait(ctx, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockPolicy)(nil).Wait), ctx, info)
}
