const SOURCE_ID = "da4d3d3a97b9ed26e47b50d9a5d2f5795434467e001f8a6deba72c361a23baa7";
function _yaiwesCheckpoint(step, payload = {}) { return {schema:'yaiwes.internal.persistence/v5', source_id:SOURCE_ID, step, payload, status:'CHECKPOINTED'}; }
export function yaiwesPersistenceStep(payload = {}) { return _yaiwesCheckpoint('yaiwesPersistenceStep', payload); }
export function admitReadyTasks(...args) { return _yaiwesCheckpoint("admitReadyTasks", {args_count: args.length}); }
export function appendLimitedUnique(...args) { return _yaiwesCheckpoint("appendLimitedUnique", {args_count: args.length}); }
export function attachTaskResultProjectionReferences(...args) { return _yaiwesCheckpoint("attachTaskResultProjectionReferences", {args_count: args.length}); }
export function budgetStatusSnapshot(...args) { return _yaiwesCheckpoint("budgetStatusSnapshot", {args_count: args.length}); }
export function budgetStatusSteerKey(...args) { return _yaiwesCheckpoint("budgetStatusSteerKey", {args_count: args.length}); }
export function captureSequencesFromError(...args) { return _yaiwesCheckpoint("captureSequencesFromError", {args_count: args.length}); }
export function classifyExecutorProviderFailure(...args) { return _yaiwesCheckpoint("classifyExecutorProviderFailure", {args_count: args.length}); }
export function classifyPlannerProviderFailure(...args) { return _yaiwesCheckpoint("classifyPlannerProviderFailure", {args_count: args.length}); }
export function cloneTaskSupervisionState(...args) { return _yaiwesCheckpoint("cloneTaskSupervisionState", {args_count: args.length}); }
export function collectTextFragments(...args) { return _yaiwesCheckpoint("collectTextFragments", {args_count: args.length}); }
export function compactExecutorGraphClosure(...args) { return _yaiwesCheckpoint("compactExecutorGraphClosure", {args_count: args.length}); }
export function compactExecutorProperty(...args) { return _yaiwesCheckpoint("compactExecutorProperty", {args_count: args.length}); }
export function compactNodeProperties(...args) { return _yaiwesCheckpoint("compactNodeProperties", {args_count: args.length}); }
export function compactProjectorConnectivityContext(...args) { return _yaiwesCheckpoint("compactProjectorConnectivityContext", {args_count: args.length}); }
export function compactSupervisorRelevantKnowledge(...args) { return _yaiwesCheckpoint("compactSupervisorRelevantKnowledge", {args_count: args.length}); }
export function controlSignalForEpochOutcome(...args) { return _yaiwesCheckpoint("controlSignalForEpochOutcome", {args_count: args.length}); }
export function controlSignalForTaskResult(...args) { return _yaiwesCheckpoint("controlSignalForTaskResult", {args_count: args.length}); }
export function createExecutionBrief(...args) { return _yaiwesCheckpoint("createExecutionBrief", {args_count: args.length}); }
export function createFallbackObserverDelta(...args) { return _yaiwesCheckpoint("createFallbackObserverDelta", {args_count: args.length}); }
export function createInitialTaskSupervisionState(...args) { return _yaiwesCheckpoint("createInitialTaskSupervisionState", {args_count: args.length}); }
export function createRuntimeAbortContext(...args) { return _yaiwesCheckpoint("createRuntimeAbortContext", {args_count: args.length}); }
export function createTaskOutcome(...args) { return _yaiwesCheckpoint("createTaskOutcome", {args_count: args.length}); }
export function dedupeStrings(...args) { return _yaiwesCheckpoint("dedupeStrings", {args_count: args.length}); }
export function deriveTaskDefinitionReadiness(...args) { return _yaiwesCheckpoint("deriveTaskDefinitionReadiness", {args_count: args.length}); }
export function diffPiSessionStats(...args) { return _yaiwesCheckpoint("diffPiSessionStats", {args_count: args.length}); }
export function disposeSession(...args) { return _yaiwesCheckpoint("disposeSession", {args_count: args.length}); }
export function ensureTaskBudget(...args) { return _yaiwesCheckpoint("ensureTaskBudget", {args_count: args.length}); }
export function errorMessageFromUnknown(...args) { return _yaiwesCheckpoint("errorMessageFromUnknown", {args_count: args.length}); }
export function eventText(...args) { return _yaiwesCheckpoint("eventText", {args_count: args.length}); }
export function executorContinuedAfterHandoffAdvice(...args) { return _yaiwesCheckpoint("executorContinuedAfterHandoffAdvice", {args_count: args.length}); }
export function formatExecutorBudgetStatus(...args) { return _yaiwesCheckpoint("formatExecutorBudgetStatus", {args_count: args.length}); }
export function formatSupervisorHandoffAdvice(...args) { return _yaiwesCheckpoint("formatSupervisorHandoffAdvice", {args_count: args.length}); }
export function inferTaskPhase(...args) { return _yaiwesCheckpoint("inferTaskPhase", {args_count: args.length}); }
export function ipv4AddressInCidr(...args) { return _yaiwesCheckpoint("ipv4AddressInCidr", {args_count: args.length}); }
export function ipv4AddressValue(...args) { return _yaiwesCheckpoint("ipv4AddressValue", {args_count: args.length}); }
export function isCheckpointControlSignal(...args) { return _yaiwesCheckpoint("isCheckpointControlSignal", {args_count: args.length}); }
export function isControlSignalDecision(...args) { return _yaiwesCheckpoint("isControlSignalDecision", {args_count: args.length}); }
export function isCountableExecutorTurn(...args) { return _yaiwesCheckpoint("isCountableExecutorTurn", {args_count: args.length}); }
export function isRecord(...args) { return _yaiwesCheckpoint("isRecord", {args_count: args.length}); }
export function isRetryablePlannerInvocationError(...args) { return _yaiwesCheckpoint("isRetryablePlannerInvocationError", {args_count: args.length}); }
export function isRuntimeContextArtifact(...args) { return _yaiwesCheckpoint("isRuntimeContextArtifact", {args_count: args.length}); }
export function isSupervisorHandoffAdvice(...args) { return _yaiwesCheckpoint("isSupervisorHandoffAdvice", {args_count: args.length}); }
export function isTaskResultStatus(...args) { return _yaiwesCheckpoint("isTaskResultStatus", {args_count: args.length}); }
export function mergeProjectionFragmentDeltas(...args) { return _yaiwesCheckpoint("mergeProjectionFragmentDeltas", {args_count: args.length}); }
export function normalizeBudgetNumber(...args) { return _yaiwesCheckpoint("normalizeBudgetNumber", {args_count: args.length}); }
export function normalizeControlSignal(...args) { return _yaiwesCheckpoint("normalizeControlSignal", {args_count: args.length}); }
export function normalizeGraphDelta(...args) { return _yaiwesCheckpoint("normalizeGraphDelta", {args_count: args.length}); }
export function normalizeInitialTaskBudget(...args) { return _yaiwesCheckpoint("normalizeInitialTaskBudget", {args_count: args.length}); }
export function normalizeObserverProjection(...args) { return _yaiwesCheckpoint("normalizeObserverProjection", {args_count: args.length}); }
export function normalizeParallelTaskLimit(...args) { return _yaiwesCheckpoint("normalizeParallelTaskLimit", {args_count: args.length}); }
export function normalizeProjectorGraphDelta(...args) { return _yaiwesCheckpoint("normalizeProjectorGraphDelta", {args_count: args.length}); }
export function normalizeRunTimeBudgetMs(...args) { return _yaiwesCheckpoint("normalizeRunTimeBudgetMs", {args_count: args.length}); }
export function normalizeSupervisorControlSignal(...args) { return _yaiwesCheckpoint("normalizeSupervisorControlSignal", {args_count: args.length}); }
export function normalizeTaskBudget(...args) { return _yaiwesCheckpoint("normalizeTaskBudget", {args_count: args.length}); }
export function normalizeTaskResult(...args) { return _yaiwesCheckpoint("normalizeTaskResult", {args_count: args.length}); }
export function positiveIntegerEnv(...args) { return _yaiwesCheckpoint("positiveIntegerEnv", {args_count: args.length}); }
export function projectionAttemptRef(...args) { return _yaiwesCheckpoint("projectionAttemptRef", {args_count: args.length}); }
export function projectionPlaceholder(...args) { return _yaiwesCheckpoint("projectionPlaceholder", {args_count: args.length}); }
export function projectionRequestPriority(...args) { return _yaiwesCheckpoint("projectionRequestPriority", {args_count: args.length}); }
export function providerMessageFromOutput(...args) { return _yaiwesCheckpoint("providerMessageFromOutput", {args_count: args.length}); }
export function raceWithTimeout(...args) { return _yaiwesCheckpoint("raceWithTimeout", {args_count: args.length}); }
export function readPiSessionStats(...args) { return _yaiwesCheckpoint("readPiSessionStats", {args_count: args.length}); }
export function remainingTurns(...args) { return _yaiwesCheckpoint("remainingTurns", {args_count: args.length}); }
export function renderProjectorTaskResult(...args) { return _yaiwesCheckpoint("renderProjectorTaskResult", {args_count: args.length}); }
export function restoreTaskSupervisionState(...args) { return _yaiwesCheckpoint("restoreTaskSupervisionState", {args_count: args.length}); }
export function routeMatchesProjectionAnchors(...args) { return _yaiwesCheckpoint("routeMatchesProjectionAnchors", {args_count: args.length}); }
export function runtimeAbortKindForControlSignal(...args) { return _yaiwesCheckpoint("runtimeAbortKindForControlSignal", {args_count: args.length}); }
export function selectRecentExecutorTurnEvents(...args) { return _yaiwesCheckpoint("selectRecentExecutorTurnEvents", {args_count: args.length}); }
export function shouldStopExecutorForControlSignal(...args) { return _yaiwesCheckpoint("shouldStopExecutorForControlSignal", {args_count: args.length}); }
export function sleep(...args) { return _yaiwesCheckpoint("sleep", {args_count: args.length}); }
export function stringArrayProperty(...args) { return _yaiwesCheckpoint("stringArrayProperty", {args_count: args.length}); }
export function stringProperty(...args) { return _yaiwesCheckpoint("stringProperty", {args_count: args.length}); }
export function supervisionStateForPrompt(...args) { return _yaiwesCheckpoint("supervisionStateForPrompt", {args_count: args.length}); }
export function taskKnowledgeAnchors(...args) { return _yaiwesCheckpoint("taskKnowledgeAnchors", {args_count: args.length}); }
export function taskObjectiveRevision(...args) { return _yaiwesCheckpoint("taskObjectiveRevision", {args_count: args.length}); }
export function taskResultFromOutcome(...args) { return _yaiwesCheckpoint("taskResultFromOutcome", {args_count: args.length}); }
export function taskTurnIdentity(...args) { return _yaiwesCheckpoint("taskTurnIdentity", {args_count: args.length}); }
export function terminationReasonForEpochOutcome(...args) { return _yaiwesCheckpoint("terminationReasonForEpochOutcome", {args_count: args.length}); }
export function terminationReasonForTaskResult(...args) { return _yaiwesCheckpoint("terminationReasonForTaskResult", {args_count: args.length}); }
export function toolResultFingerprint(...args) { return _yaiwesCheckpoint("toolResultFingerprint", {args_count: args.length}); }
export function truncateOneLine(...args) { return _yaiwesCheckpoint("truncateOneLine", {args_count: args.length}); }
export function truncateText(...args) { return _yaiwesCheckpoint("truncateText", {args_count: args.length}); }
export function turnWindowCount(...args) { return _yaiwesCheckpoint("turnWindowCount", {args_count: args.length}); }
export function updateTaskSupervisionState(...args) { return _yaiwesCheckpoint("updateTaskSupervisionState", {args_count: args.length}); }
export function withDefaultSourceEventIds(...args) { return _yaiwesCheckpoint("withDefaultSourceEventIds", {args_count: args.length}); }
export function withTimeout(...args) { return _yaiwesCheckpoint("withTimeout", {args_count: args.length}); }
export default yaiwesPersistenceStep;
