//! Unified asset store — central binary storage with JSON metadata index.
//!
//! Stores images, audio, video, and other binary assets in a flat directory
//! (`{root}/{uuid}.{ext}`), with a `index.json` manifest for browsing,
//! filtering, and metadata (source, tags, dimensions).
//!
//! Implements [`ImageSink`] so generated images (chat, CLI, cron, A2A) are
//! written and indexed atomically — no registration gap.
//!
//! Files are served **path-based** via `GET /api/assets/{name}` (public route,
//! same pattern as `image_routes.rs`). The index is metadata-only — a file is
//! fetchable the moment it hits disk, independent of whether `index.json` has
//! been updated yet.

use std::path::{Path, PathBuf};

use parking_lot::RwLock;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::image_gen::{ImageGenError, ImageSink};

/// Where an asset originated.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum AssetSource {
    /// Interactive upload from the asset gallery.
    Upload,
    /// Pasted or dragged into the knowledge markdown editor.
    EditorPaste,
    /// Attached to a chat message.
    ChatAttach,
    /// Generated by the image-generation tool.
    Generated,
    /// Saved from a web-search result.
    WebSearch,
    /// Imported from an external source (migration, etc.).
    Imported,
}

impl AssetSource {
    /// String representation for the JSON index.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Upload => "upload",
            Self::EditorPaste => "editor-paste",
            Self::ChatAttach => "chat-attach",
            Self::Generated => "generated",
            Self::WebSearch => "web-search",
            Self::Imported => "imported",
        }
    }
}

impl std::fmt::Display for AssetSource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::str::FromStr for AssetSource {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "upload" => Ok(Self::Upload),
            "editor-paste" => Ok(Self::EditorPaste),
            "chat-attach" => Ok(Self::ChatAttach),
            "generated" => Ok(Self::Generated),
            "web-search" => Ok(Self::WebSearch),
            "imported" => Ok(Self::Imported),
            other => Err(format!("unknown asset source: {other}")),
        }
    }
}

/// Asset metadata entry — one row per stored file.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Asset {
    /// UUID identifier (same as the UUID in `storage_name`).
    pub id: String,
    /// Original uploaded filename.
    pub filename: String,
    /// User-editable title or description.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// MIME type guessed from the extension.
    pub mime_type: String,
    /// File size in bytes.
    pub size_bytes: u64,
    /// Where the asset came from.
    pub source: String,
    /// Contextual reference (session_id, URL, agent_id, etc.).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_ref: Option<String>,
    /// User-assigned tags.
    #[serde(default)]
    pub tags: Vec<String>,
    /// Image width in pixels (if applicable).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub width: Option<u32>,
    /// Image height in pixels (if applicable).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub height: Option<u32>,
    /// Audio/video duration in seconds (if applicable).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_secs: Option<f64>,
    /// SHA-256 content hash (for dedup).
    pub sha256: String,
    /// Unix timestamp (seconds) of creation.
    pub created_at: i64,
    /// Filename on disk: `{uuid}.{ext}`.
    pub storage_name: String,
}

/// Filter parameters for [`AssetStore::list`].
#[derive(Debug, Clone, Default)]
pub struct AssetFilter {
    /// Filter by type category: `image`, `audio`, `video`, `document`.
    pub type_filter: Option<String>,
    /// Filter by source.
    pub source: Option<String>,
    /// Substring search on filename + title + tags.
    pub search: Option<String>,
    /// Page number (1-based).
    pub page: usize,
    /// Items per page.
    pub limit: usize,
}

/// Errors from the asset store.
#[derive(Debug, thiserror::Error)]
pub enum AssetStoreError {
    /// I/O error reading/writing files or the index.
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    /// JSON serialization error (corrupt index).
    #[error("json error: {0}")]
    Json(#[from] serde_json::Error),
    /// Asset not found by name.
    #[error("asset not found: {0}")]
    NotFound(String),
}

/// Central binary asset store with a JSON metadata index.
///
/// Files live flat under `root` as `{uuid}.{ext}`. The `index.json` manifest
/// tracks metadata for browsing/filtering. Index mutations persist atomically
/// (temp file + rename).
pub struct AssetStore {
    /// Directory holding all asset files + `index.json`.
    root: PathBuf,
    /// URL prefix for served assets (default `/api/assets/`).
    serve_prefix: String,
    /// In-memory index, persisted to `index.json` on every mutation.
    index: RwLock<Vec<Asset>>,
}

const INDEX_FILENAME: &str = "index.json";
const DEFAULT_SERVE_PREFIX: &str = "/api/assets/";

impl AssetStore {
    /// Create a new store at `root`, loading `index.json` if it exists.
    pub fn new(root: PathBuf) -> Result<Self, AssetStoreError> {
        Self::with_serve_prefix(root, DEFAULT_SERVE_PREFIX.into())
    }

    /// Create with a custom serve prefix (used by tests / non-default deployments).
    pub fn with_serve_prefix(root: PathBuf, serve_prefix: String) -> Result<Self, AssetStoreError> {
        std::fs::create_dir_all(&root)?;
        let index = Self::load_index(&root)?;
        Ok(Self {
            root,
            serve_prefix,
            index: RwLock::new(index),
        })
    }

    /// The root directory.
    pub fn root(&self) -> &Path {
        &self.root
    }

    /// Serve prefix for building URLs.
    pub fn serve_prefix(&self) -> &str {
        &self.serve_prefix
    }

    // ── Core CRUD ──────────────────────────────────────────────────

    /// Store `bytes` as a new asset with full metadata.
    ///
    /// Computes SHA256 for dedup — if an identical asset exists, returns it
    /// instead of writing a duplicate.
    pub fn store(
        &self,
        bytes: Vec<u8>,
        filename: &str,
        source: AssetSource,
        source_ref: Option<String>,
    ) -> Result<Asset, AssetStoreError> {
        let sha256 = hex::encode(Sha256::digest(&bytes));

        // Dedup: return existing asset with the same hash.
        {
            let index = self.index.read();
            if let Some(existing) = index.iter().find(|a| a.sha256 == sha256) {
                return Ok(existing.clone());
            }
        }

        let id = uuid::Uuid::new_v4().to_string();
        let ext = filename
            .rsplit('.')
            .next()
            .filter(|e| !e.is_empty() && !e.contains('/'))
            .unwrap_or("bin")
            .to_ascii_lowercase();
        let storage_name = format!("{id}.{ext}");
        let mime_type = guess_mime(&storage_name);
        let size_bytes = bytes.len() as u64;
        let (width, height) = image_dimensions(&mime_type, &bytes);

        // Write the file.
        let file_path = self.root.join(&storage_name);
        std::fs::write(&file_path, &bytes)?;

        let asset = Asset {
            id: id.clone(),
            filename: filename.to_string(),
            title: None,
            mime_type,
            size_bytes,
            source: source.to_string(),
            source_ref,
            tags: Vec::new(),
            width,
            height,
            duration_secs: None,
            sha256,
            created_at: chrono::Utc::now().timestamp(),
            storage_name,
        };

        // Update + persist index.
        {
            let mut index = self.index.write();
            index.push(asset.clone());
        }
        self.persist()?;

        Ok(asset)
    }

    /// List assets matching a filter, with pagination.
    ///
    /// Returns `(matching_items, total_count)`.
    pub fn list(&self, filter: &AssetFilter) -> (Vec<Asset>, usize) {
        let index = self.index.read();
        let mut filtered: Vec<&Asset> = index.iter().collect();

        if let Some(ref ty) = filter.type_filter {
            filtered.retain(|a| asset_type(&a.mime_type) == ty.as_str());
        }
        if let Some(ref src) = filter.source {
            filtered.retain(|a| a.source == src.as_str());
        }
        if let Some(ref search) = filter.search {
            let lower = search.to_ascii_lowercase();
            filtered.retain(|a| {
                a.filename.to_ascii_lowercase().contains(&lower)
                    || a.title
                        .as_ref()
                        .is_some_and(|t| t.to_ascii_lowercase().contains(&lower))
                    || a.tags
                        .iter()
                        .any(|t| t.to_ascii_lowercase().contains(&lower))
            });
        }

        // Sort newest first.
        filtered.sort_by_key(|a| std::cmp::Reverse(a.created_at));

        let total = filtered.len();
        let page = filter.page.max(1);
        let limit = if filter.limit == 0 { 24 } else { filter.limit };
        let start = (page - 1) * limit;
        let items = filtered
            .into_iter()
            .skip(start)
            .take(limit)
            .cloned()
            .collect();

        (items, total)
    }

    /// Get metadata for a single asset by storage name.
    pub fn get_meta(&self, storage_name: &str) -> Option<Asset> {
        let index = self.index.read();
        index
            .iter()
            .find(|a| a.storage_name == storage_name)
            .cloned()
    }

    /// Update metadata (title, tags) for an asset.
    pub fn update_meta(
        &self,
        storage_name: &str,
        title: Option<String>,
        tags: Vec<String>,
    ) -> Result<Option<Asset>, AssetStoreError> {
        let mut index = self.index.write();
        let asset = index.iter_mut().find(|a| a.storage_name == storage_name);
        if let Some(a) = asset {
            if let Some(t) = title {
                a.title = if t.is_empty() { None } else { Some(t) };
            }
            a.tags = tags;
            let updated = a.clone();
            drop(index);
            self.persist()?;
            Ok(Some(updated))
        } else {
            Ok(None)
        }
    }

    /// Delete an asset: remove file + index entry.
    ///
    /// Returns `true` if the asset was found and deleted.
    pub fn delete(&self, storage_name: &str) -> Result<bool, AssetStoreError> {
        let mut index = self.index.write();
        let pos = index.iter().position(|a| a.storage_name == storage_name);
        if let Some(i) = pos {
            let asset = index.remove(i);
            drop(index);
            // Best-effort file deletion — index entry is already removed.
            let _ = std::fs::remove_file(self.root.join(&asset.storage_name));
            self.persist()?;
            Ok(true)
        } else {
            Ok(false)
        }
    }

    // ── Reconciliation ─────────────────────────────────────────────

    /// Scan the directory for files not in the index and register them.
    ///
    /// Called on startup and optionally on-demand. Returns the number of
    /// newly registered files.
    pub fn reconcile(&self) -> Result<usize, AssetStoreError> {
        let known: std::collections::HashSet<String> = {
            let index = self.index.read();
            index.iter().map(|a| a.storage_name.clone()).collect()
        };

        let mut added = 0;
        let entries = std::fs::read_dir(&self.root)?;
        for entry in entries.flatten() {
            let path = entry.path();
            if !path.is_file() {
                continue;
            }
            let name = match path.file_name().and_then(|n| n.to_str()) {
                Some(n) => n.to_string(),
                None => continue,
            };
            if name == INDEX_FILENAME || known.contains(&name) {
                continue;
            }

            // Register this file.
            let metadata = std::fs::metadata(&path)?;
            let mime_type = guess_mime(&name);
            let sha256 = {
                let bytes = std::fs::read(&path)?;
                hex::encode(Sha256::digest(&bytes))
            };
            let id = name.split('.').next().unwrap_or(&name).to_string();

            let asset = Asset {
                id,
                filename: name.clone(),
                title: None,
                mime_type,
                size_bytes: metadata.len(),
                source: AssetSource::Imported.to_string(),
                source_ref: None,
                tags: Vec::new(),
                width: None,
                height: None,
                duration_secs: None,
                sha256,
                created_at: metadata
                    .created()
                    .ok()
                    .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
                    .map(|d| d.as_secs() as i64)
                    .unwrap_or_else(|| chrono::Utc::now().timestamp()),
                storage_name: name,
            };

            let mut index = self.index.write();
            index.push(asset);
            added += 1;
        }

        if added > 0 {
            self.persist()?;
        }

        Ok(added)
    }

    // ── Internals ──────────────────────────────────────────────────

    fn load_index(root: &Path) -> Result<Vec<Asset>, AssetStoreError> {
        let path = root.join(INDEX_FILENAME);
        match std::fs::read_to_string(&path) {
            Ok(text) => Ok(serde_json::from_str(&text).unwrap_or_default()),
            Err(_) => Ok(Vec::new()),
        }
    }

    fn persist(&self) -> Result<(), AssetStoreError> {
        let index = self.index.read();
        let json = serde_json::to_string_pretty(&*index)?;
        let target = self.root.join(INDEX_FILENAME);
        let tmp = self.root.join(format!("{INDEX_FILENAME}.tmp"));
        std::fs::write(&tmp, json)?;
        std::fs::rename(&tmp, &target)?;
        Ok(())
    }
}

impl ImageSink for AssetStore {
    fn save(&self, bytes: Vec<u8>, ext: &str) -> Result<String, ImageGenError> {
        let filename = format!("generated.{ext}");
        self.store(bytes, &filename, AssetSource::Generated, None)
            .map(|asset| format!("{}{}", self.serve_prefix, asset.storage_name))
            .map_err(|e| ImageGenError::Store(e.to_string()))
    }
}

// ── Helpers ──────────────────────────────────────────────────────────

/// Best-effort MIME type from filename extension.
fn guess_mime(name: &str) -> String {
    let ext = name.rsplit('.').next().map(str::to_ascii_lowercase);
    match ext.as_deref() {
        Some("png") => "image/png",
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("gif") => "image/gif",
        Some("webp") => "image/webp",
        Some("svg") => "image/svg+xml",
        Some("avif") => "image/avif",
        Some("bmp") => "image/bmp",
        Some("ico") => "image/x-icon",
        Some("mp3") => "audio/mpeg",
        Some("wav") => "audio/wav",
        Some("ogg") => "audio/ogg",
        Some("flac") => "audio/flac",
        Some("m4a") => "audio/mp4",
        Some("aac") => "audio/aac",
        Some("mp4") => "video/mp4",
        Some("webm") => "video/webm",
        Some("mov") => "video/quicktime",
        Some("avi") => "video/x-msvideo",
        Some("mkv") => "video/x-matroska",
        Some("pdf") => "application/pdf",
        Some("json") => "application/json",
        Some("zip") => "application/zip",
        Some("tar") | Some("gz") => "application/gzip",
        _ => "application/octet-stream",
    }
    .into()
}

/// Broad type category from MIME type.
pub fn asset_type(mime: &str) -> &'static str {
    if mime.starts_with("image/") {
        "image"
    } else if mime.starts_with("audio/") {
        "audio"
    } else if mime.starts_with("video/") {
        "video"
    } else {
        "document"
    }
}

/// Extract image dimensions from PNG/WEBP header bytes (best-effort).
fn image_dimensions(mime: &str, bytes: &[u8]) -> (Option<u32>, Option<u32>) {
    if mime == "image/png" && bytes.len() >= 24 {
        // PNG: width at [16..20], height at [20..24] (big-endian).
        let w = u32::from_be_bytes([bytes[16], bytes[17], bytes[18], bytes[19]]);
        let h = u32::from_be_bytes([bytes[20], bytes[21], bytes[22], bytes[23]]);
        return (Some(w), Some(h));
    }
    if mime == "image/gif" && bytes.len() >= 10 {
        // GIF: width at [6..8], height at [8..10] (little-endian).
        let w = u16::from_le_bytes([bytes[6], bytes[7]]) as u32;
        let h = u16::from_le_bytes([bytes[8], bytes[9]]) as u32;
        return (Some(w), Some(h));
    }
    if mime == "image/webp" {
        return webp_dimensions(bytes);
    }
    (None, None)
}

/// Parse WebP VP8/VP8L/VP8X dimensions.
fn webp_dimensions(bytes: &[u8]) -> (Option<u32>, Option<u32>) {
    // RIFF header: "RIFF" [4 size] "WEBP" then chunk. We need at least 30 bytes.
    if bytes.len() < 30 {
        return (None, None);
    }
    let chunk = &bytes[12..16];
    match chunk {
        b"VP8 " => {
            // VP8 (lossy): width/height at offset 26-29 (14-bit LE each).
            let w = (u16::from_le_bytes([bytes[26], bytes[27]]) & 0x3FFF) as u32;
            let h = (u16::from_le_bytes([bytes[28], bytes[29]]) & 0x3FFF) as u32;
            (Some(w), Some(h))
        }
        b"VP8L" => {
            // VP8L (lossless): dimensions encoded in the bitstream at offset 21.
            let b = &bytes[21..25];
            let w = 1 + (((b[1] & 0x3F) as u32) << 8 | b[0] as u32);
            let h = 1 + (((b[3] & 0x0F) as u32) << 10 | (b[2] as u32) << 2 | b[1] as u32 >> 6);
            (Some(w), Some(h))
        }
        b"VP8X" => {
            // VP8X (extended): width-1 at [24..27], height-1 at [27..30] (24-bit LE).
            let w = 1 + (bytes[24] as u32 | (bytes[25] as u32) << 8 | (bytes[26] as u32) << 16);
            let h = 1 + (bytes[27] as u32 | (bytes[28] as u32) << 8 | (bytes[29] as u32) << 16);
            (Some(w), Some(h))
        }
        _ => (None, None),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp_store() -> (AssetStore, tempfile::TempDir) {
        let dir = tempfile::tempdir().unwrap();
        let store = AssetStore::new(dir.path().to_path_buf()).unwrap();
        (store, dir)
    }

    #[test]
    fn store_writes_file_and_indexes() {
        let (store, dir) = tmp_store();
        let bytes = b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x04\x00\x00\x00\x03\x00".to_vec();
        let asset = store
            .store(bytes.clone(), "test.png", AssetSource::Upload, None)
            .unwrap();

        assert_eq!(asset.filename, "test.png");
        assert_eq!(asset.mime_type, "image/png");
        assert!(asset.storage_name.ends_with(".png"));
        assert_eq!(asset.source, "upload");
        assert_eq!(asset.width, Some(1024));
        assert_eq!(asset.height, Some(768));

        // File on disk.
        let file_path = dir.path().join(&asset.storage_name);
        assert!(file_path.exists());
        let written = std::fs::read(&file_path).unwrap();
        assert_eq!(written, bytes);

        // In the index.
        let (items, total) = store.list(&AssetFilter::default());
        assert_eq!(total, 1);
        assert_eq!(items[0].id, asset.id);
    }

    #[test]
    fn dedup_returns_existing() {
        let (store, _dir) = tmp_store();
        let bytes = vec![1, 2, 3, 4, 5];
        let a1 = store
            .store(bytes.clone(), "a.png", AssetSource::Upload, None)
            .unwrap();
        let a2 = store
            .store(bytes, "b.png", AssetSource::Upload, None)
            .unwrap();

        assert_eq!(a1.id, a2.id);
        assert_eq!(a1.storage_name, a2.storage_name);
    }

    #[test]
    fn list_filters_by_type_and_source() {
        let (store, _dir) = tmp_store();
        store
            .store(vec![1], "img.png", AssetSource::Upload, None)
            .unwrap();
        store
            .store(vec![2], "song.mp3", AssetSource::Generated, None)
            .unwrap();
        store
            .store(vec![3], "pic.jpg", AssetSource::EditorPaste, None)
            .unwrap();

        let (_, img_total) = store.list(&AssetFilter {
            type_filter: Some("image".into()),
            ..Default::default()
        });
        assert_eq!(img_total, 2);

        let (generated, gen_total) = store.list(&AssetFilter {
            source: Some("generated".into()),
            ..Default::default()
        });
        assert_eq!(gen_total, 1);
        assert_eq!(generated[0].filename, "song.mp3");
    }

    #[test]
    fn delete_removes_file_and_index() {
        let (store, dir) = tmp_store();
        let asset = store
            .store(vec![9], "del.png", AssetSource::Upload, None)
            .unwrap();
        let file_path = dir.path().join(&asset.storage_name);
        assert!(file_path.exists());

        let deleted = store.delete(&asset.storage_name).unwrap();
        assert!(deleted);
        assert!(!file_path.exists());

        let (_, total) = store.list(&AssetFilter::default());
        assert_eq!(total, 0);
    }

    #[test]
    fn persist_and_reload() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().to_path_buf();

        {
            let store = AssetStore::new(root.clone()).unwrap();
            store
                .store(vec![42], "persist.png", AssetSource::Upload, None)
                .unwrap();
        }

        // Re-open: index should load from disk.
        let store = AssetStore::new(root).unwrap();
        let (_, total) = store.list(&AssetFilter::default());
        assert_eq!(total, 1);
    }

    #[test]
    fn image_sink_returns_prefixed_url() {
        let (store, _dir) = tmp_store();
        let url = store.save(vec![1, 2, 3], "png").unwrap();
        assert!(url.starts_with("/api/assets/"));
        assert!(url.ends_with(".png"));

        // The image should be registered as generated.
        let name = url.strip_prefix("/api/assets/").unwrap();
        let meta = store.get_meta(name).unwrap();
        assert_eq!(meta.source, "generated");
    }

    #[test]
    fn reconcile_finds_unindexed_files() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().to_path_buf();

        // Write a file directly to disk (bypassing the store).
        std::fs::write(root.join("orphan.png"), vec![1, 2, 3]).unwrap();

        let store = AssetStore::new(root).unwrap();
        assert_eq!(store.index.read().len(), 0);

        let added = store.reconcile().unwrap();
        assert_eq!(added, 1);

        let (_, total) = store.list(&AssetFilter::default());
        assert_eq!(total, 1);
    }

    #[test]
    fn update_meta_changes_title_and_tags() {
        let (store, _dir) = tmp_store();
        let asset = store
            .store(vec![1], "edit.png", AssetSource::Upload, None)
            .unwrap();

        let updated = store
            .update_meta(
                &asset.storage_name,
                Some("My Screenshot".into()),
                vec!["work".into(), "important".into()],
            )
            .unwrap()
            .unwrap();

        assert_eq!(updated.title.as_deref(), Some("My Screenshot"));
        assert_eq!(updated.tags, vec!["work", "important"]);
    }

    #[test]
    fn search_matches_filename_and_title() {
        let (store, _dir) = tmp_store();
        store
            .store(vec![1], "vacation.png", AssetSource::Upload, None)
            .unwrap();
        store
            .store(vec![2], "work.png", AssetSource::Upload, None)
            .unwrap();

        let (_, total) = store.list(&AssetFilter {
            search: Some("vac".into()),
            ..Default::default()
        });
        assert_eq!(total, 1);
    }
}
