// One source of truth for the agent's whimsical "busy" verbs, shared by the streaming pill (AgentChat) and the per-message thinking bubble (MessageBubble). `live` shows while the agent works; `past` shows once the step is done ("Marinated for 3s"). Keep them fun but never self-deprecating (no "hallucinating") so they read as personality, not a malfunction.
export interface ThinkingLabel {
  live: string;
  past: string;
}

// Index 0 is the safe default the pill falls back to with no seed, so keep it the plain one. Everything after is fair game for chaos.
export const THINKING_LABELS: ReadonlyArray<ThinkingLabel> = [
  { live: 'Thinking',       past: 'Thought' },
  { live: 'Tokenmaxing',    past: 'Tokenmaxed' },
  { live: 'Pondering',      past: 'Pondered' },
  { live: 'Cooking',        past: 'Cooked' },
  { live: 'Grokking',       past: 'Grokked' },
  { live: 'Marinating',     past: 'Marinated' },
  { live: 'Galaxy-braining', past: 'Galaxy-brained' },
  { live: 'Reasoning',      past: 'Reasoned' },
  { live: 'Noodling',       past: 'Noodled' },
  { live: 'Percolating',    past: 'Percolated' },
  { live: 'Reflecting',     past: 'Reflected' },
  { live: 'Untangling',     past: 'Untangled' },
  { live: 'Crunching',      past: 'Crunched' },
  { live: 'Stewing',        past: 'Stewed' },
  { live: 'Locking-in',     past: 'Locked-in' },
  { live: 'Manifesting',    past: 'Manifested' },
  { live: 'Big-braining',   past: 'Big-brained' },
  { live: 'Vibing',         past: 'Vibed' },
  { live: 'Scheming',       past: 'Schemed' },
  { live: 'Riffing',        past: 'Riffed' },
  { live: 'Calculating',    past: 'Calculated' },
  { live: 'Tinkering',      past: 'Tinkered' },
  { live: 'Finessing',      past: 'Finessed' },
  { live: 'Chefing',        past: 'Chefed' },
  { live: 'Min-maxing',     past: 'Min-maxed' },
  { live: 'Geeking',        past: 'Geeked' },
  { live: 'Ruminating',     past: 'Ruminated' },
  { live: 'Simmering',      past: 'Simmered' },
  { live: 'Brewing',        past: 'Brewed' },
  { live: 'Wrangling',      past: 'Wrangled' },
  { live: 'Spelunking',     past: 'Spelunked' },
  { live: 'Conjuring',      past: 'Conjured' },
  { live: 'Synthesizing',   past: 'Synthesized' },
  { live: 'Overclocking',   past: 'Overclocked' },
  { live: 'Caffeinating',   past: 'Caffeinated' },
  { live: 'Sleuthing',      past: 'Sleuthed' },
  { live: 'Larping',        past: 'Larped' },
  { live: 'Speedrunning',   past: 'Speedran' },
  { live: 'Theorycrafting', past: 'Theorycrafted' },
  { live: 'Sussing',        past: 'Sussed' },
  { live: 'Hyperfixating',  past: 'Hyperfixated' },
  { live: 'Nerd-sniping',   past: 'Nerd-sniped' },
  { live: 'Promptmaxing',   past: 'Promptmaxed' },
  { live: 'Pontificating',  past: 'Pontificated' },
  { live: 'Vibe-checking',  past: 'Vibe-checked' },
  { live: 'Mogging',        past: 'Mogged' },
  { live: 'Goblin-moding',  past: 'Goblin-moded' },
  { live: 'Side-questing',  past: 'Side-quested' },
  { live: 'Tryharding',     past: 'Tryharded' },
  { live: 'Grinding',       past: 'Grinded' },
];
