// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/cadence/service/history/taskdlq (interfaces: TaskReinjector,Processor)
//
// Generated by this command:
//
//	mockgen -package taskdlq -destination interface_mock.go github.com/uber/cadence/service/history/taskdlq TaskReinjector,Processor
//

// Package taskdlq is a generated GoMock package.
package taskdlq

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	persistence "github.com/uber/cadence/common/persistence"
)

// MockTaskReinjector is a mock of TaskReinjector interface.
type MockTaskReinjector struct {
	ctrl     *gomock.Controller
	recorder *MockTaskReinjectorMockRecorder
	isgomock struct{}
}

// MockTaskReinjectorMockRecorder is the mock recorder for MockTaskReinjector.
type MockTaskReinjectorMockRecorder struct {
	mock *MockTaskReinjector
}

// NewMockTaskReinjector creates a new mock instance.
func NewMockTaskReinjector(ctrl *gomock.Controller) *MockTaskReinjector {
	mock := &MockTaskReinjector{ctrl: ctrl}
	mock.recorder = &MockTaskReinjectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskReinjector) EXPECT() *MockTaskReinjectorMockRecorder {
	return m.recorder
}

// ReinjectHistoryTasks mocks base method.
func (m *MockTaskReinjector) ReinjectHistoryTasks(ctx context.Context, tasks []persistence.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReinjectHistoryTasks", ctx, tasks)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReinjectHistoryTasks indicates an expected call of ReinjectHistoryTasks.
func (mr *MockTaskReinjectorMockRecorder) ReinjectHistoryTasks(ctx, tasks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReinjectHistoryTasks", reflect.TypeOf((*MockTaskReinjector)(nil).ReinjectHistoryTasks), ctx, tasks)
}

// MockProcessor is a mock of Processor interface.
type MockProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockProcessorMockRecorder
	isgomock struct{}
}

// MockProcessorMockRecorder is the mock recorder for MockProcessor.
type MockProcessorMockRecorder struct {
	mock *MockProcessor
}

// NewMockProcessor creates a new mock instance.
func NewMockProcessor(ctrl *gomock.Controller) *MockProcessor {
	mock := &MockProcessor{ctrl: ctrl}
	mock.recorder = &MockProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessor) EXPECT() *MockProcessorMockRecorder {
	return m.recorder
}

// FailoverPartitions mocks base method.
func (m *MockProcessor) FailoverPartitions(partitions []Partition) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FailoverPartitions", partitions)
}

// FailoverPartitions indicates an expected call of FailoverPartitions.
func (mr *MockProcessorMockRecorder) FailoverPartitions(partitions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailoverPartitions", reflect.TypeOf((*MockProcessor)(nil).FailoverPartitions), partitions)
}

// ProcessPartition mocks base method.
func (m *MockProcessor) ProcessPartition(ctx context.Context, domainID, clusterAttributeScope, clusterAttributeName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPartition", ctx, domainID, clusterAttributeScope, clusterAttributeName)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessPartition indicates an expected call of ProcessPartition.
func (mr *MockProcessorMockRecorder) ProcessPartition(ctx, domainID, clusterAttributeScope, clusterAttributeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPartition", reflect.TypeOf((*MockProcessor)(nil).ProcessPartition), ctx, domainID, clusterAttributeScope, clusterAttributeName)
}

// ProcessShard mocks base method.
func (m *MockProcessor) ProcessShard(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessShard", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessShard indicates an expected call of ProcessShard.
func (mr *MockProcessorMockRecorder) ProcessShard(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessShard", reflect.TypeOf((*MockProcessor)(nil).ProcessShard), ctx)
}

// Start mocks base method.
func (m *MockProcessor) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockProcessorMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockProcessor)(nil).Start))
}

// Stop mocks base method.
func (m *MockProcessor) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockProcessorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockProcessor)(nil).Stop))
}
