model_list:
  - model_name: gpt-oss-120b
    litellm_params:
      model: groq/openai/gpt-oss-120b
      api_key: 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
      api_base: https://api.groq.com/openai/v1
  - model_name: llama-70b
    litellm_params:
      model: groq/llama-3.3-70b-versatile
      api_key: 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
      api_base: https://api.groq.com/openai/v1
  - model_name: gemma-4-31b
    litellm_params:
      model: cerebras/gemma-4-31b
      api_key: csk-vjp8rfm6mkwvnd8dy6pfv3xtmw5kpnv2h3yj9j6prtxd2jc2
      api_base: https://api.cerebras.ai/v1
  - model_name: zai-glm-47
    litellm_params:
      model: cerebras/zai-glm-4.7
      api_key: csk-vjp8rfm6mkwvnd8dy6pfv3xtmw5kpnv2h3yj9j6prtxd2jc2
      api_base: https://api.cerebras.ai/v1
  - model_name: minimax-m27
    litellm_params:
      model: openai/minimaxai/minimax-m2.7
      api_key: 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
      api_base: https://integrate.api.nvidia.com/v1
  - model_name: minimax-m3
    litellm_params:
      model: openai/minimaxai/minimax-m3
      api_key: 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
      api_base: https://integrate.api.nvidia.com/v1
  - model_name: gemma-4-vps
    litellm_params:
      model: openai/gemma-4-vps
      api_key: not-needed
      api_base: http://127.0.0.1:8002/v1

router_settings:
  num_retries: 3
  timeout: 60

general_settings:
  master_key: sk-litellm-maxbry-2026
