"""``openagentd transfer export`` — pack config for migration to another server.

Creates a timestamped ``.tar.gz`` archive containing the portable config
layer:

    agents/        — per-agent .md files
    skills/        — user-defined skill directories
    commands/      — slash-command .md files
    plugins/       — user plugin .py files (no __pycache__)
    mcp.json       — MCP server config
    settings.yaml  — shared runtime settings (title gen, summarisation, LSP)
    server.yaml    — CLI server bind settings and access key
    multimodal.yaml — image/video generation model config
    .env           — credentials (secrets redacted by default)

Intentionally excluded:
    openagentd.db      — SQLite database (machine-local, large, session-specific)
    workspace/         — per-session agent workspaces
    .skill-lock.json   — generated cache (regenerated on demand)
    plugins/__pycache__ — Python bytecode (regenerated by Python)
    OAuth token caches — machine-bound desktop auth state
"""

from __future__ import annotations

import argparse
import io
import re
import tarfile
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

import yaml

from app.cli.paths import _config_dir
from app.cli.ui import _bold, _cyan, _dim, _green, _yellow

# ---------------------------------------------------------------------------
# Secret-line redaction
# ---------------------------------------------------------------------------

#: Env-var names whose values are blanked unless ``--include-secrets`` is given.
_SECRET_VAR_PATTERN = re.compile(
    r"""
    ^(
        [A-Z0-9_]*_API_KEY
        | [A-Z0-9_]*_SECRET(?:_KEY)?
        | [A-Z0-9_]*_TOKEN
        | [A-Z0-9_]*_PASSWORD
        | ACCESS_KEY
        | AWS_BEARER_TOKEN_BEDROCK
    )=(.+)$
    """,
    re.VERBOSE,
)


def _redact_env(content: str) -> str:
    """Return env-file text with known-secret values blanked.

    Non-secret lines (comments, blank lines, APP_ENV=…, etc.) are kept verbatim.
    Secret lines are reduced to ``KEY=`` so the target machine can fill them in.
    """
    out: list[str] = []
    for line in content.splitlines(keepends=True):
        stripped = line.rstrip("\r\n")
        m = _SECRET_VAR_PATTERN.match(stripped)
        if m:
            # Blank the value, preserve any trailing newline
            eol = line[len(stripped) :]
            out.append(f"{m.group(1)}={eol}")
        else:
            out.append(line)
    return "".join(out)


def _redact_server_settings(content: str) -> str:
    """Return server YAML without its persisted access key."""
    raw = yaml.safe_load(content) or {}
    if not isinstance(raw, dict):
        raise ValueError("server.yaml must contain a YAML mapping.")
    raw.pop("access_key", None)
    return yaml.safe_dump(raw, sort_keys=False)


# ---------------------------------------------------------------------------
# What to include
# ---------------------------------------------------------------------------

#: Top-level directories inside CONFIG_DIR to pack wholesale
#: (minus __pycache__ entries — filtered at add time).
_TREE_DIRS: tuple[str, ...] = ("agents", "skills", "commands", "plugins")

#: Top-level files to include if present.
_ROOT_FILES: tuple[str, ...] = (
    "mcp.json",
    "settings.yaml",
    "server.yaml",
    "multimodal.yaml",
    ".env",
)

#: Top-level files to always exclude.
_EXCLUDED_FILES: frozenset[str] = frozenset({".skill-lock.json", ".DS_Store"})

#: Archive root prefix — all entries live under this directory inside the tarball.
ARCHIVE_ROOT = "openagentd-export"


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class ExportResult:
    """Outcome of an export operation."""

    archive_path: Path
    files_packed: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Core export logic
# ---------------------------------------------------------------------------


def export_config(
    config_dir: Path,
    *,
    output_dir: Path | None = None,
    output_path: Path | None = None,
    include_secrets: bool = False,
) -> ExportResult:
    """Pack ``config_dir`` into a portable ``.tar.gz`` archive.

    Parameters
    ----------
    config_dir
        Source ``{OPENAGENTD_CONFIG_DIR}`` — agents, skills, etc. live here.
    output_dir
        Directory to write the timestamped archive into.
        Mutually exclusive with ``output_path``.
    output_path
        Exact path for the archive file.
        Mutually exclusive with ``output_dir``.
    include_secrets
        When ``False`` (the default), known-secret env-var values in ``.env``
        and the access key in ``server.yaml`` are removed before packing.
        Pass ``True`` only
        over a trusted, encrypted channel — the secrets will be plaintext in
        the archive.

    Returns
    -------
    ExportResult
        Archive path and list of relative paths that were packed.
    """
    if output_path is None:
        if output_dir is None:
            output_dir = Path.cwd()
        stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        output_path = output_dir / f"openagentd-export-{stamp}.tar.gz"

    files_packed: list[str] = []

    with tarfile.open(output_path, "w:gz") as tf:
        # ── Tree directories ──────────────────────────────────────────────
        for dir_name in _TREE_DIRS:
            src_dir = config_dir / dir_name
            if not src_dir.is_dir():
                continue
            for src in sorted(src_dir.rglob("*")):
                if not src.is_file():
                    continue
                # Exclude __pycache__ and any .pyc files
                if "__pycache__" in src.parts:
                    continue
                if src.name.endswith(".pyc"):
                    continue
                rel = src.relative_to(config_dir)
                arc_name = f"{ARCHIVE_ROOT}/{rel.as_posix()}"
                tf.add(src, arcname=arc_name)
                files_packed.append(rel.as_posix())

        # ── Top-level config files ────────────────────────────────────────
        for filename in _ROOT_FILES:
            if filename in _EXCLUDED_FILES:
                continue
            src = config_dir / filename
            if not src.is_file():
                continue
            rel = filename
            arc_name = f"{ARCHIVE_ROOT}/{rel}"

            if filename in {".env", "server.yaml"} and not include_secrets:
                raw = src.read_text(encoding="utf-8")
                redacted = (
                    _redact_env(raw)
                    if filename == ".env"
                    else _redact_server_settings(raw)
                ).encode("utf-8")
                info = tarfile.TarInfo(name=arc_name)
                info.size = len(redacted)
                tf.addfile(info, io.BytesIO(redacted))
            else:
                tf.add(src, arcname=arc_name)

            files_packed.append(rel)

    return ExportResult(archive_path=output_path, files_packed=sorted(files_packed))


# ---------------------------------------------------------------------------
# CLI handler
# ---------------------------------------------------------------------------


def cmd_export(args: argparse.Namespace) -> None:
    config_dir = (
        Path(args.config_dir).expanduser()
        if getattr(args, "config_dir", None)
        else _config_dir()
    )

    output_path: Path | None = None
    output_dir: Path | None = None
    if getattr(args, "output", None):
        output_path = Path(args.output).expanduser().resolve()
    else:
        output_dir = Path.cwd()

    include_secrets: bool = getattr(args, "include_secrets", False)

    if include_secrets:
        print()
        print(
            f"  {_yellow('⚠')}  {_bold('--include-secrets')} is set — API and server access keys will be "
            "stored in plaintext inside the archive."
        )
        print(
            f"     {_dim('Only use this over a trusted, encrypted channel (e.g. local disk → SCP → remote).')}"
        )
        print()

    print(f"  {_dim('…')}  Exporting config from {config_dir}")

    result = export_config(
        config_dir,
        output_dir=output_dir,
        output_path=output_path,
        include_secrets=include_secrets,
    )

    print(f"  {_green('✓')}  Archive: {_bold(str(result.archive_path))}")
    print(f"  {_dim('Packed')} {len(result.files_packed)} file(s):")
    for f in result.files_packed:
        is_secret_file = f in {".env", "server.yaml"}
        marker = _yellow("  •") if is_secret_file else _cyan("  •")
        suffix = (
            _dim("  (secrets redacted)")
            if is_secret_file and not include_secrets
            else ""
        )
        print(f"    {marker} {f}{suffix}")
    print()
    print(f"  {_bold('To import on the target server:')}")
    print(f"    openagentd transfer import {result.archive_path.name}")
    print()
