name: agentbench-fc

services:

  controller:
    image: docker.m.daocloud.io/jingbh/agentrl-controller:latest
    container_name: agentrl-controller
    ports:
      - "5020:5020"
    command:
      - controller
      - --long-timeout

  alfworld-std:
    build:
      context: ..
      dockerfile: src/server/tasks/alfworld/Dockerfile
    command: --controller http://controller:5020/api alfworld-std
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - controller
    volumes:
      - ../configs:/app/configs
      - ../src/server/tasks/alfworld:/app/src/server/tasks/alfworld
      - ../src/server/harness:/app/src/server/harness

  alfworld-env_train:
    build:
      context: ..
      dockerfile: src/server/tasks/alfworld/Dockerfile
    command: --controller http://controller:5020/api alfworld-env_train
    volumes:
      - ../configs:/app/configs
      - ../src/server/tasks/alfworld:/app/src/server/tasks/alfworld
      - ../src/server/harness:/app/src/server/harness
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - controller

  dbbench-std:
    build:
      context: ..
      dockerfile: src/server/tasks/dbbench/Dockerfile
    command: --controller http://controller:5020/api dbbench-std
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../configs:/app/configs
      - ../src/server/tasks/dbbench:/app/src/server/tasks/dbbench
      - ../src/server/tasks/native_environment.py:/app/src/server/tasks/native_environment.py
      - ../src/server/harness:/app/src/server/harness
    environment:
      - DBBENCH_STD_PARAMETERS_ENV_OPTIONS_NETWORK_NAME=agentbench-fc_default
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - controller

  dbbench-env_train:
    build:
      context: ..
      dockerfile: src/server/tasks/dbbench/Dockerfile
    command: --controller http://controller:5020/api dbbench-env_train
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../configs:/app/configs
      - ../src/server/tasks/dbbench:/app/src/server/tasks/dbbench
      - ../src/server/tasks/native_environment.py:/app/src/server/tasks/native_environment.py
      - ../src/server/harness:/app/src/server/harness
    environment:
      - DBBENCH_ENV_TRAIN_PARAMETERS_ENV_OPTIONS_NETWORK_NAME=agentbench-fc_default
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - controller

  knowledgegraph-std:
    build:
      context: ..
      dockerfile: src/server/tasks/knowledgegraph/Dockerfile
    command: --controller http://controller:5020/api kg-std
    volumes:
      - ../configs:/app/configs
      - ../src/server/tasks/knowledgegraph:/app/src/server/tasks/knowledgegraph
    environment:
      - KG_STD_PARAMETERS_ENV_OPTIONS_URLS_KG=http://freebase:3001/sparql
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - controller
      - freebase

  knowledgegraph-env_train:
    build:
      context: ..
      dockerfile: src/server/tasks/knowledgegraph/Dockerfile
    command: --controller http://controller:5020/api kg-env_train
    volumes:
      - ../configs:/app/configs
      - ../src/server/tasks/knowledgegraph:/app/src/server/tasks/knowledgegraph
    environment:
      - KG_STD_PARAMETERS_ENV_OPTIONS_URLS_KG=http://freebase:3001/sparql
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - controller
      - freebase

  os-std:
    build:
      context: ..
      dockerfile: src/server/tasks/os_interaction/Dockerfile
    command: --controller http://controller:5020/api os-std
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../configs:/app/configs
      - ../src/server/tasks/os_interaction:/app/src/server/tasks/os_interaction
      - ../src/server/harness:/app/src/server/harness
    environment:
      - OS_STD_PARAMETERS_ENV_OPTIONS_NETWORK_NAME=agentbench-fc_default
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - controller

  os-env_train:
    build:
      context: ..
      dockerfile: src/server/tasks/os_interaction/Dockerfile
    command: --controller http://controller:5020/api os-env_train
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../configs:/app/configs
      - ../src/server/tasks/os_interaction:/app/src/server/tasks/os_interaction
      - ../src/server/harness:/app/src/server/harness
    environment:
      - OS_ENV_TRAIN_PARAMETERS_ENV_OPTIONS_NETWORK_NAME=agentbench-fc_default
      - OS_TASK_IDS=${OS_TASK_IDS:-}
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - controller

  webshop-std:
    build:
      context: ..
      dockerfile: src/server/tasks/webshop/Dockerfile
    command: --controller http://controller:5020/api webshop-std
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ../configs:/app/configs
      - ../src/server/tasks/webshop:/app/src/server/tasks/webshop
      - ../src/server/harness:/app/src/server/harness
    depends_on:
      - controller

  webshop-env_train:
    build:
      context: ..
      dockerfile: src/server/tasks/webshop/Dockerfile
    command: --controller http://controller:5020/api webshop-env_train
    volumes:
      - ../configs:/app/configs
      - ../src/server/tasks/webshop:/app/src/server/tasks/webshop
      - ../src/server/harness:/app/src/server/harness
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - controller

  freebase:
    build:
      context: ..
      dockerfile: extra/freebase.Dockerfile
    volumes:
      - ./virtuoso_db/virtuoso.db:/database/virtuoso.db
    init: true

  redis:
    image: docker.m.daocloud.io/redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0 --protected-mode no
