-- Admin plugin fields for the BetterAuth user table
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'user';
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS banned BOOLEAN DEFAULT FALSE;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS ban_reason TEXT;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS ban_expires TIMESTAMP;
