"""Shared ignore helpers for filesystem tools and the workspace file listing.

Two policies live here, used by ``grep``, ``glob`` and the API's workspace
listing so a file is never visible to one and invisible to another:

1. :data:`NOISE_DIR_NAMES` — directory trees that are machine-generated and
   never hand-authored. Skipped outright, before any ``.gitignore`` lookup.
2. :func:`is_gitignored` — a ``gitignore(5)`` matcher for everything else.

The matcher used to be a thin ``fnmatch`` wrapper, which was wrong in both
directions: ``fnmatch``'s ``*`` crosses ``/``, so ``docs/*.tmp`` also hid
``docs/guide/deep/notes.tmp`` (a file git shows), while directory patterns were
anchored to the root, so ``build/`` never matched ``web/build/`` (a directory
git ignores). Wildcard scope is now git's: ``*`` and ``?`` stop at ``/`` and
only ``**`` spans directories.

Known limitation: only the ``.gitignore`` at the search root is read — nested
``.gitignore`` files, ``.git/info/exclude`` and ``core.excludesFile`` are not.
Callers that need exact fidelity should ask git itself; see
``_git_listed_paths`` in ``app/api/routes/agent/files.py``.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

import pathspec

#: Directories whose contents are generated by a tool, not written by a human:
#: dependency trees and compiler/test caches. Skipped without consulting
#: ``.gitignore`` so a repo that forgot to ignore ``node_modules`` doesn't
#: swamp every search.
#:
#: Deliberately excludes ``dist/`` and ``build/``: those regularly hold real
#: content (a site the agent just built, a tracked ``build/Dockerfile``), and
#: pruning them unconditionally made those files unsearchable and impossible to
#: @-mention. Whether they are noise is left to ``.gitignore``.
NOISE_DIR_NAMES = frozenset(
    {
        ".git",
        "node_modules",
        ".venv",
        "venv",
        "__pycache__",
        ".mypy_cache",
        ".ruff_cache",
        ".pytest_cache",
        ".tox",
        ".nox",
        ".next",
        ".nuxt",
        ".svelte-kit",
        ".turbo",
        ".parcel-cache",
        ".gradle",
        ".terraform",
    }
)

_MAX_CACHED_PATTERNS = 1024


class GitignoreRules(list):
    """Ordered ``(pattern, is_negation)`` rules backed by a compiled PathSpec."""

    def __init__(
        self,
        rules: list[tuple[str, bool]] | tuple[tuple[str, bool], ...] = (),
        raw_lines: list[str] | None = None,
    ):
        super().__init__(rules)
        if raw_lines is not None:
            self.spec: pathspec.PathSpec = pathspec.PathSpec.from_lines(
                "gitwildmatch", raw_lines
            )
        else:
            lines = [
                ("!" if inc else "")
                + (f"\\{pat}" if pat.startswith(("#", "!")) else pat)
                for pat, inc in rules
            ]
            self.spec = pathspec.PathSpec.from_lines("gitwildmatch", lines)


def load_gitignore_rules(root: Path) -> GitignoreRules:
    """Parse ``root/.gitignore`` into ``(pattern, is_negation)`` pairs.

    Order is preserved: :func:`is_gitignored` applies last-match-wins, so a
    later ``!pattern`` can re-include what an earlier rule excluded.
    """
    gitignore = root / ".gitignore"
    if not gitignore.is_file():
        return GitignoreRules()
    try:
        lines = gitignore.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeDecodeError):
        return GitignoreRules()

    rules: list[tuple[str, bool]] = []
    raw_lines: list[str] = []
    for line in lines:
        pattern = line.strip()
        if not pattern or pattern.startswith("#"):
            continue
        include = pattern.startswith("!")
        if include:
            pattern = pattern[1:].strip()
        elif pattern.startswith(("\\!", "\\#")):
            # Escaped leading marker: the file is literally named "!foo"/"#foo".
            pattern = pattern[1:]
        if pattern:
            raw_lines.append(line)
            rules.append((pattern, include))
    return GitignoreRules(rules, raw_lines=raw_lines)


@lru_cache(maxsize=_MAX_CACHED_PATTERNS)
def _compile_pattern(pattern: str) -> pathspec.PathSpec:
    return pathspec.PathSpec.from_lines("gitwildmatch", [pattern])


def matches_gitignore_pattern(pattern: str, rel: str, *, is_dir: bool) -> bool:
    """True when ``rel`` is matched by a single ``.gitignore`` pattern.

    ``rel`` is POSIX-relative to the directory holding the ``.gitignore``.
    Ancestor directories are tested too, because ignoring a directory ignores
    everything beneath it — callers that pass a file path straight in (rather
    than pruning during a walk) still get the right answer.
    """
    if not rel:
        return False
    spec = _compile_pattern(pattern)
    target = f"{rel}/" if is_dir and not rel.endswith("/") else rel
    return spec.match_file(target)


def is_gitignored(
    rel: str, *, is_dir: bool, rules: GitignoreRules | list[tuple[str, bool]]
) -> bool:
    """Apply ``rules`` to ``rel``, last match wins (so ``!`` can re-include)."""
    if not rel or not rules:
        return False
    target = f"{rel}/" if is_dir and not rel.endswith("/") else rel
    if isinstance(rules, GitignoreRules):
        return rules.spec.match_file(target)
    if isinstance(rules, list):
        lines = [
            ("!" if inc else "") + (f"\\{pat}" if pat.startswith(("#", "!")) else pat)
            for pat, inc in rules
        ]
        return pathspec.PathSpec.from_lines("gitwildmatch", lines).match_file(target)
    return False
