// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/cadence/common/persistence (interfaces: HistoryTaskSerializer)
//
// Generated by this command:
//
//	mockgen -package persistence -destination history_task_dlq_manager_mock.go github.com/uber/cadence/common/persistence HistoryTaskSerializer
//

// Package persistence is a generated GoMock package.
package persistence

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHistoryTaskSerializer is a mock of HistoryTaskSerializer interface.
type MockHistoryTaskSerializer struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryTaskSerializerMockRecorder
	isgomock struct{}
}

// MockHistoryTaskSerializerMockRecorder is the mock recorder for MockHistoryTaskSerializer.
type MockHistoryTaskSerializerMockRecorder struct {
	mock *MockHistoryTaskSerializer
}

// NewMockHistoryTaskSerializer creates a new mock instance.
func NewMockHistoryTaskSerializer(ctrl *gomock.Controller) *MockHistoryTaskSerializer {
	mock := &MockHistoryTaskSerializer{ctrl: ctrl}
	mock.recorder = &MockHistoryTaskSerializerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryTaskSerializer) EXPECT() *MockHistoryTaskSerializerMockRecorder {
	return m.recorder
}

// DeserializeTask mocks base method.
func (m *MockHistoryTaskSerializer) DeserializeTask(arg0 HistoryTaskCategory, arg1 *DataBlob) (Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeserializeTask", arg0, arg1)
	ret0, _ := ret[0].(Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeserializeTask indicates an expected call of DeserializeTask.
func (mr *MockHistoryTaskSerializerMockRecorder) DeserializeTask(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeserializeTask", reflect.TypeOf((*MockHistoryTaskSerializer)(nil).DeserializeTask), arg0, arg1)
}

// SerializeTask mocks base method.
func (m *MockHistoryTaskSerializer) SerializeTask(arg0 HistoryTaskCategory, arg1 Task) (DataBlob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SerializeTask", arg0, arg1)
	ret0, _ := ret[0].(DataBlob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SerializeTask indicates an expected call of SerializeTask.
func (mr *MockHistoryTaskSerializerMockRecorder) SerializeTask(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SerializeTask", reflect.TypeOf((*MockHistoryTaskSerializer)(nil).SerializeTask), arg0, arg1)
}
