assignments:
- agent:
  - gemini-3.1-pro-preview
  task:
  - alfworld-std-baseline
concurrency:
  agent:
    gemini-3.1-pro-preview: 5
  task:
    alfworld-std-baseline: 32
import: definition.yaml
output: outputs/gemini-3.1-pro-preview/alfworld/{TIMESTAMP}-baseline
trials: 1
