assignments:
- agent:
  - gemini-3.1-pro-preview
  task:
  - dbbench-std
concurrency:
  agent:
    gemini-3.1-pro-preview: 5
  task:
    dbbench-std: 16
import: definition.yaml
output: outputs/gemini-3.1-pro-preview/dbbench/{TIMESTAMP}-run
trials: 1
