assignments:
- agent:
  - claude-opus-4-8
  task:
  - dbbench-std
concurrency:
  agent:
    claude-opus-4-8: 5
  task:
    dbbench-std: 16
import: definition.yaml
output: outputs/claude-opus-4-8/dbbench/{TIMESTAMP}-baseline
trials: 1
