assignments:
- agent:
  - gemini-3.1-pro-preview
  task:
  - webshop-sub50
concurrency:
  agent:
    gemini-3.1-pro-preview: 5
  task:
    webshop-sub50: 16
import: definition.yaml
output: outputs/gemini-3.1-pro-preview/webshop/{TIMESTAMP}-sub50-run
trials: 1
