import: definition.yaml

concurrency:
  task:
    # os-env_train: 16
    os-std: 16
  agent:
    qwen3-4b-instruct: 16

assignments:
  - agent:
      - qwen3-4b-instruct
    task:
      # - os-env_train
      - os-std

# output: "outputs/qwen3-4b-instruct/os/{TIMESTAMP}-baseline"
# output: "outputs/qwen3-4b-instruct/os/{TIMESTAMP}-with_harness"
# output: "outputs/qwen3-4b-instruct/os/{TIMESTAMP}-no_h2"
# output: "outputs/qwen3-4b-instruct/os/{TIMESTAMP}-no_h3"
# output: "outputs/qwen3-4b-instruct/os/{TIMESTAMP}-no_h4"
# output: "outputs/qwen3-4b-instruct/os/{TIMESTAMP}-no_h5"
output: "outputs/qwen3-4b-instruct/os/{TIMESTAMP}-only-h3-h5"


trials: 1