assignments:
- agent:
  - claude-opus-4-8
  task:
  - webshop-std-baseline
concurrency:
  agent:
    claude-opus-4-8: 5
  task:
    webshop-std-baseline: 16
import: definition.yaml
output: outputs/claude-opus-4-8/webshop/{TIMESTAMP}-baseline
trials: 1
