name: PF Reusable CI Caller

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

permissions:
  contents: read

jobs:
  call-pf-ci:
    uses: ./.github/workflows/pf-ci.yaml
    with:
      pr_number: ${{ github.event.pull_request.number || '' }}
      run_phases: "2,3,6"
    secrets: inherit
