from __future__ import annotations

import json

import pytest
from tasks import _emit_datasource_factory_index

from great_expectations.datasource.fluent import _SCHEMAS_DIR
from great_expectations.datasource.fluent.sources import DataSourceManager

_INDEX_PATH = _SCHEMAS_DIR / "index.json"


@pytest.mark.unit
def test_datasource_catalog_index_matches_generator():
    """The checked-in datasource factory-method index must equal what regenerating it produces.

    The index is derived from the live datasource type registry, not hand-maintained -
    registering, removing, or renaming a datasource type without regenerating the index
    would drift it silently out from under anything that reads it to discover the
    fluent factory surface. Regenerate with `invoke schemas --sync`.
    """
    regenerated = _emit_datasource_factory_index(indent=4)
    checked_in = _INDEX_PATH.read_text()
    assert regenerated == checked_in, (
        "datasource/fluent/schemas/index.json is out of date, run `invoke schemas --sync`"
    )


@pytest.mark.unit
def test_datasource_catalog_index_entries_name_existing_factories():
    """Every datasource-index entry must name a factory method that actually exists.

    The index maps each datasource's schema file to its exact `add_or_update_*` factory
    method name so consumers never have to guess the name from the file name - the
    mapping is irregular and can't be reconstructed by a generic rule. An entry that
    names a factory method which doesn't actually exist would send a consumer to call a
    method that raises `AttributeError`.
    """
    catalog: dict[str, str] = json.loads(_INDEX_PATH.read_text())
    known_factory_names = frozenset(DataSourceManager.__new__(DataSourceManager).factories)

    unknown = {
        schema_file: factory_name
        for schema_file, factory_name in catalog.items()
        if factory_name not in known_factory_names
    }
    assert not unknown, (
        "The following datasource-index entries name a factory method that does not "
        f"exist on DataSourceManager: {unknown}. The index is generated by reconstructing "
        "each entry as `add_or_update_<type_name>` from the live datasource type registry "
        "(see `_register_add_or_update_datasource` in `datasource/fluent/sources.py`) - "
        "`invoke schemas --sync` reproduces the same reconstruction and will abort with "
        "this same error instead of fixing it. Check whether the affected datasource "
        "type's registered name or its add_or_update factory method was renamed out of "
        "step with the other, and bring them back in line."
    )
