"""JSON-schema verifier: parse agent answer as JSON, validate against schema."""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""JSON-schema verifier — generated by nemotron_gym.

verifier_data.json:
  {
    "schema": <jsonschema document, parsed dict>,
    "schema_type": "json" (informational),
  }

Reads /app/answer.txt, optionally unwraps a ```json ... ``` fence, parses
as JSON, validates against schema with `jsonschema.Draft202012Validator`.
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
ANSWER = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    schema = data.get("schema")
    if not isinstance(schema, dict):
        print("schema must be object", file=sys.stderr)
        return 0
    if not ANSWER.exists():
        print("/app/answer.txt missing", file=sys.stderr)
        return 0
    raw = ANSWER.read_text(errors="replace")
    fence = re.search(r"```(?:json)?\s*(.*?)```", raw, flags=re.DOTALL)
    candidate = fence.group(1) if fence else raw
    try:
        instance = json.loads(candidate)
    except Exception as e:
        print(f"JSON parse error: {e}")
        return 0
    try:
        from jsonschema import Draft202012Validator
    except ImportError as e:
        print(f"jsonschema unavailable: {e}", file=sys.stderr)
        return 0
    validator = Draft202012Validator(schema)
    errors = sorted(validator.iter_errors(instance), key=lambda e: e.path)
    if not errors:
        print("verdict: valid")
        return 1
    for err in errors[:5]:
        print(f"  err at {'/'.join(map(str, err.path))}: {err.message}")
    print(f"verdict: {len(errors)} validation error(s)")
    return 0


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
