"""LLM-judge verifier aligned with Harbor conventions.

Follows the pattern used by Harbor's strongreject / gaia2 adapters:
- Calls the LLM via `litellm.completion` (multi-provider; just swap JUDGE_MODEL).
- Default model: `openai/gpt-4o-mini` (Harbor's default judge).
- Env var overrides: `JUDGE_MODEL`, `OPENAI_BASE_URL`, `OPENAI_API_KEY`.
- `temperature=0`, `timeout=300`.
- Reads the agent's answer from `/app/response.txt` (Harbor's strongreject path),
  with a fallback to `/app/answer.txt` (legacy).
- Score parsed from \\boxed{<float>} on the last line; falls back to any number
  in [0,1].
- Writes `str(score)` to `/logs/verifier/reward.txt` (Harbor convention).

verifier_data.json schema:
  {
    "judge_system_prompt": str (optional, default below),
    "judge_prompt_template": str (with {instruction} {response} {rubric}
                                  {principle} placeholders; default below),
    "instruction": str,                # task prompt the agent saw
    "rubric": list[{"id": str, "criteria": str}] (optional),
    "principle": str (optional),
    "score_threshold": float (default 0.5),
    "judge_model": str (optional, overrides JUDGE_MODEL env var fallback),
  }
"""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""LLM-judge verifier — generated by nemotron_gym (Harbor-aligned)."""
from __future__ import annotations

import json
import os
import pathlib
import re
import sys
from collections import defaultdict

REWARD = pathlib.Path("/logs/verifier/reward.txt")
RESPONSE_PRIMARY = pathlib.Path("/app/response.txt")
RESPONSE_LEGACY = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")

DEFAULT_JUDGE_MODEL = "openai/gpt-4o-mini"
JUDGE_TIMEOUT_S = 300

DEFAULT_SYSTEM_PROMPT = (
    "You are an impartial evaluator. Read the task and the candidate response, "
    "score it from 0.0 to 1.0 on how well it satisfies the task. Provide your "
    "final score in \\boxed{...} on the last line."
)

DEFAULT_TEMPLATE = """Task / Instruction:
{instruction}

Candidate response:
{response}

Rubric (if any):
{rubric}

Score from 0.0 (does not satisfy) to 1.0 (fully satisfies). End with \\boxed{{<score>}}."""


def _write_reward(score: float) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text(str(score))


def _read_response() -> str | None:
    for path in (RESPONSE_PRIMARY, RESPONSE_LEGACY):
        if path.exists():
            text = path.read_text(errors="replace")
            if text.strip():
                return text
    return None


def _format_rubric(items) -> str:
    if not isinstance(items, list) or not items:
        return "(none)"
    lines = []
    for it in items:
        if not isinstance(it, dict):
            continue
        rid = it.get("id", "?")
        crit = it.get("criteria", "")
        lines.append(f"  [{rid}] {crit}")
    return "\n".join(lines) if lines else "(none)"


def _extract_score(text: str) -> float:
    m = re.search(r"\\boxed\{\s*([\d.]+)\s*\}", text)
    if m:
        try:
            return max(0.0, min(1.0, float(m.group(1))))
        except ValueError:
            pass
    for m2 in re.finditer(r"\b(0\.\d+|1\.0|0|1)\b", text):
        try:
            return max(0.0, min(1.0, float(m2.group(1))))
        except ValueError:
            continue
    return 0.0


def _resolve_model(data: dict) -> str:
    cfg = data.get("judge_model")
    if isinstance(cfg, str) and cfg.strip():
        return cfg.strip()
    return os.environ.get("JUDGE_MODEL", DEFAULT_JUDGE_MODEL).strip() or DEFAULT_JUDGE_MODEL


def main() -> float:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0.0
    data = json.loads(DATA.read_text())
    response_text = _read_response()
    if response_text is None:
        print(
            "Agent response not found at /app/response.txt or /app/answer.txt",
            file=sys.stderr,
        )
        return 0.0
    instruction = data.get("instruction", "")
    rubric = data.get("rubric")
    principle = data.get("principle")
    template = data.get("judge_prompt_template") or DEFAULT_TEMPLATE
    system_prompt = data.get("judge_system_prompt") or DEFAULT_SYSTEM_PROMPT

    fmt_kwargs = defaultdict(str)
    fmt_kwargs["instruction"] = instruction
    fmt_kwargs["response"] = response_text
    fmt_kwargs["rubric"] = _format_rubric(rubric)
    if isinstance(principle, str):
        fmt_kwargs["principle"] = principle
    try:
        prompt = template.format_map(fmt_kwargs)
    except (KeyError, IndexError, ValueError) as e:
        print(f"template format error ({e}); using default")
        prompt = DEFAULT_TEMPLATE.format_map(fmt_kwargs)

    # Harbor uses litellm — single API works across openai/anthropic/etc.
    try:
        from litellm import completion
    except ImportError:
        print("litellm unavailable in container", file=sys.stderr)
        return 0.0

    model = _resolve_model(data)
    try:
        resp = completion(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": prompt},
            ],
            temperature=0,
            timeout=JUDGE_TIMEOUT_S,
        )
    except Exception as e:
        print(f"judge API error ({model}): {e}", file=sys.stderr)
        return 0.0
    if not resp or not resp.choices:
        print(f"judge ({model}) returned no choices", file=sys.stderr)
        return 0.0
    judge_output = (resp.choices[0].message.content or "").strip()
    print(f"Judge model: {model}")
    print(f"Judge output:\n{judge_output[:2000]}")
    score = _extract_score(judge_output)
    threshold = float(data.get("score_threshold", 0.5))
    print(f"Extracted score: {score} (threshold={threshold})")
    return score


if __name__ == "__main__":
    score = 0.0
    try:
        score = float(main())
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0.0
    _write_reward(score)
'''
