"""OpenQA normalized-text verifier: normalize whitespace/case/punct, compare."""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""Normalized text-match verifier — generated by nemotron_gym."""
from __future__ import annotations

import json
import pathlib
import re
import string
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
ANSWER = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")
MAX_ANSWER_BYTES = 64 * 1024


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


_ARTICLES = re.compile(r"\b(a|an|the)\b")


def _normalize(s: str) -> str:
    s = s.lower()
    s = "".join(ch for ch in s if ch not in string.punctuation)
    s = _ARTICLES.sub(" ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    expected = data.get("expected_answers", [])
    if isinstance(data.get("expected_answer"), str):
        expected = [data["expected_answer"]]
    if not isinstance(expected, list) or not expected:
        print("expected_answer(s) missing", file=sys.stderr)
        return 0
    if not ANSWER.exists():
        print("/app/answer.txt missing", file=sys.stderr)
        return 0
    raw = ANSWER.read_text(errors="replace")[:MAX_ANSWER_BYTES]
    got = _normalize(raw)
    print(f"got_normalized={got!r}")
    for exp in expected:
        if not isinstance(exp, str):
            continue
        e = _normalize(exp)
        print(f"  vs expected_normalized={e!r}")
        if got == e or e in got:
            print("verdict: match")
            return 1
    print("verdict: mismatch")
    return 0


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
