"""MCQA letter-match verifier: extract one letter via regex, compare to expected."""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""MCQA letter-match verifier — generated by nemotron_gym."""
from __future__ import annotations

import json
import pathlib
import re
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
ANSWER = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")
MAX_REGEX_LEN = 512
MAX_ANSWER_BYTES = 64 * 1024


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    expected = data.get("expected_answer", "")
    pattern = data.get("output_regex", r"Answer\s*:\s*(?!Answer)\s*([A-Za-z0-9])\s*")
    if not isinstance(expected, str) or not isinstance(pattern, str):
        print("expected_answer / output_regex must be strings", file=sys.stderr)
        return 0
    if len(pattern) > MAX_REGEX_LEN:
        print(f"regex too long ({len(pattern)} > {MAX_REGEX_LEN})", file=sys.stderr)
        return 0
    if not ANSWER.exists():
        print("/app/answer.txt missing", file=sys.stderr)
        return 0
    raw = ANSWER.read_text(errors="replace")[:MAX_ANSWER_BYTES]
    try:
        # Compile then match with a guard timeout via re's BackRefError-resistant
        # patterns. We trust the dataset's own regex but cap pattern length.
        rx = re.compile(pattern)
    except re.error as e:
        print(f"regex compile error: {e}", file=sys.stderr)
        return 0
    matches = list(rx.finditer(raw))
    if not matches:
        # Fallback: look for trailing single-letter answer.
        for line in reversed(raw.splitlines()):
            m = re.search(r"\b([A-Za-z])\b\s*$", line.strip())
            if m:
                matches = [m]
                break
    if not matches:
        print("no answer extracted")
        print("verdict: mismatch")
        return 0
    extracted = matches[-1].group(1) if matches[-1].groups() else matches[-1].group(0)
    extracted = extracted.strip().upper()
    expected_up = expected.strip().upper()
    print(f"extracted={extracted!r} expected={expected_up!r}")
    score = 1 if extracted == expected_up else 0
    print("verdict:", "match" if score else "mismatch")
    return score


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
