"""Competitive coding verifier: run solution.py against stdin/stdout tests."""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""Stdio competitive-coding verifier — generated by nemotron_gym.

Runs /app/solution.py against each test case from verifier_data.json, comparing
captured stdout against the expected output. Passes iff ALL tests pass.
"""
from __future__ import annotations

import json
import os
import pathlib
import subprocess
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
SOLUTION = pathlib.Path("/app/solution.py")
DATA = pathlib.Path("/tests/verifier_data.json")
PER_TEST_TIMEOUT_S = 10


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


def _normalize(s: str) -> str:
    # Match codeforces-style: strip trailing whitespace on each line + EOF blank lines.
    lines = s.replace("\r\n", "\n").split("\n")
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(line.rstrip() for line in lines)


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    inputs = data.get("inputs", [])
    outputs = data.get("outputs", [])
    if not (isinstance(inputs, list) and isinstance(outputs, list)):
        print("inputs/outputs must be lists", file=sys.stderr)
        return 0
    if len(inputs) != len(outputs) or not inputs:
        print(f"no/mismatched tests: {len(inputs)} inputs, {len(outputs)} outputs", file=sys.stderr)
        return 0
    if not SOLUTION.exists():
        print("/app/solution.py missing — agent did not write solution", file=sys.stderr)
        return 0
    env = {k: v for k, v in os.environ.items() if k in ("PATH", "HOME", "LANG", "LC_ALL")}
    env.setdefault("PATH", "/usr/local/bin:/usr/bin:/bin")
    n_total = len(inputs)
    n_passed = 0
    for i, (inp, exp) in enumerate(zip(inputs, outputs)):
        if not isinstance(inp, str) or not isinstance(exp, str):
            print(f"test {i}: non-string input/output", file=sys.stderr)
            continue
        try:
            res = subprocess.run(
                ["python3", str(SOLUTION)],
                input=inp,
                capture_output=True,
                text=True,
                timeout=PER_TEST_TIMEOUT_S,
                env=env,
                cwd="/app",
            )
        except subprocess.TimeoutExpired:
            print(f"test {i}: TIMEOUT after {PER_TEST_TIMEOUT_S}s")
            continue
        except Exception as e:
            print(f"test {i}: exec error: {e}")
            continue
        got = _normalize(res.stdout)
        want = _normalize(exp)
        if got == want:
            n_passed += 1
        else:
            print(f"test {i}: MISMATCH")
            print(f"  got: {got[:200]!r}")
            print(f"  want: {want[:200]!r}")
            if res.stderr:
                print(f"  stderr: {res.stderr[:200]!r}")
    print(f"passed={n_passed}/{n_total}")
    return 1 if n_passed == n_total else 0


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
