"""Substring/exact-match verifier: identity / safety / simple text checks."""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""Substring-match verifier — generated by nemotron_gym.

verifier_data.json schema:
  {
    "mode": "any_of" | "all_of" | "none_of" | "exact",
    "needles": ["str", ...],
    "case_sensitive": bool (default False),
  }
"""
from __future__ import annotations

import json
import pathlib
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
ANSWER = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    mode = data.get("mode", "any_of")
    needles = data.get("needles", [])
    cs = bool(data.get("case_sensitive", False))
    if not isinstance(needles, list) or mode not in ("any_of", "all_of", "none_of", "exact"):
        print("malformed verifier_data", file=sys.stderr)
        return 0
    if not ANSWER.exists():
        print("/app/answer.txt missing", file=sys.stderr)
        return 0
    raw = ANSWER.read_text(errors="replace")
    text = raw if cs else raw.lower()
    items = [n if cs else (n.lower() if isinstance(n, str) else n) for n in needles]
    if mode == "exact":
        ok = len(items) == 1 and isinstance(items[0], str) and text.strip() == items[0].strip()
    elif mode == "any_of":
        ok = any(isinstance(n, str) and n in text for n in items)
    elif mode == "all_of":
        ok = all(isinstance(n, str) and n in text for n in items)
    elif mode == "none_of":
        ok = not any(isinstance(n, str) and n in text for n in items)
    else:
        ok = False
    print(f"mode={mode} needles={items[:5]} verdict={'match' if ok else 'mismatch'}")
    return 1 if ok else 0


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
