import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { ConfigProvider } from "antd";
import enUS from "antd/locale/en_US";
import zhCN from "antd/locale/zh_CN";

export type Locale = "zh-CN" | "en-US";

export const zh = {
  "app.title": "鸾鸟智能体工作台",
  "language.switchToEnglish": "切换到英文",
  "language.switchToChinese": "切换到中文",
  "language.english": "English",
  "language.chinese": "中文",
  "common.load": "载入",
  "common.start": "启动",
  "common.stop": "停止",
  "common.close": "关闭",
  "common.cancel": "取消",
  "common.refresh": "刷新",
  "common.clear": "清除",
  "common.apply": "应用",
  "common.previous": "上一页",
  "common.next": "下一页",
  "common.none": "无",
  "common.unknown": "未知",
  "common.justNow": "刚刚",
  "common.minutesAgo": "{value} 分钟前",
  "common.hoursAgo": "{value} 小时前",
  "common.daysAgo": "{value} 天前",
  "common.active": "活跃",
  "common.idle": "空闲",
  "common.items": "{value} 项",
  "auth.brand": "鸾鸟渗透智能体",
  "auth.tagline": "统一观察智能体的判断、行动与证据。",
  "auth.description": "面向安全研究与授权评测的多 Agent 运行工作台，集中管理实时轨迹、三图状态、任务队列和证据产物。",
  "auth.capability.trace": "实时轨迹",
  "auth.capability.traceDescription": "聚合 Agent 想法、动作和工具返回",
  "auth.capability.graph": "三图推理",
  "auth.capability.graphDescription": "推理图、作战图与任务树同步联动",
  "auth.capability.session": "会话管理",
  "auth.capability.sessionDescription": "快速切换历史 Runtime 与执行上下文",
  "auth.capability.protection": "访问保护",
  "auth.capability.protectionDescription": "账号会话隔离敏感运行数据",
  "auth.serviceReady": "认证服务就绪",
  "auth.sessionProtected": "会话已保护",
  "auth.sqlitePersistence": "SQLite 持久化",
  "auth.access": "工作台访问",
  "auth.enterWorkbench": "进入鸾鸟工作台",
  "auth.accessDescription": "使用团队账号登录，或注册一个新的分析员账号。",
  "auth.login": "登录",
  "auth.register": "注册",
  "auth.securityNote": "密码仅以加盐哈希保存，会话使用 HttpOnly Cookie。",
  "auth.username": "用户名",
  "auth.password": "密码",
  "auth.displayName": "显示名称",
  "auth.confirmPassword": "确认密码",
  "auth.usernameRequired": "请输入用户名",
  "auth.passwordRequired": "请输入密码",
  "auth.displayNameRequired": "请输入显示名称",
  "auth.usernamePattern": "使用 3-32 位字母、数字或 ._-",
  "auth.passwordLength": "密码至少 8 位",
  "auth.confirmPasswordRequired": "请再次输入密码",
  "auth.passwordMismatch": "两次输入的密码不一致",
  "auth.passwordPlaceholder": "输入密码",
  "auth.displayNamePlaceholder": "安全分析员",
  "auth.passwordMinPlaceholder": "至少 8 位",
  "auth.confirmPasswordPlaceholder": "再次输入密码",
  "auth.loginWorkbench": "登录工作台",
  "auth.createAccount": "创建账号并进入",
  "nav.close": "关闭导航",
  "nav.open": "打开导航",
  "nav.trace": "实时轨迹",
  "nav.reports": "产物与报告",
  "nav.traffic": "Web Traffic",
  "nav.connections": "连接",
  "nav.reasoning": "推理图",
  "nav.operation": "作战图",
  "nav.task": "任务图",
  "sidebar.sessions": "运行会话",
  "sidebar.noSessions": "暂无会话",
  "sidebar.standalone": "独立会话",
  "sidebar.agentStatus": "Agent 状态",
  "sidebar.noEvents": "暂无事件",
  "sidebar.noGoal": "暂无目标摘要",
  "sidebar.tasksTrace": "{tasks} 个任务 · {events} 条轨迹 · {time}",
  "app.connectionsInspectorTitle": "连接管理",
  "app.connectionsInspectorDescription": "管理员可控制托管的 SSH/chisel 连接。原始或非托管连接仅展示，不会自动关联到任务或会话。",
  "app.runtimeDirectory": "Runtime 目录",
  "app.startTask": "启动任务",
  "app.stopConfirm": "停止当前任务？",
  "app.stopDescription": "将优雅中断该运行，已产出的数据会保留。",
  "app.refreshRuntime": "刷新运行态",
  "app.autoRefresh": "自动刷新",
  "app.openInspector": "打开详情",
  "app.userMenu": "用户菜单",
  "app.administrator": "管理员",
  "app.analyst": "分析员",
  "app.logout": "退出登录",
  "app.currentGoal": "当前目标",
  "app.initializingGoal": "任务启动中…",
  "app.waitingRuntime": "等待运行态数据",
  "app.scopeFallback": "加载 Runtime 后展示目标、范围与当前执行状态。",
  "app.running": "运行中",
  "app.updatedAt": "更新于 {time}",
  "app.notLoaded": "尚未加载",
  "app.inspectorDrawer": "详情检查器",
  "app.traceTitle": "Agent 运行轨迹",
  "app.traceStageTitle": "Agent 正在判断什么、执行什么、观察到什么",
  "app.traceStageSubtitle": "选择任意事件，在右侧查看证据、Artifact、图引用与原始载荷。",
  "app.trafficStageTitle": "捕获、检查并安全 Replay HTTP 流量",
  "app.trafficStageSubtitle": "按 method、host、status 与执行引用过滤；body 仅在请求时加载。",
  "app.connectionsStageTitle": "连接、隧道与会话状态",
  "app.connectionsStageSubtitle": "管理员可控制托管 SSH/chisel 生命周期；分析员和非托管/原始连接保持只读。",
  "app.initializingTitle": "任务已启动，正在初始化",
  "app.initializingDescription": "Planner 正在进行首次规划，通常需要 30~90 秒。",
  "app.initializingHint": "第一张 Planner 卡片出现后页面会自动切换；页面每 5 秒自动刷新，无需手动操作。若长时间无事件，请检查 LLM 服务是否可用。",
  "metric.trace": "轨迹",
  "metric.nodes": "节点",
  "metric.edges": "关系",
  "metric.artifacts": "产物",
  "graph.reasoningSubtitle": "追踪证据、假设、漏洞与利用之间的推导关系。",
  "graph.operationSubtitle": "梳理主机、服务、端点、参数与凭据组成的攻击面。",
  "graph.taskSubtitle": "查看范围、目标与任务的树状关系；里程碑和阻塞项收纳在所属任务中。",
  "graph.searchPlaceholder": "搜索节点名称、ID 或类型",
  "graph.nodeType": "节点类型",
  "graph.edgeType": "关系类型",
  "graph.zoomOut": "缩小",
  "graph.zoomIn": "放大",
  "graph.fit": "适配画布",
  "graph.relayout": "重新布局",
  "graph.clearSelection": "清除选择",
  "graph.nodeList": "图节点列表",
  "graph.nodes": "节点",
  "graph.noMatchingNodes": "没有匹配节点",
  "graph.noVisibleNodes": "当前筛选条件下没有可展示的节点",
  "graph.counts": "{nodes} 个节点 · {edges} 个{relations}",
  "graph.treeRelations": "树关系",
  "graph.relations": "关系",
  "graph.milestones": "{value} 个里程碑",
  "graph.blockers": "{value} 个阻塞项",
  "trace.all": "全部",
  "trace.newestFirst": "最新优先",
  "trace.chronological": "时间顺序",
  "trace.empty": "当前筛选条件下没有 Trace 事件",
  "trace.decision": "决策",
  "trace.observation": "观察",
  "trace.next": "下一步",
  "trace.eventChain": "事件链",
  "trace.noSummary": "当前步骤没有可展示的判断摘要。",
  "trace.action": "执行动作",
  "trace.noAction": "本步骤没有触发外部工具动作。",
  "trace.expandDetails": "展开执行细节",
  "trace.aggregatedEvent": "查看聚合事件",
  "trace.rawEvent": "查看原始事件",
  "trace.recordedIntent": "Agent 想法",
  "trace.structuredIntent": "判断依据",
  "trace.derivedIntent": "行动目的",
  "trace.toolFailed": "工具执行失败",
  "trace.noToolOutput": "暂无工具输出",
  "startRun.title": "启动新任务",
  "startRun.goal": "任务目标",
  "startRun.goalRequired": "请输入任务目标",
  "startRun.goalPlaceholder": "例如：对授权目标 http://10.0.x.x 进行安全测试，寻找并提交所有 flag",
  "startRun.scope": "授权范围",
  "startRun.scopeRequired": "请输入授权范围",
  "startRun.scopePlaceholder": "例如：10.0.0.0/24,baidu.com,*.example.com",
  "startRun.maxMinutes": "最大运行时间（分钟）",
  "startRun.parallelTasks": "并行任务数",
  "startRun.plannerCycles": "Planner 连续无进展上限",
  "resize.navigation": "调整导航栏宽度",
  "resize.inspector": "调整详情栏宽度",
  "resize.title": "{label}，双击恢复默认宽度",
  "connections.description": "托管 SSH/Chisel Route 在活动和历史 Run 中均可重连；Session 与原始连接只读。",
  "connections.empty": "当前 Runtime 暂无连接",
  "connections.managed": "可控制",
  "connections.unmanaged": "只读",
  "connections.desired": "期望状态",
  "connections.available": "可用",
  "connections.unavailable": "不可用",
  "connections.heartbeat": "心跳",
  "connections.error": "错误",
  "connections.viewGraph": "在状态图中查看",
  "connections.graph": "状态图",
  "connections.reconnect": "重连",
  "connections.forget": "忘记 Route",
  "connections.forgetConfirm": "永久忘记这个 Route？",
  "status.live": "在线",
  "status.degraded": "异常",
  "status.stale": "过期",
  "status.closed": "已关闭",
  "status.running": "运行中",
  "status.stopped": "已停止",
  "status.completed": "已完成",
  "status.blocked": "已阻塞",
  "status.pending": "等待中",
  "status.failed": "失败",
  "inspector.currentStep": "当前步骤",
  "inspector.nodeDetails": "节点详情",
  "inspector.selectTrace": "选择一条 Trace 查看详情",
  "inspector.summarySource": "摘要来源",
  "inspector.publicOutput": "Agent 公开输出",
  "inspector.structuredReason": "结构化理由",
  "inspector.derivedPurpose": "系统派生目的",
  "inspector.action": "动作",
  "inspector.noExternalAction": "无外部动作",
  "inspector.stage": "阶段",
  "inspector.event": "事件",
  "inspector.task": "任务",
  "inspector.time": "时间",
  "inspector.commandDetails": "命令明细",
  "inspector.noArtifact": "无关联 Artifact",
  "inspector.aggregatedEvent": "聚合事件",
  "inspector.rawEvent": "原始事件",
  "inspector.loadingContent": "正在加载内容…",
  "inspector.loadContentFailed": "无法加载完整内容：{error}",
  "inspector.truncatedContent": "（内容过大，仅显示前段）",
  "inspector.selectNode": "选择图中的节点查看属性与关系",
  "inspector.milestones": "里程碑 {value}",
  "inspector.blockers": "阻塞项 {value}",
  "inspector.noMilestones": "暂无里程碑",
  "inspector.noBlockers": "暂无阻塞项",
  "inspector.evidence": "证据",
  "inspector.evidenceCount": "{value} 条证据",
  "inspector.noRefs": "无关联引用",
  "inspector.incoming": "入边 {value}",
  "inspector.outgoing": "出边 {value}",
  "inspector.noRelations": "无关系",
  "inspector.taskQueue": "任务队列 · {value}",
  "inspector.noTasks": "暂无任务",
  "traffic.filters": "Traffic 过滤器",
  "traffic.methodFilter": "Method 过滤",
  "traffic.hostFilter": "Host 过滤",
  "traffic.statusFilter": "Status 过滤",
  "traffic.taskRefFilter": "Task ref 过滤",
  "traffic.runRefFilter": "Run ref 过滤",
  "traffic.modeFilter": "Mode 过滤",
  "traffic.errorFilter": "Error 过滤",
  "traffic.onlyErrors": "仅错误",
  "traffic.noErrors": "无错误",
  "traffic.refresh": "刷新 Traffic",
  "traffic.empty": "没有匹配的流量记录",
  "traffic.pageSize": "每页最多 {value} 条",
  "traffic.selectExchange": "选择 exchange {value}",
  "traffic.unknownHost": "未知主机",
  "traffic.requestObserved": "请求 {captured} / {observed} 已观察",
  "traffic.responseObserved": "响应 {captured} / {observed} 已观察",
  "traffic.capturedObserved": "{captured} 已捕获 / {observed} 已观察",
  "traffic.inspector": "TRAFFIC 检查器",
  "traffic.exchangeDetails": "Exchange 详情",
  "traffic.selectRecord": "选择一条流量记录查看详情",
  "traffic.started": "开始",
  "traffic.completed": "完成",
  "traffic.duration": "耗时",
  "traffic.protocol": "协议",
  "traffic.mode": "模式",
  "traffic.requestBytes": "请求字节",
  "traffic.responseBytes": "响应字节",
  "traffic.error": "错误",
  "traffic.requestHeaders": "请求 Headers",
  "traffic.responseHeaders": "响应 Headers",
  "traffic.requestBody": "请求 Body",
  "traffic.responseBody": "响应 Body",
  "traffic.headersTruncated": "Headers 已截断{reason}",
  "traffic.noHeaders": "未记录 headers",
  "traffic.displayFormat": "{side} 展示格式",
  "traffic.loadingOnDemand": "正在按需加载…",
  "traffic.bodyReadFailed": "Body 无法读取，可能已淘汰或过大：{error}",
  "traffic.loadBody": "加载 body（最大 256 KiB）",
  "traffic.bodyTruncated": "Body 仅显示已捕获部分（截断{reason}）",
  "traffic.replayAdminOnly": "仅管理员可发送 Replay；分析员可查看原始 exchange。",
  "traffic.editReplay": "编辑并 Replay",
  "traffic.replayMethod": "Replay Method",
  "traffic.replayUrl": "Replay URL",
  "traffic.replayHeaderName": "Replay Header 名称 {value}",
  "traffic.replayHeaderValue": "Replay Header 值 {value}",
  "traffic.replayBody": "Replay Body",
  "traffic.deleteHeader": "删除 header {value}",
  "traffic.addHeader": "添加 header",
  "traffic.editedBody": "将发送编辑后的 body",
  "traffic.sourceBody": "Body 未修改，将由 sidecar 使用完整源 body",
  "traffic.prepareSend": "准备发送",
  "traffic.confirmReplay": "确认发送 Replay",
  "traffic.confirmSend": "确认发送",
  "traffic.replayWarning": "Replay 可能携带敏感 header 与 body",
  "traffic.replayWarningDescription": "请确认你有权向目标发送该请求。敏感值不会写入 URL、localStorage 或前端日志。",
  "traffic.headersCount": "{value} 项（可能含 Authorization/Cookie）",
  "traffic.bodyOverride": "{value} 字符（{mode} override）",
  "traffic.fullSourceBody": "使用完整源 body（无 override）",
  "traffic.referenceChain": "关联链",
  "traffic.noReferenceChain": "无 task/run/route/session/connect 关联",
  "traffic.bodyAvailable": "Body 尚未加载；点击后按需读取，最大 256 KiB。",
  "traffic.bodyEvicted": "Body 已从捕获存储淘汰。",
  "traffic.bodyUnavailableTruncated": "Body 过大或已截断，且没有可读取引用{reason}。",
  "traffic.bodyNoBytes": "Body 未捕获：该方向没有观察到 body 字节。",
  "traffic.bodyNotCaptured": "Body 未捕获（capture state: {state}）。",
  "traffic.invalidUrl": "无效 URL",
  "traffic.tcpReplayUnavailable": "TCP 流量仅支持检查，不能作为 HTTP Replay",
  "api.csrfUnavailable": "无法获取 CSRF token",
  "dashboard.sessionsFailed": "会话列表加载失败：{error}",
  "dashboard.runtimeFailed": "运行态加载失败：{error}"
} as const;

export const en = {
  "app.title": "LuaNiao Agent Workbench",
  "language.switchToEnglish": "Switch to English",
  "language.switchToChinese": "Switch to Chinese",
  "language.english": "English",
  "language.chinese": "中文",
  "common.load": "Load",
  "common.start": "Start",
  "common.stop": "Stop",
  "common.close": "Close",
  "common.cancel": "Cancel",
  "common.refresh": "Refresh",
  "common.clear": "Clear",
  "common.apply": "Apply",
  "common.previous": "Previous",
  "common.next": "Next",
  "common.none": "None",
  "common.unknown": "Unknown",
  "common.justNow": "just now",
  "common.minutesAgo": "{value} min ago",
  "common.hoursAgo": "{value} hr ago",
  "common.daysAgo": "{value} days ago",
  "common.active": "active",
  "common.idle": "idle",
  "common.items": "{value} items",
  "auth.brand": "LuaNiao Security Agent",
  "auth.tagline": "Observe agent reasoning, actions, and evidence in one place.",
  "auth.description": "A multi-agent operations workbench for security research and authorized assessment, bringing live traces, tri-graph state, task queues, and evidence artifacts together.",
  "auth.capability.trace": "Live Trace",
  "auth.capability.traceDescription": "Aggregate agent thoughts, actions, and tool results",
  "auth.capability.graph": "Tri-Graph Reasoning",
  "auth.capability.graphDescription": "Keep reasoning, operation, and task graphs synchronized",
  "auth.capability.session": "Session Management",
  "auth.capability.sessionDescription": "Switch quickly between runtime history and execution contexts",
  "auth.capability.protection": "Access Protection",
  "auth.capability.protectionDescription": "Protect sensitive runtime data with account sessions",
  "auth.serviceReady": "Auth service ready",
  "auth.sessionProtected": "Session protected",
  "auth.sqlitePersistence": "SQLite persistence",
  "auth.access": "WORKSPACE ACCESS",
  "auth.enterWorkbench": "Enter LuaNiao Workbench",
  "auth.accessDescription": "Sign in with a team account or register a new analyst account.",
  "auth.login": "Sign in",
  "auth.register": "Register",
  "auth.securityNote": "Passwords are stored only as salted hashes; sessions use HttpOnly cookies.",
  "auth.username": "Username",
  "auth.password": "Password",
  "auth.displayName": "Display name",
  "auth.confirmPassword": "Confirm password",
  "auth.usernameRequired": "Enter your username",
  "auth.passwordRequired": "Enter your password",
  "auth.displayNameRequired": "Enter a display name",
  "auth.usernamePattern": "Use 3–32 letters, numbers, or ._-",
  "auth.passwordLength": "Password must be at least 8 characters",
  "auth.confirmPasswordRequired": "Enter the password again",
  "auth.passwordMismatch": "The passwords do not match",
  "auth.passwordPlaceholder": "Enter password",
  "auth.displayNamePlaceholder": "Security analyst",
  "auth.passwordMinPlaceholder": "At least 8 characters",
  "auth.confirmPasswordPlaceholder": "Enter password again",
  "auth.loginWorkbench": "Enter workbench",
  "auth.createAccount": "Create account and continue",
  "nav.close": "Close navigation",
  "nav.open": "Open navigation",
  "nav.trace": "Live Trace",
  "nav.reports": "Artifacts & Reports",
  "nav.traffic": "Web Traffic",
  "nav.connections": "Connections",
  "nav.reasoning": "Reasoning Graph",
  "nav.operation": "Operation Graph",
  "nav.task": "Task Graph",
  "sidebar.sessions": "Runtime Sessions",
  "sidebar.noSessions": "No sessions",
  "sidebar.standalone": "Standalone Sessions",
  "sidebar.agentStatus": "Agent Status",
  "sidebar.noEvents": "No events",
  "sidebar.noGoal": "No goal summary",
  "sidebar.tasksTrace": "{tasks} tasks · {events} traces · {time}",
  "app.connectionsInspectorTitle": "Connection Management",
  "app.connectionsInspectorDescription": "Administrators can control managed SSH/chisel connections. Raw and unmanaged connections are display-only and are not linked automatically to tasks or sessions.",
  "app.runtimeDirectory": "Runtime directory",
  "app.startTask": "Start run",
  "app.stopConfirm": "Stop the current run?",
  "app.stopDescription": "The run will be interrupted gracefully and existing data will be retained.",
  "app.refreshRuntime": "Refresh runtime",
  "app.autoRefresh": "Auto refresh",
  "app.openInspector": "Open inspector",
  "app.userMenu": "User menu",
  "app.administrator": "Administrator",
  "app.analyst": "Analyst",
  "app.logout": "Sign out",
  "app.currentGoal": "Current Goal",
  "app.initializingGoal": "Run starting…",
  "app.waitingRuntime": "Waiting for runtime data",
  "app.scopeFallback": "Load a runtime to view its goal, scope, and current execution status.",
  "app.running": "Running",
  "app.updatedAt": "Updated {time}",
  "app.notLoaded": "Not loaded",
  "app.inspectorDrawer": "Inspector",
  "app.traceTitle": "Agent Trace",
  "app.traceStageTitle": "What the agents are reasoning about, doing, and observing",
  "app.traceStageSubtitle": "Select an event to inspect evidence, artifacts, graph references, and the raw payload.",
  "app.trafficStageTitle": "Capture, inspect, and safely replay HTTP traffic",
  "app.trafficStageSubtitle": "Filter by method, host, status, and execution references; bodies load only on demand.",
  "app.connectionsStageTitle": "Connections, tunnels, and session status",
  "app.connectionsStageSubtitle": "Administrators control managed SSH/chisel lifecycles; analysts and unmanaged/raw connections remain read-only.",
  "app.initializingTitle": "Run started and initializing",
  "app.initializingDescription": "Planner is preparing the first plan, which usually takes 30–90 seconds.",
  "app.initializingHint": "The page switches automatically when the first Planner card appears and refreshes every 5 seconds. If no events appear for a long time, check the LLM service.",
  "metric.trace": "Trace",
  "metric.nodes": "Nodes",
  "metric.edges": "Edges",
  "metric.artifacts": "Artifacts",
  "graph.reasoningSubtitle": "Trace deductions among evidence, hypotheses, vulnerabilities, and exploits.",
  "graph.operationSubtitle": "Map the attack surface across hosts, services, endpoints, parameters, and credentials.",
  "graph.taskSubtitle": "View scope, goals, and tasks as a tree; milestones and blockers stay with their tasks.",
  "graph.searchPlaceholder": "Search node name, ID, or type",
  "graph.nodeType": "Node type",
  "graph.edgeType": "Relationship type",
  "graph.zoomOut": "Zoom out",
  "graph.zoomIn": "Zoom in",
  "graph.fit": "Fit canvas",
  "graph.relayout": "Run layout again",
  "graph.clearSelection": "Clear selection",
  "graph.nodeList": "Graph node list",
  "graph.nodes": "Nodes",
  "graph.noMatchingNodes": "No matching nodes",
  "graph.noVisibleNodes": "No nodes match the current filters",
  "graph.counts": "{nodes} nodes · {edges} {relations}",
  "graph.treeRelations": "tree relationships",
  "graph.relations": "relationships",
  "graph.milestones": "{value} milestones",
  "graph.blockers": "{value} blockers",
  "trace.all": "All",
  "trace.newestFirst": "Newest first",
  "trace.chronological": "Chronological",
  "trace.empty": "No trace events match the current filter",
  "trace.decision": "Decision",
  "trace.observation": "Observation",
  "trace.next": "Next",
  "trace.eventChain": "Event chain",
  "trace.noSummary": "No reasoning summary is available for this step.",
  "trace.action": "Action",
  "trace.noAction": "This step did not invoke an external tool.",
  "trace.expandDetails": "Expand execution details",
  "trace.aggregatedEvent": "View aggregated event",
  "trace.rawEvent": "View raw event",
  "trace.recordedIntent": "Agent thought",
  "trace.structuredIntent": "Reasoning basis",
  "trace.derivedIntent": "Action purpose",
  "trace.toolFailed": "Tool execution failed",
  "trace.noToolOutput": "No tool output",
  "startRun.title": "Start New Run",
  "startRun.goal": "Goal",
  "startRun.goalRequired": "Enter a goal",
  "startRun.goalPlaceholder": "Example: test the authorized target http://10.0.x.x and find all flags",
  "startRun.scope": "Authorized scope",
  "startRun.scopeRequired": "Enter the authorized scope",
  "startRun.scopePlaceholder": "Example: 10.0.0.0/24,baidu.com,*.example.com",
  "startRun.maxMinutes": "Maximum runtime (minutes)",
  "startRun.parallelTasks": "Parallel tasks",
  "startRun.plannerCycles": "Maximum consecutive no-progress Planner cycles",
  "resize.navigation": "Resize navigation",
  "resize.inspector": "Resize inspector",
  "resize.title": "{label}; double-click to restore the default width",
  "connections.description": "Managed SSH/Chisel routes can reconnect in active and historical runs; sessions and raw connections are read-only.",
  "connections.empty": "No connections for this runtime",
  "connections.managed": "controllable",
  "connections.unmanaged": "read-only",
  "connections.desired": "desired",
  "connections.available": "available",
  "connections.unavailable": "unavailable",
  "connections.heartbeat": "Heartbeat",
  "connections.error": "Error",
  "connections.viewGraph": "View in status graph",
  "connections.graph": "Status graph",
  "connections.reconnect": "Reconnect",
  "connections.forget": "Forget route",
  "connections.forgetConfirm": "Permanently forget this route?",
  "status.live": "Live",
  "status.degraded": "Degraded",
  "status.stale": "Stale",
  "status.closed": "Closed",
  "status.running": "Running",
  "status.stopped": "Stopped",
  "status.completed": "Completed",
  "status.blocked": "Blocked",
  "status.pending": "Pending",
  "status.failed": "Failed",
  "inspector.currentStep": "Current Step",
  "inspector.nodeDetails": "Node Details",
  "inspector.selectTrace": "Select a trace event to inspect it",
  "inspector.summarySource": "Summary source",
  "inspector.publicOutput": "Agent public output",
  "inspector.structuredReason": "Structured rationale",
  "inspector.derivedPurpose": "System-derived purpose",
  "inspector.action": "Action",
  "inspector.noExternalAction": "No external action",
  "inspector.stage": "Stage",
  "inspector.event": "Event",
  "inspector.task": "Task",
  "inspector.time": "Time",
  "inspector.commandDetails": "Command details",
  "inspector.noArtifact": "No linked artifacts",
  "inspector.aggregatedEvent": "Aggregated event",
  "inspector.rawEvent": "Raw event",
  "inspector.loadingContent": "Loading content…",
  "inspector.loadContentFailed": "Could not load full content: {error}",
  "inspector.truncatedContent": " (content too large; showing the beginning only)",
  "inspector.selectNode": "Select a graph node to inspect its properties and relationships",
  "inspector.milestones": "Milestones {value}",
  "inspector.blockers": "Blockers {value}",
  "inspector.noMilestones": "No milestones",
  "inspector.noBlockers": "No blockers",
  "inspector.evidence": "Evidence",
  "inspector.evidenceCount": "{value} evidence items",
  "inspector.noRefs": "No linked references",
  "inspector.incoming": "Incoming {value}",
  "inspector.outgoing": "Outgoing {value}",
  "inspector.noRelations": "No relationships",
  "inspector.taskQueue": "Task Queue · {value}",
  "inspector.noTasks": "No tasks",
  "traffic.filters": "Traffic filters",
  "traffic.methodFilter": "Method filter",
  "traffic.hostFilter": "Host filter",
  "traffic.statusFilter": "Status filter",
  "traffic.taskRefFilter": "Task ref filter",
  "traffic.runRefFilter": "Run ref filter",
  "traffic.modeFilter": "Mode filter",
  "traffic.errorFilter": "Error filter",
  "traffic.onlyErrors": "Errors only",
  "traffic.noErrors": "No errors",
  "traffic.refresh": "Refresh traffic",
  "traffic.empty": "No matching traffic records",
  "traffic.pageSize": "Up to {value} per page",
  "traffic.selectExchange": "Select exchange {value}",
  "traffic.unknownHost": "unknown host",
  "traffic.requestObserved": "Request {captured} / {observed} observed",
  "traffic.responseObserved": "Response {captured} / {observed} observed",
  "traffic.capturedObserved": "{captured} captured / {observed} observed",
  "traffic.inspector": "TRAFFIC INSPECTOR",
  "traffic.exchangeDetails": "Exchange Details",
  "traffic.selectRecord": "Select a traffic record to inspect it",
  "traffic.started": "Started",
  "traffic.completed": "Completed",
  "traffic.duration": "Duration",
  "traffic.protocol": "Protocol",
  "traffic.mode": "Mode",
  "traffic.requestBytes": "Request bytes",
  "traffic.responseBytes": "Response bytes",
  "traffic.error": "Error",
  "traffic.requestHeaders": "Request Headers",
  "traffic.responseHeaders": "Response Headers",
  "traffic.requestBody": "Request Body",
  "traffic.responseBody": "Response Body",
  "traffic.headersTruncated": "Headers were truncated{reason}",
  "traffic.noHeaders": "No headers recorded",
  "traffic.displayFormat": "{side} display format",
  "traffic.loadingOnDemand": "Loading on demand…",
  "traffic.bodyReadFailed": "Body could not be read; it may be evicted or too large: {error}",
  "traffic.loadBody": "Load body (maximum 256 KiB)",
  "traffic.bodyTruncated": "Showing only the captured body portion (truncated{reason})",
  "traffic.replayAdminOnly": "Only administrators can send replays; analysts can inspect the original exchange.",
  "traffic.editReplay": "Edit and Replay",
  "traffic.replayMethod": "Replay method",
  "traffic.replayUrl": "Replay URL",
  "traffic.replayHeaderName": "Replay header name {value}",
  "traffic.replayHeaderValue": "Replay header value {value}",
  "traffic.replayBody": "Replay body",
  "traffic.deleteHeader": "Delete header {value}",
  "traffic.addHeader": "Add header",
  "traffic.editedBody": "The edited body will be sent",
  "traffic.sourceBody": "Body unchanged; sidecar will use the complete source body",
  "traffic.prepareSend": "Prepare to send",
  "traffic.confirmReplay": "Confirm Replay",
  "traffic.confirmSend": "Send Replay",
  "traffic.replayWarning": "Replay may contain sensitive headers and body data",
  "traffic.replayWarningDescription": "Confirm that you are authorized to send this request. Sensitive values are not written to URLs, localStorage, or frontend logs.",
  "traffic.headersCount": "{value} items (may include Authorization/Cookie)",
  "traffic.bodyOverride": "{value} characters ({mode} override)",
  "traffic.fullSourceBody": "Use complete source body (no override)",
  "traffic.referenceChain": "Reference Chain",
  "traffic.noReferenceChain": "No task/run/route/session/connect references",
  "traffic.bodyAvailable": "Body not loaded; click to load on demand, up to 256 KiB.",
  "traffic.bodyEvicted": "Body has been evicted from capture storage.",
  "traffic.bodyUnavailableTruncated": "Body is too large or truncated and has no readable reference{reason}.",
  "traffic.bodyNoBytes": "Body not captured: no body bytes were observed in this direction.",
  "traffic.bodyNotCaptured": "Body not captured (capture state: {state}).",
  "traffic.invalidUrl": "Invalid URL",
  "traffic.tcpReplayUnavailable": "TCP traffic can be inspected but cannot be replayed as HTTP",
  "api.csrfUnavailable": "Unable to obtain CSRF token",
  "dashboard.sessionsFailed": "Failed to load sessions: {error}",
  "dashboard.runtimeFailed": "Failed to load runtime state: {error}"
} satisfies Record<keyof typeof zh, string>;

export type TranslationKey = keyof typeof zh;
type Variables = Record<string, string | number>;

const STORAGE_KEY = "luanniao-locale";
let currentLocale: Locale = "zh-CN";

function navigatorLocale(): Locale {
  return typeof navigator !== "undefined" && navigator.language.toLowerCase().startsWith("en") ? "en-US" : "zh-CN";
}

export function readStoredLocale(): Locale {
  if (typeof localStorage === "undefined") return navigatorLocale();
  const stored = localStorage.getItem(STORAGE_KEY);
  return stored === "zh-CN" || stored === "en-US" ? stored : navigatorLocale();
}

export function getLocale(): Locale {
  return currentLocale;
}

export function translate(key: TranslationKey, variables?: Variables, locale: Locale = currentLocale): string {
  const template = locale === "en-US" ? en[key] : zh[key];
  return variables ? template.replace(/\{(\w+)\}/g, (match, name: string) => variables[name] === undefined ? match : String(variables[name])) : template;
}

export function formatDateTime(value?: string | number | Date, locale: Locale = currentLocale): string {
  if (value === undefined) return "-";
  const date = value instanceof Date ? value : new Date(value);
  return Number.isFinite(date.getTime()) ? new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "medium", hour12: false }).format(date) : "-";
}

export function formatRelativeTime(value?: string | number | Date, locale: Locale = currentLocale, now = Date.now()): string {
  if (value === undefined) return "-";
  const time = (value instanceof Date ? value : new Date(value)).getTime();
  if (!Number.isFinite(time)) return "-";
  const diff = now - time;
  if (diff < 60_000) return translate("common.justNow", undefined, locale);
  if (diff < 3_600_000) return translate("common.minutesAgo", { value: Math.floor(diff / 60_000) }, locale);
  if (diff < 86_400_000) return translate("common.hoursAgo", { value: Math.floor(diff / 3_600_000) }, locale);
  return translate("common.daysAgo", { value: Math.floor(diff / 86_400_000) }, locale);
}

export function formatNumber(value: number, locale: Locale = currentLocale, options?: Intl.NumberFormatOptions): string {
  return new Intl.NumberFormat(locale, options).format(value);
}

export function formatBytes(value: number, locale: Locale = currentLocale): string {
  if (value >= 1024 * 1024) return `${formatNumber(value / (1024 * 1024), locale, { maximumFractionDigits: 1 })} MB`;
  if (value >= 1024) return `${formatNumber(value / 1024, locale, { maximumFractionDigits: 1 })} KB`;
  return `${formatNumber(value, locale)} B`;
}

export function formatDuration(value: number, locale: Locale = currentLocale): string {
  return value >= 1000 ? `${formatNumber(value / 1000, locale, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} s` : `${formatNumber(value, locale)} ms`;
}

interface LanguageContextValue {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  toggleLocale: () => void;
  t: (key: TranslationKey, variables?: Variables) => string;
  formatDate: (value?: string | number | Date) => string;
  formatRelative: (value?: string | number | Date) => string;
  formatNumber: (value: number, options?: Intl.NumberFormatOptions) => string;
  formatBytes: (value: number) => string;
  formatDuration: (value: number) => string;
}

const defaultContext: LanguageContextValue = {
  locale: "zh-CN",
  setLocale: () => undefined,
  toggleLocale: () => undefined,
  t: (key, variables) => translate(key, variables, "zh-CN"),
  formatDate: (value) => formatDateTime(value, "zh-CN"),
  formatRelative: (value) => formatRelativeTime(value, "zh-CN"),
  formatNumber: (value, options) => formatNumber(value, "zh-CN", options),
  formatBytes: (value) => formatBytes(value, "zh-CN"),
  formatDuration: (value) => formatDuration(value, "zh-CN")
};

const LanguageContext = createContext<LanguageContextValue>(defaultContext);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(readStoredLocale);

  const setLocale = useCallback((next: Locale) => {
    currentLocale = next;
    localStorage.setItem(STORAGE_KEY, next);
    setLocaleState(next);
  }, []);
  const toggleLocale = useCallback(() => setLocale(locale === "zh-CN" ? "en-US" : "zh-CN"), [locale, setLocale]);

  useEffect(() => {
    currentLocale = locale;
    document.documentElement.lang = locale;
    document.title = translate("app.title", undefined, locale);
  }, [locale]);

  const value = useMemo<LanguageContextValue>(() => ({
    locale,
    setLocale,
    toggleLocale,
    t: (key, variables) => translate(key, variables, locale),
    formatDate: (input) => formatDateTime(input, locale),
    formatRelative: (input) => formatRelativeTime(input, locale),
    formatNumber: (input, options) => formatNumber(input, locale, options),
    formatBytes: (input) => formatBytes(input, locale),
    formatDuration: (input) => formatDuration(input, locale)
  }), [locale, setLocale, toggleLocale]);

  return <LanguageContext.Provider value={value}><ConfigProvider locale={locale === "zh-CN" ? zhCN : enUS} theme={appTheme}>{children}</ConfigProvider></LanguageContext.Provider>;
}

export function useLanguage(): LanguageContextValue {
  return useContext(LanguageContext);
}

export const appTheme = {
  token: {
    colorPrimary: "#2563eb",
    colorInfo: "#2563eb",
    colorBgLayout: "#f5f7fb",
    colorBgContainer: "#ffffff",
    colorText: "#172033",
    colorTextSecondary: "#657187",
    colorBorder: "#dfe5ee",
    borderRadius: 8,
    fontFamily: '"Avenir Next", "PingFang SC", "Microsoft YaHei", sans-serif'
  },
  components: {
    Button: { controlHeight: 34 },
    Input: { controlHeight: 34 },
    Menu: { itemBorderRadius: 5, itemHeight: 42, itemMarginInline: 10 }
  }
};
