import { sqliteTable, text, integer, real, primaryKey, index } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';

// ===== BetterAuth Tables (auto-generated by better-auth CLI) =====
export const user = sqliteTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: integer('email_verified', { mode: 'boolean' }).default(false).notNull(),
  image: text('image'),
  // Admin plugin fields (better-auth/plugins/admin)
  role: text('role').notNull().default('user'),
  banned: integer('banned', { mode: 'boolean' }).default(false),
  banReason: text('ban_reason'),
  banExpires: integer('ban_expires', { mode: 'timestamp_ms' }),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => new Date())
    .notNull(),
});

export const session = sqliteTable('session', {
  id: text('id').primaryKey(),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
  token: text('token').notNull().unique(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .$onUpdate(() => new Date())
    .notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
}, (table) => [index('session_userId_idx').on(table.userId)]);

export const account = sqliteTable('account', {
  id: text('id').primaryKey(),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: integer('access_token_expires_at', { mode: 'timestamp_ms' }),
  refreshTokenExpiresAt: integer('refresh_token_expires_at', { mode: 'timestamp_ms' }),
  scope: text('scope'),
  password: text('password'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .$onUpdate(() => new Date())
    .notNull(),
}, (table) => [index('account_userId_idx').on(table.userId)]);

export const verification = sqliteTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => new Date())
    .notNull(),
}, (table) => [index('verification_identifier_idx').on(table.identifier)]);

// ===== Company Memberships (multi-user authorization) =====
export const companyMemberships = sqliteTable('company_memberships', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  companyId: text('company_id')
    .notNull()
    .references(() => companies.id, { onDelete: 'cascade' }),
  role: text('role', { enum: ['owner', 'admin', 'member'] })
    .notNull()
    .default('member'),
  invitedAt: text('invited_at'),
  joinedAt: text('joined_at')
    .default(sql`(datetime('now'))`),
  inviteToken: text('invite_token').unique(),
}, (table) => [
  index('membership_user_idx').on(table.userId),
  index('membership_company_idx').on(table.companyId),
  index('membership_token_idx').on(table.inviteToken),
]);

// ===== Benutzer (legacy — will be migrated to auth_users) =====
export const users = sqliteTable('benutzer', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  passwordHash: text('passwort_hash').notNull(),
  role: text('rolle', { enum: ['admin', 'mitglied'] }).notNull().default('mitglied'),
  oauthProvider: text('oauth_provider'),
  oauthId: text('oauth_id'),
  createdAt: text('erstellt_am').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
});

// ===== Unternehmen (ehem. Firmen) =====
export const companies = sqliteTable('unternehmen', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  description: text('beschreibung'),
  goal: text('ziel'),
  workDir: text('work_dir'),  // absolute path to project workspace — inherited by all agents
  status: text('status', { enum: ['active', 'paused', 'archived'] }).notNull().default('active'),
  createdAt: text('erstellt_am').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
});

// ===== Experten (Agenten, ehem. Mitarbeiter) =====
export const agents = sqliteTable('experten', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  role: text('rolle').notNull(),
  title: text('titel'),
  status: text('status', { enum: ['active', 'paused', 'idle', 'running', 'error', 'terminated'] }).notNull().default('idle'),
  reportsTo: text('reports_to').references((): any => agents.id),
  skills: text('faehigkeiten'),
  connectionType: text('verbindungs_typ', { enum: ['claude', 'claude-code', 'anthropic', 'openai', 'openrouter', 'google', 'moonshot', 'poe', 'ollama', 'ollama_cloud', 'codex', 'codex-cli', 'gemini-cli', 'kimi-cli', 'cursor', 'http', 'bash', 'ceo', 'custom', 'openclaw'] }).notNull().default('openrouter'),
  connectionConfig: text('verbindungs_config'), // JSON string
  avatar: text('avatar'),
  avatarColor: text('avatar_farbe').notNull().default('#23CDCA'),
  monthlyBudgetCent: integer('budget_monat_cent').notNull().default(0),
  monthlySpendCent: integer('verbraucht_monat_cent').notNull().default(0),
  lastCycle: text('letzter_zyklus'),
  autoCycleIntervalSec: integer('zyklus_intervall_sek').default(300),
  autoCycleActive: integer('zyklus_aktiv', { mode: 'boolean' }).default(false),
  isOrchestrator: integer('is_orchestrator', { mode: 'boolean' }).default(false),
  systemPrompt: text('system_prompt'),
  advisorId: text('advisor_id').references((): any => agents.id),
  advisorStrategy: text('advisor_strategy', { enum: ['none', 'planning', 'native'] }).notNull().default('none'),
  advisorConfig: text('advisor_config'), // JSON string
  // SOUL Document (Git-tracked agent identity)
  soulPath: text('soul_path'),    // absolute path to *.soul.md file (optional)
  soulVersion: text('soul_version'), // mtime-based hash or git-hash for cache invalidation
  messageCount: integer('nachrichten_count').notNull().default(0),
  createdAt: text('erstellt_am').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
});

// ===== Aufgaben =====
export const tasks = sqliteTable('aufgaben', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id, { onDelete: 'cascade' }),
  title: text('titel').notNull(),
  description: text('beschreibung'),
  status: text('status', { enum: ['backlog', 'todo', 'in_progress', 'in_review', 'done', 'blocked', 'cancelled'] }).notNull().default('backlog'),
  priority: text('prioritaet', { enum: ['critical', 'high', 'medium', 'low'] }).notNull().default('medium'),
  assignedTo: text('zugewiesen_an').references(() => agents.id),
  createdBy: text('erstellt_von'), // expert ID or 'board'
  parentId: text('parent_id').references((): any => tasks.id),
  projectId: text('projekt_id'),
  goalId: text('ziel_id'),
  // Issue-Execution-Lock (verhindert parallele Ausführung am selben Issue)
  executionRunId: text('execution_run_id'), // FK zu workCycles.id
  executionAgentNameKey: text('execution_agent_name_key'), // normalized agent name
  executionLockedAt: text('execution_locked_at'),
  // Maximizer Mode: Budget-Limits ignorieren, Agent darf autonom eskalieren
  isMaximizerMode: integer('is_maximizer_mode', { mode: 'boolean' }).default(false),
  // Dependencies (für Task-Orchestrierung)
  blockedBy: text('blocked_by'),
  workspacePath: text('workspace_path'),
  startedAt: text('gestartet_am'),
  completedAt: text('abgeschlossen_am'),
  cancelledAt: text('abgebrochen_am'),
  createdAt: text('erstellt_am').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
}, (t) => ({
  idxZugewiesenAn:       index('aufgaben_zugewiesen_an_idx').on(t.assignedTo),
  idxUnternehmenStatus:  index('aufgaben_unternehmen_status_idx').on(t.companyId, t.status),
  idxExecutionLocked:    index('aufgaben_execution_locked_idx').on(t.executionLockedAt),
}));

// ===== Kommentare =====
export const comments = sqliteTable('kommentare', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id, { onDelete: 'cascade' }),
  taskId: text('aufgabe_id').notNull().references(() => tasks.id, { onDelete: 'cascade' }),
  authorAgentId: text('autor_expert_id').references(() => agents.id, { onDelete: 'set null' }),
  authorType: text('autor_typ', { enum: ['agent', 'board'] }).notNull().default('board'),
  content: text('inhalt').notNull(),
  createdAt: text('erstellt_am').notNull(),
});

// ===== Chat-Nachrichten =====
export const chatMessages = sqliteTable('chat_nachrichten', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id, { onDelete: 'cascade' }),
  agentId: text('expert_id').notNull().references(() => agents.id, { onDelete: 'cascade' }),
  vonExpertId: text('von_expert_id'), // sender expertId when agent→agent P2P
  threadId: text('thread_id'),        // meeting thread grouping
  senderType: text('absender_typ', { enum: ['board', 'agent', 'system'] }).notNull(),
  message: text('nachricht').notNull(),
  read: integer('gelesen', { mode: 'boolean' }).notNull().default(false),
  createdAt: text('erstellt_am').notNull(),
}, (t) => ({
  idxExpertGelesen: index('chat_nachrichten_expert_gelesen_idx').on(t.agentId, t.read),
  idxExpertAm:      index('chat_nachrichten_expert_am_idx').on(t.agentId, t.createdAt),
}));

// ===== Agenten-Meetings (Multi-Agent Koordination) =====
export const agentMeetings = sqliteTable('agenten_meetings', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  title: text('titel').notNull(),
  organizerAgentId: text('veranstalter_expert_id').notNull().references(() => agents.id),
  participantIds: text('teilnehmer_ids').notNull(), // JSON array of expert IDs
  responses: text('antworten').default('{}'),       // JSON map { agentId: "response" }
  status: text('status', { enum: ['running', 'completed', 'cancelled'] }).notNull().default('running'),
  result: text('ergebnis'),                       // final CEO synthesis
  createdAt: text('erstellt_am').notNull(),
  completedAt: text('abgeschlossen_am'),
});

// ===== Genehmigungen =====
export const approvals = sqliteTable('genehmigungen', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  type: text('typ', { enum: ['hire_expert', 'approve_strategy', 'budget_change', 'agent_action'] }).notNull(),
  title: text('titel').notNull(),
  description: text('beschreibung'),
  requestedBy: text('angefordert_von'), // expert ID
  status: text('status', { enum: ['pending', 'approved', 'rejected', 'cancelled'] }).notNull().default('pending'),
  payload: text('payload'), // JSON string
  decisionNote: text('entscheidungsnotiz'),
  decidedAt: text('entschieden_am'),
  createdAt: text('erstellt_am').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
  telegramChatId: text('telegram_chat_id'),
  telegramMessageId: integer('telegram_message_id'),
  notifiedAt: text('notified_at'),
});

// ===== Kostenbuchungen =====
export const costEntries = sqliteTable('kostenbuchungen', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id, { onDelete: 'cascade' }),
  agentId: text('expert_id').notNull().references(() => agents.id, { onDelete: 'cascade' }),
  taskId: text('aufgabe_id').references(() => tasks.id),
  provider: text('anbieter').notNull(), // 'openai', 'anthropic', etc.
  model: text('modell').notNull(),
  inputTokens: integer('input_tokens').notNull().default(0),
  outputTokens: integer('output_tokens').notNull().default(0),
  costCent: integer('kosten_cent').notNull(),
  timestamp: text('zeitpunkt').notNull(),
  createdAt: text('erstellt_am').notNull(),
});

// ===== Aktivitätsprotokoll =====
export const activityLog = sqliteTable('aktivitaetslog', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  actorType: text('akteur_typ', { enum: ['agent', 'board', 'system'] }).notNull(),
  actorId: text('akteur_id').notNull(),
  actorName: text('akteur_name'),
  action: text('aktion').notNull(),
  entityType: text('entitaet_typ').notNull(), // 'aufgabe', 'expert', 'companies', etc.
  entityId: text('entitaet_id').notNull(),
  details: text('details'), // JSON string
  createdAt: text('erstellt_am').notNull(),
});

// ===== Arbeitszyklen (Heartbeat-Läufe) =====
export const workCycles = sqliteTable('arbeitszyklen', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id, { onDelete: 'cascade' }),
  agentId: text('expert_id').notNull().references(() => agents.id, { onDelete: 'cascade' }),
  source: text('quelle', { enum: ['scheduler', 'manual', 'callback', 'assignment', 'automation'] }).notNull().default('manual'),
  status: text('status', { enum: ['queued', 'running', 'succeeded', 'failed', 'cancelled', 'timed_out', 'deferred'] }).notNull().default('queued'),
  command: text('befehl'), // command that was run
  output: text('ausgabe'), // stdout/stderr
  error: text('fehler'),
  startedAt: text('gestartet_am'),
  endedAt: text('beendet_am'),
  createdAt: text('erstellt_am').notNull(),
  // Heartbeat-specific fields (execution tracking)
  invocationSource: text('invocation_source'), // "on_demand", "timer", "assignment"
  triggerDetail: text('trigger_detail'), // "manual", "ping", "callback", "system"
  exitCode: integer('exit_code'),
  usageJson: text('usage_json'), // JSON: { inputTokens, outputTokens, costCents }
  resultJson: text('result_json'), // JSON: agent output
  sessionIdBefore: text('session_id_before'),
  sessionIdAfter: text('session_id_after'),
  contextSnapshot: text('context_snapshot'), // JSON: { issueId, wakeReason, etc. }
  retryOfRunId: text('retry_of_run_id').references((): any => workCycles.id),
});

// ===== Arbeitszyklen Archiv (aggregated daily stats before cleanup deletion) =====
export const workCyclesArchive = sqliteTable('arbeitszyklen_archiv', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  agentId: text('expert_id').notNull().references(() => agents.id),
  archiveDate: text('archiv_datum').notNull(),
  cycleCount: integer('zyklus_anzahl').notNull().default(0),
  successCount: integer('erfolgreich_anzahl').notNull().default(0),
  failedCount: integer('fehlgeschlagen_anzahl').notNull().default(0),
  cancelledCount: integer('abgebrochen_anzahl').notNull().default(0),
  avgDurationMs: integer('durchschnitt_dauer_ms').notNull().default(0),
  totalInputTokens: integer('gesamt_input_tokens').notNull().default(0),
  totalOutputTokens: integer('gesamt_output_tokens').notNull().default(0),
  totalCostCent: integer('gesamt_kosten_cent').notNull().default(0),
  modelsJson: text('modelle_json'), // JSON: { "claude-3-5": 12, "gpt-4": 3 }
  createdAt: text('erstellt_am').notNull(),
}, (t) => ({
  idxUnternehmenDatum: index('archiv_unternehmen_datum_idx').on(t.companyId, t.archiveDate),
  idxExpert: index('archiv_expert_idx').on(t.agentId, t.archiveDate),
}));

// ===== Task Checkpoints (Hermes-inspired) =====
export const taskCheckpoints = sqliteTable('task_checkpoints', {
  id: text('id').primaryKey(),
  taskId: text('task_id').notNull().references(() => tasks.id, { onDelete: 'cascade' }),
  runId: text('run_id').references(() => workCycles.id, { onDelete: 'set null' }),
  agentId: text('agent_id').notNull().references(() => agents.id, { onDelete: 'cascade' }),
  companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }),
  stateLabel: text('state_label', { enum: ['DONE', 'BLOCKED', 'NEEDS_INPUT', 'HANDOFF', 'IN_PROGRESS'] }).notNull(),
  filesChanged: text('files_changed'), // JSON array of paths
  commandsRun: text('commands_run'), // JSON array of commands
  result: text('result'),
  blocker: text('blocker'),
  nextAction: text('next_action'),
  createdAt: text('created_at').notNull(),
}, (t) => ({
  idxTask: index('checkpoint_task_idx').on(t.taskId),
  idxRun: index('checkpoint_run_idx').on(t.runId),
  idxAgent: index('checkpoint_agent_idx').on(t.agentId),
  idxCompany: index('checkpoint_company_idx').on(t.companyId),
}));

// ===== Learned Skills (auto-extracted from successful work cycles) =====
// Distinct from skillsLibrary (manually curated, broad categories).
// Learned skills are concrete recipes derived from a specific successful task,
// shared company-wide so other agents can reuse the pattern.
export const learnedSkills = sqliteTable('learned_skills', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id, { onDelete: 'cascade' }),
  sourceAgentId: text('source_agent_id').references(() => agents.id, { onDelete: 'set null' }),
  sourceTaskId: text('source_task_id').references(() => tasks.id, { onDelete: 'set null' }),
  sourceRunId: text('source_run_id').references(() => workCycles.id, { onDelete: 'set null' }),
  title: text('title').notNull(),                  // short label, e.g. "Stripe webhook handler"
  pattern: text('pattern').notNull(),              // when this applies, e.g. "tasks involving stripe webhook signature verification"
  recipe: text('recipe').notNull(),                // the actual reusable steps/output template
  keywords: text('keywords'),                      // JSON array, used for retrieval matching
  confidence: integer('confidence').notNull().default(50), // 0-100
  useCount: integer('use_count').notNull().default(0),
  lastUsedAt: text('last_used_at'),
  isPinned: integer('is_pinned', { mode: 'boolean' }).notNull().default(false),
  isDisabled: integer('is_disabled', { mode: 'boolean' }).notNull().default(false),
  extractedBy: text('extracted_by', { enum: ['heuristic', 'llm'] }).notNull().default('heuristic'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
}, (t) => ({
  idxCompany: index('learned_skills_company_idx').on(t.companyId),
  idxKeywordSearch: index('learned_skills_keywords_idx').on(t.companyId, t.isDisabled),
}));

// ===== Ziele =====
export const goals = sqliteTable('ziele', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  title: text('titel').notNull(),
  description: text('beschreibung'),
  level: text('ebene', { enum: ['company', 'team', 'agent', 'task'] }).notNull().default('company'),
  parentId: text('parent_id').references((): any => goals.id),
  ownerAgentId: text('eigentuemer_expert_id').references(() => agents.id),
  status: text('status', { enum: ['planned', 'active', 'achieved', 'cancelled'] }).notNull().default('planned'),
  progress: integer('fortschritt').notNull().default(0),
  createdAt: text('erstellt_am').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
});

// ===== Einstellungen =====
export const settings = sqliteTable('einstellungen', {
  key: text('schluessel').notNull(),
  companyId: text('unternehmen_id').notNull().default(''), // '' = global
  value: text('wert').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
}, (t) => ({
  pk: primaryKey({ columns: [t.key, t.companyId] }),
}));

// ===== Agent Wakeup Requests =====
export const agentWakeupRequests = sqliteTable('agent_wakeup_requests', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  agentId: text('expert_id').notNull().references(() => agents.id),
  source: text('source', { enum: ['timer', 'assignment', 'on_demand', 'automation'] }).notNull(),
  triggerDetail: text('trigger_detail'), // "manual", "ping", "callback", "system"
  reason: text('reason').notNull(), // why the wakeup was requested
  payload: text('payload'), // JSON: { issueId?, taskId?, wakeCommentId?, etc. }
  status: text('status', { enum: ['queued', 'claimed', 'completed', 'failed', 'deferred'] }).notNull().default('queued'),
  coalescedCount: integer('coalesced_count').notNull().default(0), // deduplication counter
  runId: text('run_id').references((): any => workCycles.id), // linked heartbeat run
  contextSnapshot: text('context_snapshot'), // JSON: { issueId?, source? }
  requestedAt: text('requested_at').notNull(),
  claimedAt: text('claimed_at'),
  finishedAt: text('finished_at'),
}, (t) => ({
  idxExpertStatus: index('wakeup_expert_status_idx').on(t.agentId, t.status),
  idxUnternehmenStatus: index('wakeup_unternehmen_status_idx').on(t.companyId, t.status),
}));

// ===== Routines (wiederkehrende Aufgaben) =====
export const routines = sqliteTable('routinen', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  title: text('titel').notNull(),
  description: text('beschreibung'),
  assignedTo: text('zugewiesen_an').references(() => agents.id),
  priority: text('prioritaet', { enum: ['critical', 'high', 'medium', 'low'] }).notNull().default('medium'),
  status: text('status', { enum: ['active', 'paused'] }).notNull().default('active'),
  concurrencyPolicy: text('concurrency_policy', { enum: ['coalesce_if_active', 'skip_if_active', 'always_enqueue'] }).notNull().default('coalesce_if_active'),
  catchUpPolicy: text('catch_up_policy', { enum: ['skip_missed', 'catch_up'] }).notNull().default('skip_missed'),
  variables: text('variablen'), // JSON: variable definitions
  lastExecutedAt: text('zuletzt_ausgefuehrt_am'),
  lastEnqueuedAt: text('zuletzt_enqueued_am'),
  createdAt: text('erstellt_am').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
});

// ===== Routine Trigger =====
export const routineTrigger = sqliteTable('routine_trigger', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id, { onDelete: 'cascade' }),
  routineId: text('routine_id').notNull().references(() => routines.id, { onDelete: 'cascade' }),
  kind: text('kind', { enum: ['schedule', 'webhook', 'api'] }).notNull(),
  active: integer('aktiv', { mode: 'boolean' }).notNull().default(true),
  cronExpression: text('cron_expression'), // for schedule triggers
  timezone: text('timezone').default('UTC'),
  nextExecutionAt: text('naechster_ausfuehrung_am'),
  lastFiredAt: text('zuletzt_gefeuert_am'),
  publicId: text('public_id'), // for webhook URLs
  secretId: text('secret_id'), // for webhook signing
  createdAt: text('erstellt_am').notNull(),
});

// ===== Routine Ausführungen =====
export const routineRuns = sqliteTable('routine_ausfuehrung', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id, { onDelete: 'cascade' }),
  routineId: text('routine_id').notNull().references(() => routines.id, { onDelete: 'cascade' }),
  triggerId: text('trigger_id').references(() => routineTrigger.id, { onDelete: 'cascade' }),
  source: text('quelle', { enum: ['schedule', 'manual', 'api', 'webhook'] }).notNull(),
  status: text('status', { enum: ['received', 'enqueued', 'completed', 'failed'] }).notNull().default('received'),
  payload: text('payload'), // JSON: trigger payload
  taskId: text('aufgabe_id').references(() => tasks.id), // linked issue created
  createdAt: text('erstellt_am').notNull(),
  completedAt: text('abgeschlossen_am'),
});

// ===== Work Products =====
export const workProducts = sqliteTable('work_products', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id, { onDelete: 'cascade' }),
  taskId: text('aufgabe_id').notNull().references(() => tasks.id, { onDelete: 'cascade' }),
  agentId: text('expert_id').notNull().references(() => agents.id, { onDelete: 'cascade' }),
  runId: text('run_id').references(() => workCycles.id),
  type: text('typ').notNull().default('file'), // file, text, url, directory
  name: text('name').notNull(),
  pfad: text('pfad'),
  content: text('inhalt'),
  sizeBytes: integer('groesse_bytes'),
  mimeTyp: text('mime_typ'),
  createdAt: text('erstellt_am').notNull(),
});

// ===== Projekte =====
export const projects = sqliteTable('projekte', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  name: text('name').notNull(),
  description: text('beschreibung'),
  status: text('status', { enum: ['aktiv', 'pausiert', 'abgeschlossen', 'archiviert'] }).notNull().default('aktiv'),
  priority: text('prioritaet', { enum: ['low', 'medium', 'high', 'critical'] }).notNull().default('medium'),
  goalId: text('ziel_id').references(() => goals.id),
  ownerAgentId: text('eigentuemer_id').references(() => agents.id),
  color: text('farbe').notNull().default('#23CDCB'),
  deadline: text('deadline'),
  progress: integer('fortschritt').notNull().default(0),
  whiteboardState: text('whiteboard_state'), // JSON: shared project whiteboard for agents
  workDir: text('work_dir'),  // per-project workspace path — overrides companies.workDir
  createdAt: text('erstellt_am').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
});

// ===== Agent Permissions =====
export const agentPermissions = sqliteTable('agent_permissions', {
  id: text('id').primaryKey(),
  agentId: text('expert_id').notNull().references(() => agents.id).unique(),
  darfAufgabenErstellen: integer('darf_aufgaben_erstellen', { mode: 'boolean' }).notNull().default(true),
  darfAufgabenZuweisen: integer('darf_aufgaben_zuweisen', { mode: 'boolean' }).notNull().default(false),
  darfGenehmigungAnfordern: integer('darf_genehmigungen_anfordern', { mode: 'boolean' }).notNull().default(true),
  darfGenehmigungEntscheiden: integer('darf_genehmigungen_entscheiden', { mode: 'boolean' }).notNull().default(false),
  darfExpertenAnwerben: integer('darf_experten_anwerben', { mode: 'boolean' }).notNull().default(false),
  budgetLimitCent: integer('budget_limit_cent'),     // NULL = Firmen-Budget gilt
  erlaubtePfade: text('erlaubte_pfade'),             // JSON array of allowed paths, NULL = none
  erlaubteDomains: text('erlaubte_domains'),         // JSON array of allowed domains, NULL = none
  createdAt: text('erstellt_am').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
});

// ===== Glass Agent: Trace Events (real-time agent execution log) =====
export const traceEvents = sqliteTable('trace_ereignisse', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  agentId: text('expert_id').notNull().references(() => agents.id),
  runId: text('run_id'), // linked to workCycles.id
  type: text('typ').notNull(), // 'thinking' | 'action' | 'result' | 'error' | 'info'
  title: text('titel').notNull(),
  details: text('details'), // optional extra text
  createdAt: text('erstellt_am').notNull(),
}, (t) => ({
  idxExpertAm: index('trace_expert_am_idx').on(t.agentId, t.createdAt),
  idxUnternehmenAm: index('trace_unternehmen_am_idx').on(t.companyId, t.createdAt),
}));

// ===== Skill Library (RAG-lite: Markdown knowledge base per company) =====
export const skillsLibrary = sqliteTable('skills_library', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  name: text('name').notNull(),
  description: text('beschreibung'),
  content: text('inhalt').notNull(), // Full markdown content
  tags: text('tags'), // JSON array of tags for keyword matching
  createdBy: text('erstellt_von'), // user id oder 'learning-loop' für auto-generierte
  // Learning Loop Felder
  confidence: integer('konfidenz').notNull().default(50), // 0-100, startet bei 50
  uses: integer('nutzungen').notNull().default(0), // Wie oft der Skill verwendet wurde
  successes: integer('erfolge').notNull().default(0), // Erfolgreiche Nutzungen
  source: text('quelle', { enum: ['manuell', 'learning-loop', 'clipmart'] }).notNull().default('manuell'),
  remoteRef: text('remote_ref'), // Remote-Quelle (GitHub URL etc.)
  createdAt: text('erstellt_am').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
});


// ===== Expert <-> Skill Library (assignment) =====
export const agentSkills = sqliteTable('experten_skills', {
  id: text('id').primaryKey(),
  agentId: text('expert_id').notNull().references(() => agents.id),
  skillId: text('skill_id').notNull().references(() => skillsLibrary.id),
  createdAt: text('erstellt_am').notNull(),
});

// ===== Agent Trust Scores (Reputation System) =====
export const agentTrustScores = sqliteTable('agent_trust_scores', {
  id: text('id').primaryKey(),
  subjectAgentId: text('subject_expert_id').notNull().references(() => agents.id),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  evaluatorAgentId: text('evaluator_expert_id').notNull(),
  score: integer('score').notNull().default(50),
  reliability: integer('zuverlaessigkeit').notNull().default(50),
  quality: integer('qualitaet').notNull().default(50),
  communication: integer('kommunikation').notNull().default(50),
  collaboration: integer('zusammenarbeit').notNull().default(50),
  ratingCount: integer('bewertungs_count').notNull().default(0),
  trend: text('trend', { enum: ['rising', 'falling', 'stable'] }).notNull().default('stable'),
  historyJson: text('verlauf_json'), // JSON array of { date, score, taskId, success }
  lastUpdated: text('letzte_aktualisierung').notNull(),
  createdAt: text('erstellt_am').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
});

// ===== Agent Votes (Consensus System) =====
export const agentVotes = sqliteTable('agent_votes', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  contextId: text('context_id').notNull(),
  contextType: text('context_typ', { enum: ['meeting', 'task', 'decision', 'proposal'] }).notNull(),
  agentId: text('expert_id').notNull().references(() => agents.id),
  vote: integer('vote').notNull(), // -1 = reject, 0 = abstain, 1 = approve
  weightedVote: integer('gewichteter_vote'),
  reason: text('begruendung'),
  proposalText: text('proposal_text'),
  createdAt: text('erstellt_am').notNull(),
});

// ===== Agent Capabilities (Contract-Net Bidding) =====
export const agentCapabilities = sqliteTable('agent_capabilities', {
  id: text('id').primaryKey(),
  agentId: text('expert_id').notNull().references(() => agents.id),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  capabilitiesJson: text('capabilities_json').notNull(), // JSON { domains, tools, languages, complexity }
  quelle: text('quelle').notNull().default('manual'), // auto-extracted, manual, hybrid
  konfidenz: integer('konfidenz').notNull().default(50),
  letzteAktualisierung: text('letzte_aktualisierung'),
  createdAt: text('erstellt_am').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
});

// ===== Contract Net Bids (Task Auction System) =====
export const contractNetBids = sqliteTable('contract_net_bids', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  taskId: text('aufgabe_id').notNull().references(() => tasks.id),
  bidderAgentId: text('bidder_expert_id').notNull().references(() => agents.id),
  bidScore: integer('bid_score').notNull().default(0),
  reason: text('begruendung'),
  estimatedMinutes: integer('estimated_minutes'),
  status: text('status', { enum: ['pending', 'accepted', 'rejected', 'expired'] }).notNull().default('pending'),
  announcerAgentId: text('announcer_expert_id').references(() => agents.id),
  createdAt: text('erstellt_am').notNull(),
  completedAt: text('abgeschlossen_am'),
});

// ===== Memory (nativer Gedächtnis-Palast — ersetzt Python MCP-Server) =====

// Wings: Jeder Agent hat einen isolierten Wing
export const palaceWings = sqliteTable('palace_wings', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  agentId: text('expert_id').notNull().references(() => agents.id),
  name: text('name').notNull(), // z.B. "ceo", "cto" (lowercase, underscored)
  createdAt: text('erstellt_am').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
});

// Drawers: Speichereinheiten innerhalb eines Wings
export const palaceDrawers = sqliteTable('palace_drawers', {
  id: text('id').primaryKey(),
  wingId: text('wing_id').notNull().references(() => palaceWings.id),
  room: text('room').notNull(), // z.B. "notizen", "chat_history", "task_results"
  content: text('inhalt').notNull(),
  createdAt: text('erstellt_am').notNull(),
});

// Diary: AAAK-Tagebucheinträge pro Wing
export const palaceDiary = sqliteTable('palace_diary', {
  id: text('id').primaryKey(),
  wingId: text('wing_id').notNull().references(() => palaceWings.id),
  datum: text('datum').notNull(), // ISO date (YYYY-MM-DD)
  thought: text('thought'),
  action: text('action'),
  knowledge: text('knowledge'),
  createdAt: text('erstellt_am').notNull(),
});

// Knowledge Graph: Temporale Fakten (Subject-Predicate-Object Tripel)
export const palaceKg = sqliteTable('palace_kg', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  subject: text('subject').notNull(),
  predicate: text('predicate').notNull(),
  object: text('object').notNull(),
  validFrom: text('valid_from'), // ISO date — wann wurde dieser Fakt gültig
  validUntil: text('valid_until'), // ISO date — wann wurde er ungültig (NULL = noch gültig)
  createdBy: text('erstellt_von'), // expert_id oder 'system'
  createdAt: text('erstellt_am').notNull(),
}, (t) => ({
  idxSubjectValid: index('kg_subject_valid_idx').on(t.subject, t.validUntil),
  idxUnternehmenSubject: index('kg_unternehmen_subject_idx').on(t.companyId, t.subject),
}));

// ===== Context Summaries (iterative Kompression) =====
export const palaceSummaries = sqliteTable('palace_summaries', {
  id: text('id').primaryKey(),
  agentId: text('expert_id').notNull().references(() => agents.id),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  content: text('inhalt').notNull(), // Strukturierte Zusammenfassung (Goal, Progress, Decisions, etc.)
  version: integer('version').notNull().default(1), // Wird bei jedem Update inkrementiert
  komprimierteTurns: integer('komprimierte_turns').notNull().default(0),
  createdAt: text('erstellt_am').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
});

// ===== Budget Policies (Scope-Hierarchie + Incidents) =====
export const budgetPolicies = sqliteTable('budget_policies', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  scope: text('scope', { enum: ['company', 'project', 'agent'] }).notNull(),
  scopeId: text('scope_id').notNull(), // unternehmenId, projektId oder expertId
  limitCent: integer('limit_cent').notNull(),
  fenster: text('fenster', { enum: ['monatlich', 'lifetime'] }).notNull().default('monatlich'),
  warnProzent: integer('warn_prozent').notNull().default(80),
  hardStop: integer('hard_stop', { mode: 'boolean' }).notNull().default(true),
  active: integer('aktiv', { mode: 'boolean' }).notNull().default(true),
  createdAt: text('erstellt_am').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
});

export const budgetIncidents = sqliteTable('budget_incidents', {
  id: text('id').primaryKey(),
  policyId: text('policy_id').notNull().references(() => budgetPolicies.id),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  type: text('typ', { enum: ['warnung', 'hard_stop'] }).notNull(),
  beobachteterBetrag: integer('beobachteter_betrag').notNull(), // in Cent
  limitBetrag: integer('limit_betrag').notNull(),
  status: text('status', { enum: ['offen', 'behoben', 'ignoriert'] }).notNull().default('offen'),
  behobeneAm: text('behoben_am'),
  createdAt: text('erstellt_am').notNull(),
});

// ===== Execution Workspaces (isolierte Task-Umgebungen) =====
export const executionWorkspaces = sqliteTable('execution_workspaces', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  taskId: text('aufgabe_id').references(() => tasks.id),
  agentId: text('expert_id').references(() => agents.id),
  pfad: text('pfad').notNull(), // Absoluter Pfad zum Workspace-Verzeichnis
  branchName: text('branch_name'), // Git-Branch (wenn git-aware)
  basePfad: text('base_pfad'), // Basis-Verzeichnis von dem abgeleitet
  abgeleitetVon: text('abgeleitet_von').references((): any => executionWorkspaces.id),
  status: text('status', { enum: ['offen', 'aktiv', 'geschlossen', 'aufgeraeumt'] }).notNull().default('offen'),
  metadaten: text('metadaten'), // JSON für Erweiterbarkeit
  geoeffnetAm: text('geoeffnet_am').notNull(),
  geschlossenAm: text('geschlossen_am'),
  aufgeraeumtAm: text('aufgeraeumt_am'),
  createdAt: text('erstellt_am').notNull(),
});

// ===== Issue Relations (Blocking-Graph für Task-Dependencies) =====
export const issueRelations = sqliteTable('issue_relations', {
  id: text('id').primaryKey(),
  sourceId: text('quell_id').notNull().references(() => tasks.id), // Die blockierende Aufgabe
  targetId: text('ziel_id').notNull().references(() => tasks.id),   // Die blockierte Aufgabe
  type: text('typ', { enum: ['blocks'] }).notNull().default('blocks'),
  createdBy: text('erstellt_von'), // expertId oder 'board'
  createdAt: text('erstellt_am').notNull(),
});

// ===== OpenClaw Gateway Tokens =====
// Per-company invite tokens that OpenClaw agents use to register themselves.
export const openclawTokens = sqliteTable('openclaw_tokens', {
  id:            text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  token:         text('token').notNull().unique(),
  description:  text('beschreibung'),
  createdAt:    text('erstellt_am').notNull(),
  letzterJoin:   text('letzter_join'),
});

// ===== Expert Config History (rollback snapshots) =====
// ===== CEO Decision Log — persistenter roter Faden für den Orchestrator =====
// Jeder Planungszyklus schreibt einen Eintrag; beim nächsten Zyklus wird der
// letzte Eintrag in den Kontext geladen → kein Amnesie-Problem mehr.
export const ceoDecisionLog = sqliteTable('ceo_decision_log', {
  id: text('id').primaryKey(),
  agentId: text('expert_id').notNull().references(() => agents.id),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  runId: text('run_id').notNull(),
  createdAt: text('erstellt_am').notNull(),
  // Structured decision snapshot
  focusSummary: text('focus_summary').notNull(),      // 1-2 sentences: what the CEO decided to focus on
  actionsJson: text('actions_json').notNull(),          // JSON array of actions taken this cycle
  goalsSnapshot: text('goals_snapshot'),               // JSON: goal titles + progress at decision time
  pendingTaskCount: integer('pending_task_count').notNull().default(0),
  teamSummary: text('team_summary'),                   // "Anna(3 tasks), Bob(1 task)"
}, (t) => ({
  idxCeoLog: index('ceo_decision_log_expert_idx').on(t.agentId, t.createdAt),
}));

export const agentConfigHistory = sqliteTable('expert_config_history', {
  id: text('id').primaryKey(),
  agentId: text('expert_id').notNull().references(() => agents.id),
  changedAt: text('changed_at').notNull(),
  changedBy: text('changed_by'), // userId or 'system'
  configJson: text('config_json').notNull(), // full snapshot of changed fields
  note: text('note'),
}, (t) => ({
  idxExpertHistory: index('expert_config_history_expert_idx').on(t.agentId, t.changedAt),
}));

// ===== Worker Nodes (Multi-Node Agent Worker Pool) =====
// Persistent registry of worker processes that can claim and run agent work.
// Workers authenticate via a shared token and send periodic heartbeats.
export const workerNodes = sqliteTable('worker_nodes', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),                 // human-readable
  hostname: text('hostname'),
  capabilities: text('capabilities').notNull(), // JSON string array: ['claude-code','bash','ollama']
  tokenHash: text('token_hash').notNull(),      // sha256 of auth token
  status: text('status', { enum: ['online', 'offline', 'disabled'] }).notNull().default('online'),
  maxConcurrency: integer('max_concurrency').notNull().default(1),
  activeRuns: integer('active_runs').notNull().default(0),
  totalRuns: integer('total_runs').notNull().default(0),
  lastHeartbeatAt: text('last_heartbeat_at'),
  registriertAm: text('registriert_am').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
}, (t) => ({
  idxStatus: index('worker_nodes_status_idx').on(t.status, t.lastHeartbeatAt),
}));

// ─── Semantic Memory ─────────────────────────────────────────────────────────
export const memoryEmbeddings = sqliteTable('memory_embeddings', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull(),
  agentId: text('expert_id'),                    // which agent stored this
  source: text('quelle').notNull().default('manual'), // source: 'manual', 'task', 'chat', 'skill'
  quelleId: text('quelle_id'),                    // ID of source task/chat/skill
  chunkText: text('chunk_text').notNull(),        // the actual text content
  embeddingJson: text('embedding_json').notNull(), // JSON array of floats
  model: text('model').notNull().default('openai/text-embedding-3-small'),
  tokenCount: integer('token_count').default(0),
  charCount: integer('char_count').notNull().default(0),
  tags: text('tags'),                             // comma-separated tags
  createdAt: text('erstellt_am').notNull(),
}, (t) => ({
  idxUnternehmen: index('mem_emb_unternehmen_idx').on(t.companyId),
  idxExpert: index('mem_emb_expert_idx').on(t.agentId),
  idxQuelle: index('mem_emb_quelle_idx').on(t.source),
}));

// Memory Conflicts (actor-aware conflict detection)
export const memoryConflicts = sqliteTable('memory_conflicts', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull().references(() => companies.id),
  conflictingTriplesJson: text('conflicting_triples_json').notNull(),
  conflictTyp: text('conflict_typ', { enum: ['contradiction', 'outdated', 'ambiguity', 'stale'] }).notNull(),
  beschreibung: text('beschreibung').notNull(),
  status: text('status', { enum: ['open', 'resolved', 'ignored'] }).notNull().default('open'),
  resolution: text('resolution'),
  resolvedByAgentId: text('resolved_by_expert_id').references(() => agents.id),
  createdAt: text('erstellt_am').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
}, (t) => ({
  idxUnternehmenStatus: index('mem_conflict_unternehmen_status_idx').on(t.companyId, t.status),
}));

// ===== Agent-to-Agent Messages (A2A Message Bus) =====
export const agentMessages = sqliteTable('agent_messages', {
  id: text('id').primaryKey(),
  companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }),
  senderId: text('sender_id').notNull().references(() => agents.id, { onDelete: 'cascade' }),
  recipientId: text('recipient_id').references(() => agents.id, { onDelete: 'cascade' }),
  channel: text('channel'),
  threadId: text('thread_id'),
  type: text('type', { enum: ['direct', 'broadcast', 'channel', 'request', 'response'] }).notNull().default('direct'),
  payload: text('payload').notNull(), // JSON: { text, metadata?, urgency? }
  readAt: text('read_at'),
  createdAt: text('created_at').notNull(),
}, (t) => ({
  idxCompany: index('agent_msg_company_idx').on(t.companyId),
  idxSender: index('agent_msg_sender_idx').on(t.senderId),
  idxRecipient: index('agent_msg_recipient_idx').on(t.recipientId),
  idxThread: index('agent_msg_thread_idx').on(t.threadId),
  idxChannel: index('agent_msg_channel_idx').on(t.channel),
  idxRecipientRead: index('agent_msg_recipient_read_idx').on(t.recipientId, t.readAt),
}));

// ===== PR-VND-2: Vendor Performance, Compliance, Blacklist =====
export const vendorBankDetails = sqliteTable('vendor_bank_details', {
  id: text('id').primaryKey(),
  vendorId: text('vendor_id').notNull(),
  bankName: text('bank_name').notNull(),
  accountNumber: text('account_number').notNull(),
  accountName: text('account_name'),
  branch: text('branch'),
  swiftCode: text('swift_code'),
  currency: text('currency').default('KES'),
  isActive: integer('is_active').notNull().default(1),
  changedBy: text('changed_by'),
  changeReason: text('change_reason'),
  createdAt: text('erstellt_am').notNull(),
});

export const vendorPerformanceReviews = sqliteTable('vendor_performance_reviews', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull(),
  vendorId: text('vendor_id').notNull(),
  reviewPeriodStart: text('review_period_start').notNull(),
  reviewPeriodEnd: text('review_period_end').notNull(),
  reviewedBy: text('reviewed_by').notNull(),
  role: text('rolle').notNull().default('procurement'),
  deliveryScore: integer('delivery_score').default(0),
  qualityScore: integer('quality_score').default(0),
  pricingScore: integer('pricing_score').default(0),
  responsivenessScore: integer('responsiveness_score').default(0),
  complianceScore: integer('compliance_score').default(0),
  overallScore: real('overall_score').default(0),
  totalPosIssued: integer('total_pos_issued').default(0),
  totalPosOnTime: integer('total_pos_on_time').default(0),
  totalValueAwarded: real('total_value_awarded').default(0),
  disputeCount: integer('dispute_count').default(0),
  comments: text('comments'),
  status: text('status').notNull().default('draft'),
  nextReviewDate: text('next_review_date'),
  createdAt: text('erstellt_am').notNull(),
  updatedAt: text('aktualisiert_am').notNull(),
});

export const vendorBlacklistEvents = sqliteTable('vendor_blacklist_events', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull(),
  vendorId: text('vendor_id').notNull(),
  blacklistedBy: text('blacklisted_by').notNull(),
  reason: text('reason').notNull(),
  evidence: text('evidence'),
  blacklistedAt: text('blacklisted_am').notNull(),
  effectiveFrom: text('effective_from').notNull(),
  effectiveUntil: text('effective_until'),
  liftedBy: text('lifted_by'),
  liftedAt: text('lifted_am'),
  liftReason: text('lift_reason'),
  status: text('status').notNull().default('active'),
  createdAt: text('erstellt_am').notNull(),
});

export const vendorReviews = sqliteTable('vendor_reviews', {
  id: text('id').primaryKey(),
  companyId: text('unternehmen_id').notNull(),
  vendorId: text('vendor_id').notNull(),
  poId: text('po_id'),
  reviewedBy: text('reviewed_by').notNull(),
  role: text('rolle').notNull().default('procurement_officer'),
  decision: text('decision').notNull().default('no_action'),
  rating: integer('rating'),
  comments: text('comments'),
  reviewedAt: text('reviewed_am').notNull(),
  createdAt: text('erstellt_am').notNull(),
});

// NOTE: Business Automation tables (customers, orders, invoices, accounting)
// were removed from core schema. They will return as a plugin in the future.
// The physical SQLite tables remain for backward compatibility but are no longer
// managed by Drizzle. A future migration can drop them if needed.

// Export helper for all tables
export const allTables = {
  users,
  companies,
  agents,
  tasks,
  comments,
  chatMessages,
  agentMessages,
  agentMeetings,
  approvals,
  costEntries,
  activityLog,
  workCycles,
  goals,
  settings,
  agentWakeupRequests,
  routines,
  routineTrigger,
  routineRuns,
  workProducts,
  projects,
  agentPermissions,
  traceEvents,
  skillsLibrary,
  agentSkills,
  palaceWings,
  palaceDrawers,
  palaceDiary,
  palaceKg,
  palaceSummaries,
  budgetPolicies,
  budgetIncidents,
  executionWorkspaces,
  issueRelations,
  openclawTokens,
  agentConfigHistory,
  ceoDecisionLog,
  workerNodes,
  memoryEmbeddings,
  agentCapabilities,
  contractNetBids,
  agentVotes,
  agentTrustScores,
  workCyclesArchive,
  taskCheckpoints,
  learnedSkills,
  memoryConflicts,
  user,
  vendorBankDetails,
  vendorPerformanceReviews,
  vendorBlacklistEvents,
  vendorReviews,
  session,
  account,
  verification,
};
