import datetime
import logging

import pytest
from pytest_mock import MockerFixture
from scripts.cleanup.cleanup_big_query import (
    DEFAULT_MAX_AGE,
    TABLE_PATTERN,
    BigQueryConnectionConfig,
    cleanup_big_query,
    find_stale_table_ids,
)

from tests.integration.test_utils.data_source_config.sql import SQLBatchTestSetup

pytestmark = pytest.mark.unit

DATASET = "my-project.great_expectations_ci"
NOW = datetime.datetime(2026, 8, 6, 12, 0, tzinfo=datetime.timezone.utc)


class _NotFound(Exception):
    """Stands in for google.cloud.exceptions.NotFound.

    These tests run in environments without the Google client libraries installed,
    where `NotFound` is a NotImported sentinel that raises on any attribute access.
    Substituting a plain exception keeps the control flow under test -- that a table
    disappearing mid-sweep is tolerated rather than fatal -- without requiring the
    optional dependency.
    """


@pytest.fixture
def bigquery_module(mocker: MockerFixture):
    """Stand in for the `python_bigquery` module the script imported.

    Replaces the whole name rather than an attribute on it: without the optional
    dependency installed the name is a NotImported sentinel, which raises from both
    __getattr__ and __setattr__, so `python_bigquery.Client` cannot be patched.

    `new=` is passed explicitly because patch's default path inspects the object it
    is replacing -- `hasattr(original, "__func__")` -- and NotImported raises
    ModuleNotFoundError rather than AttributeError, which hasattr does not swallow.
    """
    module = mocker.MagicMock()
    mocker.patch("scripts.cleanup.cleanup_big_query.python_bigquery", new=module)
    mocker.patch("scripts.cleanup.cleanup_big_query.NotFound", new=_NotFound)
    return module


def _table(mocker: MockerFixture, table_id: str, age: datetime.timedelta | None):
    item = mocker.Mock()
    item.table_id = table_id
    item.created = None if age is None else NOW - age
    return item


@pytest.fixture
def frozen_now(mocker: MockerFixture):
    """Pin ``now`` so age comparisons are exact rather than clock-dependent."""
    dt = mocker.patch(
        "scripts.cleanup.cleanup_big_query.datetime.datetime", wraps=datetime.datetime
    )
    dt.now.return_value = NOW
    return dt


@pytest.fixture
def client(mocker: MockerFixture):
    return mocker.Mock()


@pytest.mark.parametrize(
    ("table_id", "expected"),
    [
        # Generated by SQLBatchTestSetup._create_table_name: prefix + uuid4 suffix,
        # optionally with a caller-supplied label in between.
        ("expectation_test_table_0f223e8357", True),
        ("expectation_test_table_col_b_15836bd07c", True),
        ("expectation_test_table_other_table_89d7676f8e", True),
        ("expectation_test_table_table_2_01ad98a61b", True),
        # Anything a person may have created deliberately in this dataset must survive.
        ("great_expectations_ci", False),
        ("users", False),
        ("my_reference_data", False),
        # Near misses on the generated shape.
        ("expectation_test_table", False),
        ("my_expectation_test_table_abcdef0123", False),
        ("expectation_test_table_NOTHEX0000", False),
        ("expectation_test_table_abcdef012", False),
        ("expectation_test_table_abcdef01234", False),
        # The dataset naming the old schema-based sweep looked for is not a table.
        ("gx_ci_test_abcdef0123", False),
    ],
)
def test_only_generated_test_tables_are_candidates(
    mocker: MockerFixture, frozen_now, client, table_id: str, expected: bool
):
    client.list_tables.return_value = [_table(mocker, table_id, datetime.timedelta(days=1))]

    stale = find_stale_table_ids(client, DATASET)

    assert stale == ([table_id] if expected else [])


@pytest.mark.parametrize("label", [None, "col_b", "other_table", "table_2"])
def test_the_pattern_matches_what_the_harness_actually_generates(label):
    """Pin the pattern to the generator it exists to describe.

    Every other test in this module types a table name out by hand, so all of them keep
    passing if the harness changes the names it produces -- and the sweeper would then
    match nothing, silently, with unbounded table growth as the only symptom. That is
    exactly the failure #12015 fixed for the schema-based sweep, where the pattern had
    drifted to one that could never match. Deriving the name from the harness means a
    change to the prefix, the separator, or the width of the random suffix fails here.

    `_create_table_name` is called with the class in place of `self`: the only attribute
    it reaches for is `_random_resource_name`, a staticmethod, and `SQLBatchTestSetup` is
    abstract, so there is no instance to build.
    """
    name = SQLBatchTestSetup._create_table_name(SQLBatchTestSetup, label)

    assert TABLE_PATTERN.match(name), f"sweeper pattern does not match generated name {name!r}"


def test_listed_and_matched_counts_are_reported_separately(
    mocker: MockerFixture, frozen_now, client, caplog
):
    """Tables present but none matched must not read like a clean dataset.

    Both end with nothing to delete. Only the counts tell a drifted pattern apart from
    genuinely having nothing to do, so a summary that collapses them is not a summary.
    """
    client.list_tables.return_value = [
        _table(mocker, "not_a_test_table", datetime.timedelta(days=1)),
        _table(mocker, "also_not_a_test_table", datetime.timedelta(days=1)),
    ]

    with caplog.at_level(logging.INFO, logger="scripts.cleanup.cleanup_big_query"):
        assert find_stale_table_ids(client, DATASET) == []

    assert "2 table(s)" in caplog.text
    assert "0 matched" in caplog.text


def test_recent_tables_are_left_alone(mocker: MockerFixture, frozen_now, client):
    """A run still in progress must not have its tables deleted underneath it."""
    client.list_tables.return_value = [
        _table(mocker, "expectation_test_table_aaaaaaaaaa", datetime.timedelta(minutes=5)),
        _table(mocker, "expectation_test_table_bbbbbbbbbb", datetime.timedelta(days=2)),
    ]

    assert find_stale_table_ids(client, DATASET) == ["expectation_test_table_bbbbbbbbbb"]


def test_table_exactly_at_the_age_threshold_is_left_alone(
    mocker: MockerFixture, frozen_now, client
):
    client.list_tables.return_value = [
        _table(mocker, "expectation_test_table_aaaaaaaaaa", DEFAULT_MAX_AGE)
    ]

    assert find_stale_table_ids(client, DATASET) == []


def test_table_with_unknown_creation_time_is_left_alone(mocker: MockerFixture, frozen_now, client):
    """Without an age we cannot distinguish a leftover from a table about to be queried."""
    client.list_tables.return_value = [_table(mocker, "expectation_test_table_aaaaaaaaaa", None)]

    assert find_stale_table_ids(client, DATASET) == []


def test_max_age_is_configurable(mocker: MockerFixture, frozen_now, client):
    client.list_tables.return_value = [
        _table(mocker, "expectation_test_table_aaaaaaaaaa", datetime.timedelta(minutes=5))
    ]

    assert find_stale_table_ids(client, DATASET, max_age=datetime.timedelta(minutes=1)) == [
        "expectation_test_table_aaaaaaaaaa"
    ]


def test_the_search_is_scoped_to_the_configured_dataset(mocker: MockerFixture, frozen_now, client):
    """Listing must stay dataset-scoped; enumerating the project is what we are avoiding."""
    client.list_tables.return_value = []

    find_stale_table_ids(client, DATASET)

    client.list_tables.assert_called_once_with(DATASET)
    client.list_datasets.assert_not_called()


def _config() -> BigQueryConnectionConfig:
    return BigQueryConnectionConfig(
        GE_TEST_GCP_PROJECT="my-project",
        GE_TEST_BIGQUERY_DATASET="great_expectations_ci",
        GOOGLE_APPLICATION_CREDENTIALS="creds.json",
    )


def test_cleanup_deletes_each_stale_table(mocker: MockerFixture, frozen_now, bigquery_module):
    client = mocker.Mock()
    bigquery_module.Client.return_value = client
    client.list_tables.return_value = [
        _table(mocker, "expectation_test_table_aaaaaaaaaa", datetime.timedelta(days=1)),
        _table(mocker, "expectation_test_table_bbbbbbbbbb", datetime.timedelta(days=1)),
        _table(mocker, "keep_me", datetime.timedelta(days=1)),
    ]

    cleanup_big_query(_config())

    assert sorted(c.args[0] for c in client.delete_table.call_args_list) == [
        f"{DATASET}.expectation_test_table_aaaaaaaaaa",
        f"{DATASET}.expectation_test_table_bbbbbbbbbb",
    ]


def test_cleanup_tolerates_a_table_vanishing_mid_sweep(
    mocker: MockerFixture, frozen_now, bigquery_module
):
    """A run finishing its own teardown between listing and deleting is not an error."""
    client = mocker.Mock()
    bigquery_module.Client.return_value = client
    client.list_tables.return_value = [
        _table(mocker, "expectation_test_table_aaaaaaaaaa", datetime.timedelta(days=1)),
        _table(mocker, "expectation_test_table_bbbbbbbbbb", datetime.timedelta(days=1)),
    ]
    client.delete_table.side_effect = [_NotFound("gone"), None]

    cleanup_big_query(_config())

    assert client.delete_table.call_count == 2


def test_cleanup_does_not_swallow_unexpected_delete_errors(
    mocker: MockerFixture, frozen_now, bigquery_module
):
    """Only a table already being gone is tolerable.

    Anything else -- a permissions problem, a transport failure -- means the sweep is
    not working and must be visible rather than logged as a routine skip.
    """
    client = mocker.Mock()
    bigquery_module.Client.return_value = client
    client.list_tables.return_value = [
        _table(mocker, "expectation_test_table_aaaaaaaaaa", datetime.timedelta(days=1))
    ]
    client.delete_table.side_effect = PermissionError("caller lacks bigquery.tables.delete")

    with pytest.raises(PermissionError):
        cleanup_big_query(_config())


def test_cleanup_makes_no_delete_calls_when_nothing_is_stale(
    mocker: MockerFixture, frozen_now, bigquery_module
):
    client = mocker.Mock()
    bigquery_module.Client.return_value = client
    client.list_tables.return_value = []

    cleanup_big_query(_config())

    client.delete_table.assert_not_called()
