fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(
            // Must mirror `generate_handler!` in src/main.rs exactly: this
            // list is what generates permissions/autogenerated/*.toml, and
            // the capability set can only reference identifiers generated
            // from here.
            tauri_build::AppManifest::new().commands(&[
                "show_desktop_notification",
                "save_workspace_file",
                "backend_health",
                "backend_logs_path",
                "desktop_logs_path",
                "app_backend_status",
                "app_remove_backend_server",
                "app_save_backend_server",
                "app_use_external_backend",
                "app_use_bundled_backend",
                "app_new_window",
                "app_stop_bundled_backend",
                "set_tray_session",
                "get_tray_usage_summary",
                "tray_action",
                "updater_check",
                "updater_download",
                "updater_install",
                "updater_release_notes",
                "secure_get_access_key",
                "secure_set_access_key",
                "secure_delete_access_key",
            ]),
        ),
    )
    .expect("failed to build Tauri application");
}
