/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as GitRouteImport } from './routes/git'
import { Route as PersonasRouteImport } from './routes/personas'
import { Route as TokenMaxingRouteImport } from './routes/token-maxing'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge/index'
import { Route as OperateIndexRouteImport } from './routes/operate/index'
import { Route as OperateCapabilitiesRouteImport } from './routes/operate/capabilities'
import { Route as OperateEventsRouteImport } from './routes/operate/events'
import { Route as OperateRunsRouteImport } from './routes/operate/runs'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioAutomationsRouteImport } from './routes/studio/automations'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as KnowledgeLibraryIndexRouteImport } from './routes/knowledge/library/index'
import { Route as KnowledgeLibraryAssetsRouteImport } from './routes/knowledge/library/assets'
import { Route as KnowledgeLibraryGraphRouteImport } from './routes/knowledge/library/graph'
import { Route as KnowledgeLibraryJournalRouteImport } from './routes/knowledge/library/journal'
import { Route as KnowledgeMemoryIndexRouteImport } from './routes/knowledge/memory/index'
import { Route as KnowledgeMemoryContradictionsRouteImport } from './routes/knowledge/memory/contradictions'
import { Route as KnowledgeMemoryEntitiesRouteImport } from './routes/knowledge/memory/entities'
import { Route as KnowledgeMemorySearchRouteImport } from './routes/knowledge/memory/search'
import { Route as KnowledgeMemoryTimelineRouteImport } from './routes/knowledge/memory/timeline'
import { Route as OperateProjectsIndexRouteImport } from './routes/operate/projects/index'
import { Route as OperateProjectsProjectIdRouteImport } from './routes/operate/projects/$projectId'
import { Route as OperateSystemConnectionsRouteImport } from './routes/operate/system/connections'
import { Route as OperateSystemMcpRouteImport } from './routes/operate/system/mcp'
import { Route as OperateSystemResourcesRouteImport } from './routes/operate/system/resources'
import { Route as OperateSystemSecurityRouteImport } from './routes/operate/system/security'
import { Route as OperateSystemSettingsRouteImport } from './routes/operate/system/settings'
import { Route as OperateSystemSkillsRouteImport } from './routes/operate/system/skills'
import { Route as StudioSessionsSessionIdRouteImport } from './routes/studio/sessions/$sessionId'

const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const GitRoute = GitRouteImport.update({
  id: '/git',
  path: '/git',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasRoute = PersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenMaxingRoute = TokenMaxingRouteImport.update({
  id: '/token-maxing',
  path: '/token-maxing',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperateIndexRoute = OperateIndexRouteImport.update({
  id: '/operate/',
  path: '/operate/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperateCapabilitiesRoute = OperateCapabilitiesRouteImport.update({
  id: '/operate/capabilities',
  path: '/operate/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const OperateEventsRoute = OperateEventsRouteImport.update({
  id: '/operate/events',
  path: '/operate/events',
  getParentRoute: () => rootRouteImport,
} as any)
const OperateRunsRoute = OperateRunsRouteImport.update({
  id: '/operate/runs',
  path: '/operate/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioAutomationsRoute = StudioAutomationsRouteImport.update({
  id: '/studio/automations',
  path: '/studio/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeLibraryIndexRoute = KnowledgeLibraryIndexRouteImport.update({
  id: '/knowledge/library/',
  path: '/knowledge/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeLibraryAssetsRoute = KnowledgeLibraryAssetsRouteImport.update({
  id: '/knowledge/library/assets',
  path: '/knowledge/library/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeLibraryGraphRoute = KnowledgeLibraryGraphRouteImport.update({
  id: '/knowledge/library/graph',
  path: '/knowledge/library/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeLibraryJournalRoute = KnowledgeLibraryJournalRouteImport.update({
  id: '/knowledge/library/journal',
  path: '/knowledge/library/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeMemoryIndexRoute = KnowledgeMemoryIndexRouteImport.update({
  id: '/knowledge/memory/',
  path: '/knowledge/memory/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeMemoryContradictionsRoute =
  KnowledgeMemoryContradictionsRouteImport.update({
    id: '/knowledge/memory/contradictions',
    path: '/knowledge/memory/contradictions',
    getParentRoute: () => rootRouteImport,
  } as any)
const KnowledgeMemoryEntitiesRoute = KnowledgeMemoryEntitiesRouteImport.update({
  id: '/knowledge/memory/entities',
  path: '/knowledge/memory/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeMemorySearchRoute = KnowledgeMemorySearchRouteImport.update({
  id: '/knowledge/memory/search',
  path: '/knowledge/memory/search',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeMemoryTimelineRoute = KnowledgeMemoryTimelineRouteImport.update({
  id: '/knowledge/memory/timeline',
  path: '/knowledge/memory/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const OperateProjectsIndexRoute = OperateProjectsIndexRouteImport.update({
  id: '/operate/projects/',
  path: '/operate/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperateProjectsProjectIdRoute =
  OperateProjectsProjectIdRouteImport.update({
    id: '/operate/projects/$projectId',
    path: '/operate/projects/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperateSystemConnectionsRoute =
  OperateSystemConnectionsRouteImport.update({
    id: '/operate/system/connections',
    path: '/operate/system/connections',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperateSystemMcpRoute = OperateSystemMcpRouteImport.update({
  id: '/operate/system/mcp',
  path: '/operate/system/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OperateSystemResourcesRoute = OperateSystemResourcesRouteImport.update({
  id: '/operate/system/resources',
  path: '/operate/system/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const OperateSystemSecurityRoute = OperateSystemSecurityRouteImport.update({
  id: '/operate/system/security',
  path: '/operate/system/security',
  getParentRoute: () => rootRouteImport,
} as any)
const OperateSystemSettingsRoute = OperateSystemSettingsRouteImport.update({
  id: '/operate/system/settings',
  path: '/operate/system/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OperateSystemSkillsRoute = OperateSystemSkillsRouteImport.update({
  id: '/operate/system/skills',
  path: '/operate/system/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSessionsSessionIdRoute = StudioSessionsSessionIdRouteImport.update({
  id: '/studio/sessions/$sessionId',
  path: '/studio/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/assets': typeof AssetsRoute
  '/git': typeof GitRoute
  '/personas': typeof PersonasRoute
  '/token-maxing': typeof TokenMaxingRoute
  '/operate/capabilities': typeof OperateCapabilitiesRoute
  '/operate/events': typeof OperateEventsRoute
  '/operate/runs': typeof OperateRunsRoute
  '/studio/automations': typeof StudioAutomationsRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/operate/': typeof OperateIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/knowledge/library/assets': typeof KnowledgeLibraryAssetsRoute
  '/knowledge/library/graph': typeof KnowledgeLibraryGraphRoute
  '/knowledge/library/journal': typeof KnowledgeLibraryJournalRoute
  '/knowledge/memory/contradictions': typeof KnowledgeMemoryContradictionsRoute
  '/knowledge/memory/entities': typeof KnowledgeMemoryEntitiesRoute
  '/knowledge/memory/search': typeof KnowledgeMemorySearchRoute
  '/knowledge/memory/timeline': typeof KnowledgeMemoryTimelineRoute
  '/operate/projects/$projectId': typeof OperateProjectsProjectIdRoute
  '/operate/system/connections': typeof OperateSystemConnectionsRoute
  '/operate/system/mcp': typeof OperateSystemMcpRoute
  '/operate/system/resources': typeof OperateSystemResourcesRoute
  '/operate/system/security': typeof OperateSystemSecurityRoute
  '/operate/system/settings': typeof OperateSystemSettingsRoute
  '/operate/system/skills': typeof OperateSystemSkillsRoute
  '/studio/sessions/$sessionId': typeof StudioSessionsSessionIdRoute
  '/knowledge/library/': typeof KnowledgeLibraryIndexRoute
  '/knowledge/memory/': typeof KnowledgeMemoryIndexRoute
  '/operate/projects/': typeof OperateProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/assets': typeof AssetsRoute
  '/git': typeof GitRoute
  '/personas': typeof PersonasRoute
  '/token-maxing': typeof TokenMaxingRoute
  '/operate/capabilities': typeof OperateCapabilitiesRoute
  '/operate/events': typeof OperateEventsRoute
  '/operate/runs': typeof OperateRunsRoute
  '/studio/automations': typeof StudioAutomationsRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/operate': typeof OperateIndexRoute
  '/studio': typeof StudioIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/knowledge/library/assets': typeof KnowledgeLibraryAssetsRoute
  '/knowledge/library/graph': typeof KnowledgeLibraryGraphRoute
  '/knowledge/library/journal': typeof KnowledgeLibraryJournalRoute
  '/knowledge/memory/contradictions': typeof KnowledgeMemoryContradictionsRoute
  '/knowledge/memory/entities': typeof KnowledgeMemoryEntitiesRoute
  '/knowledge/memory/search': typeof KnowledgeMemorySearchRoute
  '/knowledge/memory/timeline': typeof KnowledgeMemoryTimelineRoute
  '/operate/projects/$projectId': typeof OperateProjectsProjectIdRoute
  '/operate/system/connections': typeof OperateSystemConnectionsRoute
  '/operate/system/mcp': typeof OperateSystemMcpRoute
  '/operate/system/resources': typeof OperateSystemResourcesRoute
  '/operate/system/security': typeof OperateSystemSecurityRoute
  '/operate/system/settings': typeof OperateSystemSettingsRoute
  '/operate/system/skills': typeof OperateSystemSkillsRoute
  '/studio/sessions/$sessionId': typeof StudioSessionsSessionIdRoute
  '/knowledge/library': typeof KnowledgeLibraryIndexRoute
  '/knowledge/memory': typeof KnowledgeMemoryIndexRoute
  '/operate/projects': typeof OperateProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/assets': typeof AssetsRoute
  '/git': typeof GitRoute
  '/personas': typeof PersonasRoute
  '/token-maxing': typeof TokenMaxingRoute
  '/operate/capabilities': typeof OperateCapabilitiesRoute
  '/operate/events': typeof OperateEventsRoute
  '/operate/runs': typeof OperateRunsRoute
  '/studio/automations': typeof StudioAutomationsRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/operate/': typeof OperateIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/knowledge/library/assets': typeof KnowledgeLibraryAssetsRoute
  '/knowledge/library/graph': typeof KnowledgeLibraryGraphRoute
  '/knowledge/library/journal': typeof KnowledgeLibraryJournalRoute
  '/knowledge/memory/contradictions': typeof KnowledgeMemoryContradictionsRoute
  '/knowledge/memory/entities': typeof KnowledgeMemoryEntitiesRoute
  '/knowledge/memory/search': typeof KnowledgeMemorySearchRoute
  '/knowledge/memory/timeline': typeof KnowledgeMemoryTimelineRoute
  '/operate/projects/$projectId': typeof OperateProjectsProjectIdRoute
  '/operate/system/connections': typeof OperateSystemConnectionsRoute
  '/operate/system/mcp': typeof OperateSystemMcpRoute
  '/operate/system/resources': typeof OperateSystemResourcesRoute
  '/operate/system/security': typeof OperateSystemSecurityRoute
  '/operate/system/settings': typeof OperateSystemSettingsRoute
  '/operate/system/skills': typeof OperateSystemSkillsRoute
  '/studio/sessions/$sessionId': typeof StudioSessionsSessionIdRoute
  '/knowledge/library/': typeof KnowledgeLibraryIndexRoute
  '/knowledge/memory/': typeof KnowledgeMemoryIndexRoute
  '/operate/projects/': typeof OperateProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/assets'
    | '/git'
    | '/personas'
    | '/token-maxing'
    | '/operate/capabilities'
    | '/operate/events'
    | '/operate/runs'
    | '/studio/automations'
    | '/knowledge/'
    | '/operate/'
    | '/studio/'
    | '/workspace/'
    | '/knowledge/library/assets'
    | '/knowledge/library/graph'
    | '/knowledge/library/journal'
    | '/knowledge/memory/contradictions'
    | '/knowledge/memory/entities'
    | '/knowledge/memory/search'
    | '/knowledge/memory/timeline'
    | '/operate/projects/$projectId'
    | '/operate/system/connections'
    | '/operate/system/mcp'
    | '/operate/system/resources'
    | '/operate/system/security'
    | '/operate/system/settings'
    | '/operate/system/skills'
    | '/studio/sessions/$sessionId'
    | '/knowledge/library/'
    | '/knowledge/memory/'
    | '/operate/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assets'
    | '/git'
    | '/personas'
    | '/token-maxing'
    | '/operate/capabilities'
    | '/operate/events'
    | '/operate/runs'
    | '/studio/automations'
    | '/knowledge'
    | '/operate'
    | '/studio'
    | '/workspace'
    | '/knowledge/library/assets'
    | '/knowledge/library/graph'
    | '/knowledge/library/journal'
    | '/knowledge/memory/contradictions'
    | '/knowledge/memory/entities'
    | '/knowledge/memory/search'
    | '/knowledge/memory/timeline'
    | '/operate/projects/$projectId'
    | '/operate/system/connections'
    | '/operate/system/mcp'
    | '/operate/system/resources'
    | '/operate/system/security'
    | '/operate/system/settings'
    | '/operate/system/skills'
    | '/studio/sessions/$sessionId'
    | '/knowledge/library'
    | '/knowledge/memory'
    | '/operate/projects'
  id:
    | '__root__'
    | '/assets'
    | '/git'
    | '/personas'
    | '/token-maxing'
    | '/operate/capabilities'
    | '/operate/events'
    | '/operate/runs'
    | '/studio/automations'
    | '/knowledge/'
    | '/operate/'
    | '/studio/'
    | '/workspace/'
    | '/knowledge/library/assets'
    | '/knowledge/library/graph'
    | '/knowledge/library/journal'
    | '/knowledge/memory/contradictions'
    | '/knowledge/memory/entities'
    | '/knowledge/memory/search'
    | '/knowledge/memory/timeline'
    | '/operate/projects/$projectId'
    | '/operate/system/connections'
    | '/operate/system/mcp'
    | '/operate/system/resources'
    | '/operate/system/security'
    | '/operate/system/settings'
    | '/operate/system/skills'
    | '/studio/sessions/$sessionId'
    | '/knowledge/library/'
    | '/knowledge/memory/'
    | '/operate/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AssetsRoute: typeof AssetsRoute
  GitRoute: typeof GitRoute
  PersonasRoute: typeof PersonasRoute
  TokenMaxingRoute: typeof TokenMaxingRoute
  OperateCapabilitiesRoute: typeof OperateCapabilitiesRoute
  OperateEventsRoute: typeof OperateEventsRoute
  OperateRunsRoute: typeof OperateRunsRoute
  StudioAutomationsRoute: typeof StudioAutomationsRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  OperateIndexRoute: typeof OperateIndexRoute
  StudioIndexRoute: typeof StudioIndexRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  KnowledgeLibraryAssetsRoute: typeof KnowledgeLibraryAssetsRoute
  KnowledgeLibraryGraphRoute: typeof KnowledgeLibraryGraphRoute
  KnowledgeLibraryJournalRoute: typeof KnowledgeLibraryJournalRoute
  KnowledgeMemoryContradictionsRoute: typeof KnowledgeMemoryContradictionsRoute
  KnowledgeMemoryEntitiesRoute: typeof KnowledgeMemoryEntitiesRoute
  KnowledgeMemorySearchRoute: typeof KnowledgeMemorySearchRoute
  KnowledgeMemoryTimelineRoute: typeof KnowledgeMemoryTimelineRoute
  OperateProjectsProjectIdRoute: typeof OperateProjectsProjectIdRoute
  OperateSystemConnectionsRoute: typeof OperateSystemConnectionsRoute
  OperateSystemMcpRoute: typeof OperateSystemMcpRoute
  OperateSystemResourcesRoute: typeof OperateSystemResourcesRoute
  OperateSystemSecurityRoute: typeof OperateSystemSecurityRoute
  OperateSystemSettingsRoute: typeof OperateSystemSettingsRoute
  OperateSystemSkillsRoute: typeof OperateSystemSkillsRoute
  StudioSessionsSessionIdRoute: typeof StudioSessionsSessionIdRoute
  KnowledgeLibraryIndexRoute: typeof KnowledgeLibraryIndexRoute
  KnowledgeMemoryIndexRoute: typeof KnowledgeMemoryIndexRoute
  OperateProjectsIndexRoute: typeof OperateProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/git': {
      id: '/git'
      path: '/git'
      fullPath: '/git'
      preLoaderRoute: typeof GitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas': {
      id: '/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof PersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token-maxing': {
      id: '/token-maxing'
      path: '/token-maxing'
      fullPath: '/token-maxing'
      preLoaderRoute: typeof TokenMaxingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operate/': {
      id: '/operate/'
      path: '/operate'
      fullPath: '/operate/'
      preLoaderRoute: typeof OperateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operate/capabilities': {
      id: '/operate/capabilities'
      path: '/operate/capabilities'
      fullPath: '/operate/capabilities'
      preLoaderRoute: typeof OperateCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operate/events': {
      id: '/operate/events'
      path: '/operate/events'
      fullPath: '/operate/events'
      preLoaderRoute: typeof OperateEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operate/runs': {
      id: '/operate/runs'
      path: '/operate/runs'
      fullPath: '/operate/runs'
      preLoaderRoute: typeof OperateRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/automations': {
      id: '/studio/automations'
      path: '/studio/automations'
      fullPath: '/studio/automations'
      preLoaderRoute: typeof StudioAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/library/': {
      id: '/knowledge/library/'
      path: '/knowledge/library'
      fullPath: '/knowledge/library/'
      preLoaderRoute: typeof KnowledgeLibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/library/assets': {
      id: '/knowledge/library/assets'
      path: '/knowledge/library/assets'
      fullPath: '/knowledge/library/assets'
      preLoaderRoute: typeof KnowledgeLibraryAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/library/graph': {
      id: '/knowledge/library/graph'
      path: '/knowledge/library/graph'
      fullPath: '/knowledge/library/graph'
      preLoaderRoute: typeof KnowledgeLibraryGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/library/journal': {
      id: '/knowledge/library/journal'
      path: '/knowledge/library/journal'
      fullPath: '/knowledge/library/journal'
      preLoaderRoute: typeof KnowledgeLibraryJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/memory/': {
      id: '/knowledge/memory/'
      path: '/knowledge/memory'
      fullPath: '/knowledge/memory/'
      preLoaderRoute: typeof KnowledgeMemoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/memory/contradictions': {
      id: '/knowledge/memory/contradictions'
      path: '/knowledge/memory/contradictions'
      fullPath: '/knowledge/memory/contradictions'
      preLoaderRoute: typeof KnowledgeMemoryContradictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/memory/entities': {
      id: '/knowledge/memory/entities'
      path: '/knowledge/memory/entities'
      fullPath: '/knowledge/memory/entities'
      preLoaderRoute: typeof KnowledgeMemoryEntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/memory/search': {
      id: '/knowledge/memory/search'
      path: '/knowledge/memory/search'
      fullPath: '/knowledge/memory/search'
      preLoaderRoute: typeof KnowledgeMemorySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/memory/timeline': {
      id: '/knowledge/memory/timeline'
      path: '/knowledge/memory/timeline'
      fullPath: '/knowledge/memory/timeline'
      preLoaderRoute: typeof KnowledgeMemoryTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operate/projects/': {
      id: '/operate/projects/'
      path: '/operate/projects'
      fullPath: '/operate/projects/'
      preLoaderRoute: typeof OperateProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operate/projects/$projectId': {
      id: '/operate/projects/$projectId'
      path: '/operate/projects/$projectId'
      fullPath: '/operate/projects/$projectId'
      preLoaderRoute: typeof OperateProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operate/system/connections': {
      id: '/operate/system/connections'
      path: '/operate/system/connections'
      fullPath: '/operate/system/connections'
      preLoaderRoute: typeof OperateSystemConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operate/system/mcp': {
      id: '/operate/system/mcp'
      path: '/operate/system/mcp'
      fullPath: '/operate/system/mcp'
      preLoaderRoute: typeof OperateSystemMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operate/system/resources': {
      id: '/operate/system/resources'
      path: '/operate/system/resources'
      fullPath: '/operate/system/resources'
      preLoaderRoute: typeof OperateSystemResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operate/system/security': {
      id: '/operate/system/security'
      path: '/operate/system/security'
      fullPath: '/operate/system/security'
      preLoaderRoute: typeof OperateSystemSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operate/system/settings': {
      id: '/operate/system/settings'
      path: '/operate/system/settings'
      fullPath: '/operate/system/settings'
      preLoaderRoute: typeof OperateSystemSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operate/system/skills': {
      id: '/operate/system/skills'
      path: '/operate/system/skills'
      fullPath: '/operate/system/skills'
      preLoaderRoute: typeof OperateSystemSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/sessions/$sessionId': {
      id: '/studio/sessions/$sessionId'
      path: '/studio/sessions/$sessionId'
      fullPath: '/studio/sessions/$sessionId'
      preLoaderRoute: typeof StudioSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AssetsRoute: AssetsRoute,
  GitRoute: GitRoute,
  PersonasRoute: PersonasRoute,
  TokenMaxingRoute: TokenMaxingRoute,
  OperateCapabilitiesRoute: OperateCapabilitiesRoute,
  OperateEventsRoute: OperateEventsRoute,
  OperateRunsRoute: OperateRunsRoute,
  StudioAutomationsRoute: StudioAutomationsRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  OperateIndexRoute: OperateIndexRoute,
  StudioIndexRoute: StudioIndexRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  KnowledgeLibraryAssetsRoute: KnowledgeLibraryAssetsRoute,
  KnowledgeLibraryGraphRoute: KnowledgeLibraryGraphRoute,
  KnowledgeLibraryJournalRoute: KnowledgeLibraryJournalRoute,
  KnowledgeMemoryContradictionsRoute: KnowledgeMemoryContradictionsRoute,
  KnowledgeMemoryEntitiesRoute: KnowledgeMemoryEntitiesRoute,
  KnowledgeMemorySearchRoute: KnowledgeMemorySearchRoute,
  KnowledgeMemoryTimelineRoute: KnowledgeMemoryTimelineRoute,
  OperateProjectsProjectIdRoute: OperateProjectsProjectIdRoute,
  OperateSystemConnectionsRoute: OperateSystemConnectionsRoute,
  OperateSystemMcpRoute: OperateSystemMcpRoute,
  OperateSystemResourcesRoute: OperateSystemResourcesRoute,
  OperateSystemSecurityRoute: OperateSystemSecurityRoute,
  OperateSystemSettingsRoute: OperateSystemSettingsRoute,
  OperateSystemSkillsRoute: OperateSystemSkillsRoute,
  StudioSessionsSessionIdRoute: StudioSessionsSessionIdRoute,
  KnowledgeLibraryIndexRoute: KnowledgeLibraryIndexRoute,
  KnowledgeMemoryIndexRoute: KnowledgeMemoryIndexRoute,
  OperateProjectsIndexRoute: OperateProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
