#!/usr/bin/env node
/**
 * i18n Migration Script
 * Converts inline `de ? 'German' : 'English'` patterns to proper i18n keys.
 *
 * Usage:
 *   npx tsx scripts/i18n-migrate.ts src/pages/Dashboard.tsx
 *   npx tsx scripts/i18n-migrate.ts src/components/Sidebar.tsx
 *
 * The script:
 * 1. Extracts all `de ? 'German' : 'English'` patterns
 * 2. Generates camelCase keys from the English version
 * 3. Appends missing keys to src/i18n/de.ts and src/i18n/en.ts
 * 4. Replaces inline patterns with `t('generatedKey')`
 */

import fs from 'fs';
import path from 'path';

// Simple camelCase converter
function toCamelCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .split(/\s+/)
    .map((w, i) => i === 0 ? w.toLowerCase() : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('')
    .replace(/[^a-zA-Z0-9]/g, '')
    .slice(0, 40);
}

function extractPatterns(content: string): Array<{ full: string; de: string; en: string; key: string }> {
  const patterns: Array<{ full: string; de: string; en: string; key: string }> = [];
  const seen = new Set<string>();

  // Match: de ? 'German text' : 'English text'
  const regex = /de\s*\?\s*['"`]([^'"`]+)['"`]\s*:\s*['"`]([^'"`]+)['"`]/g;
  let match;
  while ((match = regex.exec(content)) !== null) {
    const full = match[0];
    const de = match[1].trim();
    const en = match[2].trim();
    const key = toCamelCase(en);
    if (!seen.has(key)) {
      seen.add(key);
      patterns.push({ full, de, en, key });
    }
  }

  // Also match: de ? `German ${var}` : `English ${var}`
  const regex2 = /de\s*\?\s*['"`]([^'"`]+)['"`]\s*:\s*\(/g;
  while ((match = regex2.exec(content)) !== null) {
    // Skip ternary with parenthesized expressions (complex cases)
  }

  return patterns;
}

function addKeysToI18n(keys: Array<{ de: string; en: string; key: string }>) {
  const dePath = path.join(process.cwd(), 'src/i18n/de.ts');
  const enPath = path.join(process.cwd(), 'src/i18n/en.ts');

  let deContent = fs.readFileSync(dePath, 'utf-8');
  let enContent = fs.readFileSync(enPath, 'utf-8');

  // Find insertion point: last `},` before `} as const;`
  const asConstIdx = deContent.lastIndexOf('} as const');
  const insertPoint = asConstIdx !== -1 ? asConstIdx : deContent.lastIndexOf('};');
  if (insertPoint === -1) {
    console.error('Could not find insertion point in de.ts');
    return;
  }

  let deInsert = '';
  let enInsert = '';

  for (const { key, de, en } of keys) {
    if (deContent.includes(`${key}:`)) {
      console.log(`  ⚠️  Key already exists: ${key}`);
      continue;
    }
    deInsert += `    ${key}: '${de.replace(/'/g, "\\'")}',
`;
    enInsert += `    ${key}: '${en.replace(/'/g, "\\'")}',
`;
    console.log(`  ✅ Added key: ${key}`);
  }

  if (deInsert) {
    // Insert before the last `};`
    deContent = deContent.slice(0, insertPoint) + '  autoGenerated: {\n' + deInsert + '  },\n' + deContent.slice(insertPoint);
    enContent = enContent.slice(0, insertPoint) + '  autoGenerated: {\n' + enInsert + '  },\n' + enContent.slice(insertPoint);

    fs.writeFileSync(dePath, deContent);
    fs.writeFileSync(enPath, enContent);
    console.log(`\n📝 Updated i18n files with ${keys.length} new keys in 'autoGenerated' section.`);
  }
}

function patchFile(filePath: string, patterns: Array<{ full: string; key: string }>) {
  let content = fs.readFileSync(filePath, 'utf-8');
  let count = 0;

  for (const { full, key } of patterns) {
    // Replace exact match with t('key')
    // We need to be careful with regex special chars
    const escaped = full.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(escaped, 'g');
    if (content.includes(full)) {
      content = content.replace(regex, `t('autoGenerated.${key}')`);
      count++;
    }
  }

  // Add useI18n import if not present
  if (count > 0 && !content.includes('useI18n')) {
    const importLine = "import { useI18n } from '../i18n';\n";
    const firstImport = content.indexOf('import ');
    if (firstImport !== -1) {
      content = content.slice(0, firstImport) + importLine + content.slice(firstImport);
    }
  }

  // Add const { t } = useI18n(); if not present
  if (count > 0 && !content.includes('const { t } = useI18n()')) {
    // Find the component function body start
    const funcMatch = content.match(/export function \w+\([^)]*\)\s*\{/);
    if (funcMatch) {
      const insertPos = funcMatch.index! + funcMatch[0].length;
      content = content.slice(0, insertPos) + "\n  const { t } = useI18n();" + content.slice(insertPos);
    }
  }

  fs.writeFileSync(filePath, content);
  console.log(`🔧 Patched ${count} patterns in ${path.basename(filePath)}`);
}

// ── Main ────────────────────────────────────────────────────────────────────
const targetFile = process.argv[2];
if (!targetFile) {
  console.error('Usage: npx tsx scripts/i18n-migrate.ts <file.tsx>');
  process.exit(1);
}

const fullPath = path.resolve(targetFile);
if (!fs.existsSync(fullPath)) {
  console.error(`File not found: ${fullPath}`);
  process.exit(1);
}

console.log(`\n🔍 Scanning ${targetFile}...`);
const content = fs.readFileSync(fullPath, 'utf-8');
const patterns = extractPatterns(content);

if (patterns.length === 0) {
  console.log('No inline translation patterns found.\n');
  process.exit(0);
}

console.log(`Found ${patterns.length} patterns:\n`);
for (const p of patterns) {
  console.log(`  ${p.key}`);
  console.log(`    DE: ${p.de.slice(0, 60)}`);
  console.log(`    EN: ${p.en.slice(0, 60)}`);
}

console.log('\n➕ Adding keys to i18n files...');
addKeysToI18n(patterns);

console.log('\n🔧 Patching source file...');
patchFile(fullPath, patterns);

console.log('\n✅ Done!\n');
