
global_batch_size: 8
model_name_or_path: NousResearch/Meta-Llama-3-8B-Instruct
trust_remote_code: true
attn: sdpa
optim: adamw_torch

stage: sft
do_train: true
finetuning_type: full

template: llama3
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 1

logging_steps: 1
save_strategy: "steps"
save_steps: 30
save_total_limit: 1
plot_loss: true

learning_rate: 2.0e-5
num_train_epochs: 1.0
max_steps: 30
warmup_steps: 3
max_grad_norm: 1.0
lr_scheduler_type: cosine
bf16: true
pure_bf16: true
gradient_checkpointing: true
push_to_hub: false
